ECOSYSTEM_RIVER = 'River'
ECOSYSTEM_WETLAND = 'Wetland'
ECOSYSTEM_OPEN_WATERBODY = 'Open waterbody'

ECOSYSTEM_TYPE_CHOICES = (
    (ECOSYSTEM_RIVER, ECOSYSTEM_RIVER),
    (ECOSYSTEM_WETLAND, ECOSYSTEM_WETLAND),
    (ECOSYSTEM_OPEN_WATERBODY, ECOSYSTEM_OPEN_WATERBODY)
)
