ECOSYSTEM_RIVER = 'River'
ECOSYSTEM_WETLAND = 'Wetland'
ECOSYSTEM_OPEN_WATERBODY = 'Open waterbody'

ECOSYSTEM_TYPE_CHOICES = (
    (ECOSYSTEM_RIVER, ECOSYSTEM_RIVER),
    (ECOSYSTEM_WETLAND, ECOSYSTEM_WETLAND),
    (ECOSYSTEM_OPEN_WATERBODY, ECOSYSTEM_OPEN_WATERBODY)
)

HYDROPERIOD_INUNDATED = 'Inundated'
HYDROPERIOD_SATURATED = 'Saturated at surface'
HYDROPERIOD_DRY = 'Dry at surface'

HYDROPERIOD_CHOICES = (
    (HYDROPERIOD_INUNDATED, HYDROPERIOD_INUNDATED),
    (HYDROPERIOD_SATURATED, HYDROPERIOD_SATURATED),
    (HYDROPERIOD_DRY, HYDROPERIOD_DRY),
)
