ECOSYSTEM_RIVER = 'River'
ECOSYSTEM_WETLAND = 'Wetland'
ECOSYSTEM_OPEN_WATERBODY = 'Open waterbody'
ECOSYSTEM_UNSPECIFIED = 'Unspecified'

ECOSYSTEM_TYPE_CHOICES = (
    (ECOSYSTEM_RIVER, ECOSYSTEM_RIVER),
    (ECOSYSTEM_WETLAND, ECOSYSTEM_WETLAND),
    (ECOSYSTEM_OPEN_WATERBODY, ECOSYSTEM_OPEN_WATERBODY)
)

HYDROPERIOD_INUNDATED = 'Inundated'
HYDROPERIOD_SATURATED = 'Saturated at surface'
HYDROPERIOD_DRY = 'Dry at surface'

HYDROPERIOD_CHOICES = (
    (HYDROPERIOD_INUNDATED, HYDROPERIOD_INUNDATED),
    (HYDROPERIOD_SATURATED, HYDROPERIOD_SATURATED),
    (HYDROPERIOD_DRY, HYDROPERIOD_DRY),
)

HYDROGEOMORPHIC_NONE = '-'
HYDROGEOMORPHIC_FLOODPLAIN = 'Floodplain'
HYDROGEOMORPHIC_CHANNELLED_VALLEY_BOTTOM = 'Channelled valley-bottom'
HYDROGEOMORPHIC_UNCHANNELLED_VALLEY_BOTTOM = 'Unchannelled valley-bottom'
HYDROGEOMORPHIC_SEEP = 'Seep'
HYDROGEOMORPHIC_DEPRESSION = 'Depression'
HYDROGEOMORPHIC_WETLAND_FLAT = 'Wetland flat'
HYDROGEOMORPHIC_UNKNOWN = 'Unknown'

HYDROGEOMORPHIC_CHOICES = (
    (HYDROGEOMORPHIC_NONE, HYDROGEOMORPHIC_NONE),
    (HYDROGEOMORPHIC_FLOODPLAIN, HYDROGEOMORPHIC_FLOODPLAIN),
    (HYDROGEOMORPHIC_CHANNELLED_VALLEY_BOTTOM, HYDROGEOMORPHIC_CHANNELLED_VALLEY_BOTTOM),
    (HYDROGEOMORPHIC_UNCHANNELLED_VALLEY_BOTTOM, HYDROGEOMORPHIC_UNCHANNELLED_VALLEY_BOTTOM),
    (HYDROGEOMORPHIC_SEEP, HYDROGEOMORPHIC_SEEP),
    (HYDROGEOMORPHIC_DEPRESSION, HYDROGEOMORPHIC_DEPRESSION),
    (HYDROGEOMORPHIC_WETLAND_FLAT, HYDROGEOMORPHIC_WETLAND_FLAT),
    (HYDROGEOMORPHIC_UNKNOWN, HYDROGEOMORPHIC_UNKNOWN),
)
