# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td_biblio', '0003_auto_20181115_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='td_biblio.Journal'),
        ),
    ]
