# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_biblio', '0004_auto_20191209_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=355, verbose_name='Title'),
        ),
    ]
