# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td_biblio', '0005_auto_20200308_0322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='editor',
            options={'ordering': ('first_name', 'last_name'), 'verbose_name': 'Editor', 'verbose_name_plural': 'Editors'},
        ),
    ]
