# Generated by Django 2.2.12 on 2020-05-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_biblio', '0005_auto_20200308_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('article', 'Article'), ('book', 'Book'), ('booklet', 'Book (no publisher)'), ('conference', 'Conference'), ('inbook', 'Book chapter'), ('incollection', 'Book from a collection'), ('inproceedings', 'Conference proceedings article'), ('manual', 'Technical documentation'), ('mastersthesis', "Master's Thesis"), ('misc', 'Miscellaneous'), ('phdthesis', 'PhD Thesis'), ('proceedings', 'Conference proceedings'), ('techreport', 'Technical report'), ('unpublished', 'Unpublished work')], default='article', max_length=50, verbose_name='Entry type'),
        ),
    ]
