# Generated by Django 2.2.12 on 2020-05-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td_biblio', '0006_auto_20200519_0407'),
        ('td_biblio', '0006_auto_20200526_1141'),
    ]

    operations = [
    ]
