# Generated by Django 4.1.10 on 2023-08-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_biblio', '0007_merge_20200529_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='crossref',
            field=models.ManyToManyField(blank=True, to='td_biblio.entry'),
        ),
    ]
