apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.rancher.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  containers:
    - image: rabbitmq:3.7-alpine
      name: rabbitmq
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
  restartPolicy: OnFailure
  volumes:
    - name: rabbitmq
      persistentVolumeClaim:
        claimName: rabbitmq
status: {}
