apiVersion: v1
kind: Deployment
metadata:
  name: not-important
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-bims
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-bims
