# Generated by Django 2.2.16 on 2022-03-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20200512_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='groupprofile',
            name='title_en',
        ),
    ]
