# Initially fitted by tailor on 2026-03-17
license: agpl-3.0

repository:
  description: Biodiversity Information Management System
  homepage: https://freshwaterbiodiversity.org/
  has_wiki: false
  has_discussions: false
  has_projects: false
  has_issues: true
  allow_merge_commit: false
  allow_squash_merge: true
  allow_rebase_merge: true
  squash_merge_commit_title: PR_TITLE
  squash_merge_commit_message: PR_BODY
  delete_branch_on_merge: true
  allow_update_branch: true
  allow_auto_merge: false
  web_commit_signoff_required: false
  default_workflow_permissions: read
  can_approve_pull_request_reviews: false
  topics:
    - biodiversity
    - django
    - python
    - gis
    - freshwater

labels:
  - name: bug
    color: d20f39
    description: "Something isn't working"

  - name: documentation
    color: 04a5e5
    description: "Documentation improvement"

  - name: duplicate
    color: 8839ef
    description: "Already exists"

  - name: enhancement
    color: 1e66f5
    description: "New feature request"

  - name: good first issue
    color: 40a02b
    description: "Good for newcomers"

  - name: help wanted
    color: "179299"
    description: "Extra attention needed"

  - name: invalid
    color: e64553
    description: "Not valid or relevant"

  - name: question
    color: 7287fd
    description: "Needs more information"

  - name: wontfix
    color: dc8a78
    description: "Will not be worked on"

  - name: dependencies
    color: fe640b
    description: "Dependency update"

  - name: github_actions
    color: ea76cb
    description: "GitHub Actions update"

  - name: hacktoberfest-accepted
    color: df8e1d
    description: "Hacktoberfest contribution"

swatches:
  - path: .github/workflows/tailor.yml
    alteration: always

  - path: .github/dependabot.yml
    alteration: first-fit

  - path: .github/FUNDING.yml
    alteration: first-fit

  - path: .github/ISSUE_TEMPLATE/bug_report.yml
    alteration: always

  - path: .github/ISSUE_TEMPLATE/feature_request.yml
    alteration: always

  - path: .github/ISSUE_TEMPLATE/config.yml
    alteration: first-fit

  - path: .github/pull_request_template.md
    alteration: always

  - path: SECURITY.md
    alteration: always

  - path: CODE_OF_CONDUCT.md
    alteration: always

  - path: CONTRIBUTING.md
    alteration: always

  - path: SUPPORT.md
    alteration: always

  - path: justfile
    alteration: never

  - path: flake.nix
    alteration: never

  - path: .gitignore
    alteration: first-fit

  - path: .envrc
    alteration: never

  - path: cubic.yaml
    alteration: never

  - path: .tailor.yml
    alteration: always

  - path: .github/workflows/tailor-automerge.yml
    alteration: triggered
