# Generated by Django 2.0.4 on 2018-04-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examplecollectionrecord',
            options={'verbose_name': 'fish', 'verbose_name_plural': 'fishes'},
        ),
    ]
