# Generated by Django 2.0.4 on 2018-04-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0003_auto_20180417_1146'),
        ('example', '0002_auto_20180417_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockCollectionRecord',
            fields=[
                ('biologicalcollectionrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bims.BiologicalCollectionRecord')),
                ('rock_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'rock',
                'verbose_name_plural': 'rocks',
            },
            bases=('bims.biologicalcollectionrecord',),
        ),
        migrations.AlterModelOptions(
            name='examplecollectionrecord',
            options={'verbose_name': 'example', 'verbose_name_plural': 'examples'},
        ),
    ]
