
SPECIES_NAME = 'Taxon'
TAXON_RANK = 'Taxon rank'
LATITUDE = 'Latitude'
LONGITUDE = 'Longitude'
LOCATION_SITE = 'Original River Name'
ORIGINAL_SITE_CODE = 'Original Site Code'
ORIGINAL_RIVER_NAME = 'Original River Name'
FBIS_SITE_CODE = 'FBIS Site Code'
SITE_DESCRIPTION = 'Site description'
REFINED_GEO_ZONE = 'Refined Geomorphological Zone'
ENDEMISM = 'Endemism'
CATEGORY = 'Category'
ORIGIN = 'Origin'
HABITAT = 'Habitat'
SAMPLING_METHOD = 'Sampling method'
SAMPLING_EFFORT = 'Sampling effort measure'
SAMPLING_EFFORT_VALUE = 'Sampling effort value'
ABUNDANCE_MEASURE = 'Abundance measure'
ABUNDANCE_VALUE = 'Abundance value'
CATCH_NUMBER = 'Catch/number'
CATCH_PER_UNIT = 'Catch Per Unit Effort (CPUE)'
# HYDRAULIC_BIOTOPE = 'Hydraulic biotope'
BROAD_BIOTOPE = 'Broad biotope'
SPECIFIC_BIOTOPE = 'Specific biotope'
SUBSTRATUM = 'Substratum'

# Chemical records
TEMP = 'TEMP'
CONDUCTIVITY = 'COND'
PH = 'PH'
DISSOLVED_OXYGEN_PERCENT = 'DOPER'
DISSOLVED_OXYGEN_MG = 'DO'
TURBIDITY = 'TURB'
ORTHOPHOSPHATE = 'SRP'
TOT = 'TOT-P'
SILICA = 'SI'
NH4_N = 'NH4-N'
NH3_N = 'NH3-N'
NO3_NO2_N = 'NO3+NO2-N'
NO2_N = 'NO2-N'
NO3_N = 'NO3-N'
TIN = 'TIN'
AFDM = 'AFDM'
CHLA_B = 'CHLA-B'

DEPTH_M = 'Depth'
NBV = 'Near Bed Velocity'
COLLECTOR_OR_OWNER = 'Collector/Owner'
CUSTODIAN = 'Collector/Owner Institute'
NUMBER_OF_REPLICATES = 'Number of replicates'
SAMPLING_DATE = 'Sampling Date'
UUID = 'UUID'
COLLECTOR = 'Collector/Owner'
NOTES = 'Notes'
REFERENCE = 'Reference'
REFERENCE_CATEGORY = 'Reference category'
DOI = 'DOI'
DOCUMENT_UPLOAD_LINK = 'Document Upload Link'
DOCUMENT_URL = 'URL'
DOCUMENT_TITLE = 'Title'
DOCUMENT_AUTHOR = 'Author(s)'
SOURCE_YEAR = 'Year'
SOURCE = 'Source'
PRESENT = 'Present'
COMMON_NAME = 'Common Name'

# Abiotic categorical values
WATER_LEVEL = 'Water Level'
WATER_TURBIDITY = 'Water Turbidity'
EMBEDDEDNESS = 'Embeddedness'

SURVEY_DATA = {
    WATER_LEVEL: 'Water level',
    WATER_TURBIDITY: 'Water turbidity',
    EMBEDDEDNESS: 'Embeddedness'
}