# Generated by Django 4.2.8 on 2024-04-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='on_trial',
            field=models.BooleanField(default=False),
        ),
    ]
