# Generated by Django 3.2.20 on 2023-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20200115_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
