# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 06:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0002_sitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='average_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='average_velocity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='canopy_cover',
            field=models.CharField(blank=True, choices=[(b'CLOSED', b'Closed'), (b'OPEN', b'Open'), (b'PARTIALLY_OPEN', b'Partially Open')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='discharge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='sass_version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitevisit',
            name='water_turbidity',
            field=models.CharField(blank=True, choices=[(b'CLEAR', b'Clear'), (b'DISCOLOURED', b'Discoloured'), (b'OPAQUE', b'Opaque'), (b'SILTY', b'Silty')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='water_level',
            field=models.CharField(blank=True, choices=[(b'DRY', b'Dry'), (b'ISOLATED_POOLS', b'Isolated pools'), (b'MODERATE_FLOW', b'Moderate flow'), (b'HIGH_FLOW', b'High flow'), (b'LOW_FLOW', b'Low flow'), (b'FLOOD', b'Flood')], max_length=100, null=True),
        ),
    ]
