# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0006_sassbiotope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
