# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0007_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SassBiotopeFraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.Rate')),
                ('sass_biotope', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.SassBiotope')),
            ],
        ),
    ]
