# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 02:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0009_sitevisit_sass_biotope_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
