# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 05:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0101_auto_20190110_0533'),
        ('sass', '0011_auto_20190110_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='SassTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('taxon_sass_4', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('sass_5_score', models.IntegerField(blank=True, null=True)),
                ('air_breather', models.IntegerField(blank=True, null=True)),
                ('display_order_sass_4', models.IntegerField(blank=True, null=True)),
                ('display_order_sass_5', models.IntegerField(blank=True, null=True)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.Taxon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
