# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0012_sasstaxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sasstaxon',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.Taxonomy'),
        ),
    ]
