# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0013_auto_20190110_0631'),
    ]

    operations = [
        migrations.AlterModelTable(name='SassBiotope', table='bims_sassbiotope'),
    ]
