# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0017_auto_20190114_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitbiotopetaxon',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
