# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0018_sitevisitbiotopetaxon_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SassValidationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('colour', models.CharField(blank=True, max_length=100, null=True)),
                ('colour_description', models.CharField(blank=True, max_length=100, null=True)),
                ('missing_ind', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
