# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0105_biotope_biotope_component'),
        ('sass', '0019_sassvalidationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitTaxon',
            fields=[
                ('biologicalcollectionrecord_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bims.BiologicalCollectionRecord')),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sass.SiteVisit')),
                ('taxon_abundance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sass.TaxonAbundance')),
            ],
            options={
                'abstract': False,
            },
            bases=('bims.biologicalcollectionrecord',),
        ),
    ]
