# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0020_sitevisittaxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='channel_type',
            field=models.CharField(blank=True, choices=[(b'BEDROCK', b'Bedrock'), (b'MIXED_BEDROCK_ALLUVIAL', b'Mixed bedrock and alluvial - dominant type(s)'), (b'ALLUVIAL', b'Alluvial with dominant type(s)')], max_length=200, null=True),
        ),
    ]
