# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-15 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0021_sitevisit_channel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chem_code', models.CharField(max_length=100)),
                ('chem_description', models.CharField(blank=True, max_length=200, null=True)),
                ('chem_unit', models.CharField(blank=True, choices=[(b'PERCENT', b'%'), (b'NTU', b'NTU'), (b'PER_100_ML', b'Per 100ml'), (b'M', b'm'), (b'MS_M', b'mS/m'), (b'MEQ_L', b'meq/l'), (b'MG_L', b'mg/l'), (b'OC', b'oC'), (b'PH_UNIT', b'pH unit')], max_length=200, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
