# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0024_sass5sheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sass5sheet',
            options={'verbose_name': 'SASS 5 Sheet', 'verbose_name_plural': 'SASS 5 Sheets'},
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_aquatic_vegetation',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_bedrock',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_gravel',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_hand_picking',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_margin_veg_in_current',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_margin_veg_out_of_current',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_mud',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_sand',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_stones_in_current',
        ),
        migrations.RemoveField(
            model_name='sass5sheet',
            name='biotype_stones_out_of_current',
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_aquatic_vegetation',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Aquatic Veg', max_length=10, null=True, verbose_name=b'Biotope Aquatic Veg'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_bedrock',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Bedrock', max_length=10, null=True, verbose_name=b'Biotope Bedrock'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_gravel',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Gravel', max_length=10, null=True, verbose_name=b'Biotope Gravel'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_hand_picking',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Hand Picking', max_length=10, null=True, verbose_name=b'Biotope Hand Picking'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_margin_veg_in_current',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope MargVeg In Current', max_length=10, null=True, verbose_name=b'Biotope MargVeg In Current'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_margin_veg_out_of_current',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope MargVeg Out Of Current', max_length=10, null=True, verbose_name=b'Biotope MargVeg Out Of Current'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_mud',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Mud', max_length=10, null=True, verbose_name=b'Biotope Mud'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_sand',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Sand', max_length=10, null=True, verbose_name=b'Biotope Sand'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_stones_in_current',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Stones In Current (SIC)', max_length=10, null=True, verbose_name=b'Biotope Stones In Current (SIC)'),
        ),
        migrations.AddField(
            model_name='sass5sheet',
            name='biotope_stones_out_of_current',
            field=models.CharField(blank=True, choices=[(b'RATING_1', b'1'), (b'RATING_2', b'2'), (b'RATING_3', b'3'), (b'RATING_4', b'4'), (b'RATING_5', b'5')], help_text=b'Biotope Stones Out Of Current (SOOC)', max_length=10, null=True, verbose_name=b'Biotope Stones Out Of Current (SOOC)'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='collector_sampler',
            field=models.CharField(blank=True, help_text=b'Collector/Sampler', max_length=255, null=True, verbose_name=b'Collector/Sampler'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='do_mg_per_litre',
            field=models.FloatField(blank=True, help_text=b'DO (mg/L)', null=True, verbose_name=b'DO (mg/L)'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='flow',
            field=models.FloatField(blank=True, help_text=b'Flow', null=True, verbose_name=b'Flow'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='instream_disturbance',
            field=models.CharField(blank=True, help_text=b'Instream Disturbance', max_length=100, null=True, verbose_name=b'Instream Disturbance'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='ph',
            field=models.FloatField(blank=True, help_text=b'pH', null=True, verbose_name=b'pH'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='rhp_site_code',
            field=models.CharField(blank=True, help_text=b'RHP Site Code', max_length=10, null=True, verbose_name=b'RHP Site Code'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='riparian_disturbance',
            field=models.CharField(blank=True, help_text=b'Riparian Disturbance', max_length=100, null=True, verbose_name=b'Riparian Disturbance'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='temp_centigrade',
            field=models.FloatField(blank=True, help_text=b'Temp (\xcb\x9aC)', null=True, verbose_name=b'Temp (\xcb\x9aC)'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='time_minutes',
            field=models.IntegerField(blank=True, help_text=b'Time (min)', null=True, verbose_name=b'Time (min)'),
        ),
        migrations.AlterField(
            model_name='sass5sheet',
            name='zonation',
            field=models.CharField(blank=True, help_text=b'Zonation', max_length=100, null=True, verbose_name=b'Zonation'),
        ),
    ]
