# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0107_biologicalcollectionrecord_source_collection'),
        ('sass', '0025_auto_20190117_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='SASS5Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, help_text=b'Count', null=True)),
                ('stone_and_rock', models.IntegerField(blank=True, help_text=b'Stone and Rock (S)', null=True, verbose_name=b'Stone and Rock (S)')),
                ('vegetation', models.IntegerField(blank=True, help_text=b'Vegetation (Veg)', null=True, verbose_name=b'Vegetation (Veg)')),
                ('gravel_sand_mud', models.IntegerField(blank=True, help_text=b'Gravel Sand Mud (GSM)', null=True, verbose_name=b'Gravel Sand Mud (GSM)')),
                ('family', models.ForeignKey(blank=True, help_text=b'Taxonomy Family', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Taxonomy', verbose_name=b'Family')),
                ('sass_sheet', models.ForeignKey(help_text=b'SASS Sheet', on_delete=django.db.models.deletion.CASCADE, to='sass.SASS5Sheet', verbose_name=b'SASS Sheet')),
            ],
            options={
                'verbose_name': 'SASS 5 Record',
                'verbose_name_plural': 'SASS 5 Records',
            },
        ),
    ]
