# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-18 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0027_auto_20190118_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasstaxon',
            name='taxon_sass_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sass5record',
            name='taxonomy',
            field=models.ForeignKey(blank=True, help_text=b'Family/Order Taxonomy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sass.SassTaxon', verbose_name=b'Family/Order Taxonomy'),
        ),
    ]
