# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0031_auto_20190205_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitbiotopetaxon',
            name='sass_taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.SassTaxon'),
        ),
    ]
