# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0032_sitevisitbiotopetaxon_sass_taxon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisittaxon',
            name='sass_taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.SassTaxon'),
        ),
    ]
