# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 06:40
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0034_sitevisit_data_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SassEcologicalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('colour', colorfield.fields.ColorField(default=b'#009106', max_length=18)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SassEcologicalCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoregion_level_1', models.CharField(max_length=200)),
                ('geomorphological_zone', models.CharField(blank=True, max_length=200, null=True)),
                ('sass_score_precentile', models.IntegerField(blank=True, null=True)),
                ('aspt_score_precentile', models.FloatField(blank=True, null=True)),
                ('ecological_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.SassEcologicalCategory')),
            ],
        ),
    ]
