# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-25 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0035_sassecologicalcategory_sassecologicalcondition'),
        ('sass', '0030_samplingmethod'),
    ]

    operations = [
    ]
