# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0036_merge_20190225_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chem',
            options={'verbose_name': 'Chemistry record', 'verbose_name_plural': 'Chemistry records'},
        ),
        migrations.AlterModelOptions(
            name='sassbiotopefraction',
            options={'verbose_name': 'SASS biotope fraction', 'verbose_name_plural': 'SASS biotope fractions'},
        ),
        migrations.AlterModelOptions(
            name='sasstaxon',
            options={'verbose_name': 'SASS taxon', 'verbose_name_plural': 'SASS taxa'},
        ),
        migrations.AlterModelOptions(
            name='sassvalidationstatus',
            options={'verbose_name': 'SASS validation status', 'verbose_name_plural': 'SASS validation statuses'},
        ),
        migrations.AlterModelOptions(
            name='sitevisitbiotopetaxon',
            options={'verbose_name_plural': 'Site visit biotope taxa'},
        ),
        migrations.AlterModelOptions(
            name='sitevisitchem',
            options={'verbose_name': 'Site visit chemistry record', 'verbose_name_plural': 'Site visit chemistry records'},
        ),
        migrations.AlterModelOptions(
            name='sitevisittaxon',
            options={'verbose_name_plural': 'Site visit taxa'},
        ),
    ]
