# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0037_auto_20190226_0923'),
        ('sass', '0036_auto_20190226_0630'),
    ]

    operations = [
    ]
