# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0038_merge_20190305_0552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SamplingMethod',
        ),
    ]
