# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-18 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0040_sitevisitecologicalcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sasstaxon',
            name='rating_scale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
