# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0042_auto_20190812_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='sass_biotope_fraction',
            field=models.ManyToManyField(blank=True, to='sass.SassBiotopeFraction'),
        ),
    ]
