# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0045_migrate_sass_asessor_to_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisit',
            name='assessor',
        ),
    ]
