# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-13 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0046_remove_sitevisit_assessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chem',
            name='decimal_place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
