# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0047_chem_decimal_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisitchem',
            name='chem',
            field=models.IntegerField(),
        ),
    ]
