# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0048_auto_20191021_0924'),
    ]

    database_operations = [
        migrations.AlterModelTable('chem', 'bims_chem')
    ]

    state_operations = [
        migrations.DeleteModel('chem')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
