# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-22 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0051_auto_20191022_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitevisitchem',
            name='chem',
        ),
        migrations.RemoveField(
            model_name='sitevisitchem',
            name='site_visit',
        ),
        migrations.DeleteModel(
            name='SiteVisitChem',
        ),
    ]
