# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0052_auto_20191022_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='embeddedness',
            field=models.CharField(blank=True, choices=[(b'0-25', b'0-25'), (b'26-50', b'26-50'), (b'51-75', b'51-75'), (b'76-100', b'76-100')], default=b'', max_length=50),
        ),
    ]
