# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sass', '0053_sitevisit_embeddedness'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text=b'The person that did the analysis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='river_analyst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='river',
            name='collector_user',
            field=models.ForeignKey(blank=True, help_text=b'The user object of the actual capturer/collector of this data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='river_collector_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
