# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-19 06:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0054_auto_20200305_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
