# Generated by Django 2.2.12 on 2020-05-19 04:07

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0055_auto_20200319_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text='The person that did the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='river_analyst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='river',
            name='collector_user',
            field=models.ForeignKey(blank=True, help_text='The user object of the actual capturer/collector of this data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='river_collector_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sassecologicalcategory',
            name='colour',
            field=colorfield.fields.ColorField(default='#009106', max_length=18),
        ),
        migrations.AlterField(
            model_name='sassecologicalcondition',
            name='ecological_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sass.SassEcologicalCategory'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='canopy_cover',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PARTIALLY_OPEN', 'Partially Open')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='channel_type',
            field=models.CharField(blank=True, choices=[('BEDROCK', 'Bedrock'), ('MIXED_BEDROCK_ALLUVIAL', 'Mixed bedrock and alluvial - dominant type(s)'), ('ALLUVIAL', 'Alluvial with dominant type(s)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='collector',
            field=models.ForeignKey(blank=True, help_text='Actual capturer/collector of this data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitevisit_data_collector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.DataSource'),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='embeddedness',
            field=models.CharField(blank=True, choices=[('0-25', '0-25'), ('26-50', '26-50'), ('51-75', '51-75'), ('76-100', '76-100')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Creator/owner of this data from the web', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitevisit_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='water_level',
            field=models.CharField(blank=True, choices=[('DRY', 'Dry'), ('ISOLATED_POOLS', 'Isolated pools'), ('MODERATE_FLOW', 'Moderate flow'), ('HIGH_FLOW', 'High flow'), ('LOW_FLOW', 'Low flow'), ('FLOOD', 'Flood')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='water_turbidity',
            field=models.CharField(blank=True, choices=[('SILTY', 'Silty'), ('OPAQUE', 'Opaque'), ('DISCOLOURED', 'Discoloured'), ('CLEAR', 'Clear')], max_length=100, null=True),
        ),
    ]
