# Generated by Django 4.1.10 on 2023-12-05 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0059_alter_river_analyst_alter_river_collector_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='end_embargo_date',
            field=models.DateField(blank=True, help_text='The date when the embargo on the data expires. After this date, the data will become public.', null=True),
        ),
    ]
