# Generated by Django 4.2.11 on 2024-07-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0062_river_accuracy_of_identification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='accuracy_of_identification',
        ),
        migrations.RemoveField(
            model_name='river',
            name='accuracy_of_locality',
        ),
        migrations.AddField(
            model_name='river',
            name='accuracy_of_coordinates',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='river',
            name='certainty_of_identification',
            field=models.CharField(blank=True, default=''),
        ),
    ]
