# Generated by Django 4.2.16 on 2025-03-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0063_remove_river_accuracy_of_identification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='source_site',
        ),
    ]
