# Generated by Django 6.0.2 on 2026-08-21 10:01

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def dedupe_site_visit_ecological_condition(apps, schema_editor):
    """Keep only the most recent condition row per site visit.

    Multiple SiteVisitEcologicalCondition rows for the same site_visit
    were never supposed to exist (one SASS assessment -> one ecological
    condition), but the lack of a DB constraint let duplicates slip in.
    The most recent row (highest id) is kept, matching what the
    generator script already did defensively when it found duplicates.
    """
    SiteVisitEcologicalCondition = apps.get_model(
        'sass', 'SiteVisitEcologicalCondition')
    duplicate_site_visits = (
        SiteVisitEcologicalCondition.objects
        .values('site_visit')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
        .values_list('site_visit', flat=True)
    )
    for site_visit_id in duplicate_site_visits:
        ids_to_keep = (
            SiteVisitEcologicalCondition.objects
            .filter(site_visit_id=site_visit_id)
            .order_by('-id')
            .values_list('id', flat=True)[:1]
        )
        SiteVisitEcologicalCondition.objects.filter(
            site_visit_id=site_visit_id
        ).exclude(id__in=list(ids_to_keep)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0065_alter_river_collector_user_alter_river_owner'),
    ]

    operations = [
        migrations.RunPython(
            dedupe_site_visit_ecological_condition,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='sitevisitecologicalcondition',
            name='site_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sass.sitevisit', unique=True),
        ),
    ]
