#--------- Generic stuff all our Dockerfiles should start with so we get caching ------------
# Note this base image is based on debian
FROM kartoza/kbims_uwsgi:latest
MAINTAINER Dimas Ciputra<dimas@kartoza.com>

#USER www-data
WORKDIR /usr/src/bims

ADD uwsgi.conf /uwsgi.conf
# Open port 8080 as we will be running our uwsgi socket on that
EXPOSE 8080

CMD ["uwsgi", "--ini", "/uwsgi.conf"]