# syntax=docker/dockerfile:1
FROM python:3.12.3-slim-bookworm
ARG TIPPECANOE_VERSION=2.79.0
RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    apt-get update && apt-get install -y --no-install-recommends \
      git make g++ \
      libprotobuf-dev protobuf-compiler zlib1g-dev libsqlite3-dev
RUN git clone --depth 1 --branch "${TIPPECANOE_VERSION}" \
      https://github.com/felt/tippecanoe.git /tmp/tippecanoe && \
    make -C /tmp/tippecanoe -j"$(nproc)" && \
    make -C /tmp/tippecanoe install
