# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 15:59


from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_resourcebase_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
