# Generated by Django 2.2.16 on 2022-03-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20201116_0929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.RemoveField(
            model_name='link',
            name='resource',
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menu',
            name='placeholder',
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='license',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='license',
            name='license_text_en',
        ),
        migrations.RemoveField(
            model_name='license',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='restrictioncodetype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='restrictioncodetype',
            name='gn_description_en',
        ),
        migrations.RemoveField(
            model_name='spatialrepresentationtype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='spatialrepresentationtype',
            name='gn_description_en',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='gn_description_en',
        ),
        migrations.DeleteModel(
            name='CuratedThumbnail',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='MenuPlaceholder',
        ),
    ]
