# Generated by Django 3.2.20 on 2023-07-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20220330_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicalkeyword',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
