# Generated by Django 4.2.8 on 2024-06-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_resourcebase_polymorphic_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hierarchicalkeyword',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='hierarchicalkeyword',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='hierarchicalkeyword',
            name='path',
        ),
    ]
