# Generated by Django 4.2.16 on 2025-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_remove_hierarchicalkeyword_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebase',
            name='title',
            field=models.CharField(help_text='name by which the cited resource is known', max_length=512, verbose_name='title'),
        ),
    ]
