# Generated by Django 4.2.25 on 2025-12-10 09:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bims', '0484_allow_multiple_harvest_schedules_per_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, default='', help_text='Name of the weather station', max_length=255)),
                ('date', models.DateField(help_text='Date of the climate observation')),
                ('year', models.IntegerField(help_text='Year of observation', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.IntegerField(help_text='Month of observation (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.IntegerField(help_text='Day of observation (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('avg_temperature', models.FloatField(blank=True, help_text='Average daily temperature (°C)', null=True)),
                ('max_temperature', models.FloatField(blank=True, help_text='Maximum daily temperature (°C)', null=True)),
                ('min_temperature', models.FloatField(blank=True, help_text='Minimum daily temperature (°C)', null=True)),
                ('avg_humidity', models.FloatField(blank=True, help_text='Average daily relative humidity (%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_humidity', models.FloatField(blank=True, help_text='Maximum relative humidity (%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_humidity', models.FloatField(blank=True, help_text='Minimum relative humidity (%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('avg_windspeed', models.FloatField(blank=True, help_text='Average daily wind speed (m/s)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_rainfall', models.FloatField(blank=True, help_text='Daily rainfall (mm)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('location_site', models.ForeignKey(help_text='The location site where this climate data was recorded', on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='bims.locationsite')),
            ],
            options={
                'verbose_name': 'Climate Data',
                'verbose_name_plural': 'Climate Data',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['location_site', 'date'], name='climate_cli_locatio_657a2f_idx'), models.Index(fields=['date'], name='climate_cli_date_f4cfbc_idx'), models.Index(fields=['year', 'month'], name='climate_cli_year_de7a51_idx')],
                'unique_together': {('location_site', 'date')},
            },
        ),
    ]
