# Generated by Django 2.0.4 on 2018-05-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0005_carouselheader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselheader',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
