# Generated by Django 2.0.5 on 2018-05-28 10:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0006_auto_20180529_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='BoundaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=128)),
                ('site_count', models.IntegerField(default=0)),
                ('details', models.TextField(default='')),
                ('boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.Boundary')),
            ],
        ),
        migrations.AddField(
            model_name='boundary',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.BoundaryType'),
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together={('boundary', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='boundary',
            unique_together={('name', 'type')},
        ),
    ]
