# Generated by Django 2.0.6 on 2018-06-24 06:21

import bims.models.taxonomy
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0008_category_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='accepted_key',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Accepted Key'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='accepted_name',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Accepted Name'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='family',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Family'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='genus',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Genus'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='kingdom',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Kingdom'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='order',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='phylum',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Phylum'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='species',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Species'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='taxon_class',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Class'),
        ),
        migrations.AddField(
            model_name='taxon',
            name='taxon_id',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Taxon ID'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='author',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='common_name',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Common Name'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='scientific_name',
            field=bims.models.taxonomy.TaxonomyField(blank=True, default='', max_length=100, verbose_name='Scientific Name'),
        ),
    ]
