# Generated by Django 2.0.6 on 2018-06-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0009_auto_20180624_0821'),
        ('bims', '0009_csvdocument'),
    ]

    operations = [
    ]
