# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0010_merge_20180625_0607'),
        ('bims', '0009_auto_20180621_0200'),
    ]

    operations = [
    ]
