# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0010_merge_20180625_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bims_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
