# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0011_boundary_centroid'),
        ('bims', '0009_auto_20180621_0200'),
    ]

    operations = [
    ]
