# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0011_boundary_centroid'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundary',
            name='code_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='boundary',
            name='top_level_boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.Boundary'),
        ),
        migrations.AddField(
            model_name='boundarytype',
            name='level',
            field=models.IntegerField(blank=True, help_text=b'what level of this boundary type', null=True),
        ),
    ]
