# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0014_auto_20180702_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='code_name',
            field=models.CharField(default='EMPTY', max_length=128),
        ),
        migrations.AlterField(
            model_name='boundarytype',
            name='level',
            field=models.IntegerField(blank=True, help_text='what level of this boundary type', null=True),
        ),
    ]
