# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0014_auto_20180702_0527'),
        ('bims', '0011_auto_20180702_0443'),
    ]

    operations = [
    ]
