# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0016_taxon_vernacularnames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='vernacularNames',
            new_name='vernacular_names',
        ),
    ]
