# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 06:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0017_auto_20180717_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='vernacular_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=b'', max_length=100), default=[], null=True, size=None, verbose_name=b'Vernacular Names'),
        ),
    ]
