# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0019_auto_20180717_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shapefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapefile', models.FileField(upload_to=b'shapefile/')),
            ],
            options={
                'verbose_name': 'Shapefile',
                'verbose_name_plural': 'Shapefiles',
            },
        ),
        migrations.CreateModel(
            name='ShapefileUploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('shapefiles', models.ManyToManyField(to='bims.Shapefile')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shapefile Upload Session',
                'verbose_name_plural': 'Shapefile Upload Sessions',
            },
        ),
    ]
