# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0020_shapefile_shapefileuploadsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefileuploadsession',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
