# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0016_nonbiodiversitylayer'),
        ('bims', '0023_shapefileuploadsession_token'),
    ]

    operations = [
    ]
