# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0024_merge_20180719_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='collector',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'collector or observer'),
        ),
    ]
