# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0024_merge_20180719_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='location_context_document',
            field=models.TextField(blank=True, help_text=b'This document is generated from GeoContext by using management command or changing the geometry.', null=True, verbose_name=b'Document for location context as JSON.'),
        ),
    ]
