# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0026_auto_20180727_0851'),
        ('bims', '0015_auto_20180705_1151'),
    ]

    operations = [
    ]
