# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0026_auto_20180727_0851'),
        ('bims', '0025_auto_20180730_0523'),
    ]

    operations = [
    ]
