# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0027_merge_20180730_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVDocument',
        ),
    ]
