# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-01 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0027_merge_20180731_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biologicalcollectionrecord',
            options={'permissions': (('can_upload_csv', 'Can upload CSV'), ('can_upload_shapefile', 'Can upload Shapefile'))},
        ),
    ]
