# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-08 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0025_create_administrative_layer'),
        ('bims', '0030_auto_20180801_0604'),
    ]

    operations = [
    ]
