# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0030_biologicalcollectionrecord_ready_for_validation'),
        ('bims', '0030_auto_20180801_0604'),
    ]

    operations = [
    ]
