# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0029_auto_20180731_1016'),
        ('bims', '0030_auto_20180801_0604'),
    ]

    operations = [
    ]
