# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 03:23
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0031_merge_20180808_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='iucnstatus',
            name='colour',
            field=colorfield.fields.ColorField(default=b'#009106', max_length=18),
        ),
    ]
