# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-13 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0031_merge_20180807_0804'),
        ('bims', '0032_iucnstatus_colour'),
    ]

    operations = [
    ]
