# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-20 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0033_merge_20180813_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.Boundary'),
        ),
    ]
