# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0033_merge_20180813_1001'),
        ('bims', '0031_merge_20180801_0833'),
    ]

    operations = [
    ]
