# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-21 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0034_locationsite_boundary'),
        ('bims', '0034_profile_hide_bims_info'),
    ]

    operations = [
    ]
