# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0035_merge_20180821_0538'),
        ('bims', '0034_merge_20180820_0836'),
    ]

    operations = [
    ]
