# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-27 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0036_merge_20180822_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to=b'csv/')),
            ],
            options={
                'verbose_name': 'CSV Document',
                'verbose_name_plural': 'CSV Documents',
            },
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='category',
            field=models.CharField(blank=True, choices=[(b'alien', b'Non-native'), (b'indigenous', b'Native'), (b'translocated', b'Translocated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='boundary',
            field=models.ForeignKey(blank=True, help_text=b'This is lowest boundary where location is placed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.Boundary'),
        ),
    ]
