# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-29 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0037_auto_20180827_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='institution_id',
            field=models.CharField(default=b'LEDET', help_text=b'An identifier for the institution having custody of the object(s) or information referred to in the record.', max_length=50),
        ),
    ]
