# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-03 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0038_biologicalcollectionrecord_institution_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='LinkCategory',
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='institution_id',
            field=models.CharField(default=b'LEDET', help_text=b'An identifier for the institution having custody of the object(s) or information referred to in the record.', max_length=50, verbose_name=b'Custodian'),
        ),
        migrations.AlterField(
            model_name='iucnstatus',
            name='category',
            field=models.CharField(blank=True, choices=[(b'LC', b'Least Concern'), (b'NT', b'Near Threatened'), (b'VU', b'Vulnerable'), (b'EN', b'Endangered'), (b'CR', b'Critically Endangered'), (b'EW', b'Extinct In The Wild'), (b'EX', b'Extinct'), (b'DD', b'Data Deficient')], default=b'', max_length=50),
        ),
    ]
