# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0040_userboundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='endemism',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='reference',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='reference_category',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='sampling_effort',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='sampling_method',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
