# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0041_auto_20180928_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='site_code',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
