# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-28 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0042_locationsite_site_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationsite',
            old_name='description',
            new_name='site_description',
        ),
    ]
