# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-01 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0043_auto_20180928_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='institution_id',
            field=models.CharField(default=b'LEDET', help_text=b'An identifier for the institution having custody of the object(s) or information referred to in the record.', max_length=100, verbose_name=b'Custodian'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='reference',
            field=models.CharField(blank=True, default=b'', max_length=300),
        ),
    ]
