# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0043_auto_20180928_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='site_description',
            field=models.CharField(blank=True, default=b'', max_length=500),
        ),
    ]
