# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-02 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0044_auto_20181001_0703'),
        ('bims', '0044_auto_20181001_0730'),
    ]

    operations = [
    ]
