# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-09 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0045_merge_20181002_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('category', models.CharField(choices=[(b'cluster_generation', b'Cluster Generation'), (b'search_results', b'Search Results')], max_length=50)),
                ('query', models.CharField(max_length=500)),
                ('process_id', models.CharField(blank=True, max_length=200)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
