# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-09 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0046_searchprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprocess',
            name='file',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
