# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-09 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0047_auto_20181009_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchprocess',
            name='file',
        ),
        migrations.AddField(
            model_name='searchprocess',
            name='file_path',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
