# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0048_auto_20181009_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprocess',
            name='query',
            field=models.CharField(max_length=2000),
        ),
    ]
