# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-15 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0050_nonbiodiversitylayer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonbiodiversitylayer',
            options={'ordering': ('order',)},
        ),
    ]
