# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-18 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0051_auto_20181015_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='default_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
