# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-19 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0052_nonbiodiversitylayer_default_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='iucn_redlist_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'IUCN id'),
        ),
    ]
