# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0054_auto_20181019_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('ready_for_validation', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='validation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.Validation'),
        ),
    ]
