# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [(b'bims', '0055_auto_20181102_0922'), (b'bims', '0056_auto_20181102_0923')]

    dependencies = [
        ('bims', '0054_auto_20181019_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biologicalcollectionrecord',
            options={'permissions': (('can_upload_csv', 'Can upload CSV'), ('can_upload_shapefile', 'Can upload Shapefile'), ('can_validate_data', 'Can validate data'))},
        ),
    ]
