# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0056_auto_20181101_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name='validation',
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
