# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-05 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0058_auto_20181102_0318'),
        ('bims', '0055_auto_20181102_0922_squashed_0056_auto_20181102_0923'),
    ]

    operations = [
    ]
