# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_auto_20170801_1228'),
        ('bims', '0063_locationsite_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='documents',
            field=models.ManyToManyField(to='documents.Document'),
        ),
    ]
