# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0065_auto_20181116_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
    ]
