# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0066_auto_20181122_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endemism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
