# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0067_endemism'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='endemism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Endemism', verbose_name=b'Endemism'),
        ),
    ]
