# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0069_endemism_move_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name='endemism',
        ),
    ]
