# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 13:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0072_auto_20181202_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonidentifier',
            name='vernacular_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=100), blank=True, default=[], null=True, size=None, verbose_name=b'Vernacular Names'),
        ),
    ]
