# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0073_auto_20181202_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonidentifier',
            name='description',
        ),
    ]
