# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0074_remove_taxonidentifier_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('taxon_identifiers', models.ManyToManyField(to='bims.TaxonIdentifier')),
            ],
        ),
    ]
