# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-03 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0076_auto_20181203_0919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaxonIdentifier',
            new_name='Taxonomy',
        ),
    ]
