# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0079_auto_20181203_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Taxonomy', verbose_name=b'Taxonomy'),
        ),
    ]
