# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_auto_20180414_2120'),
        ('bims', '0080_biologicalcollectionrecord_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='documents',
            field=models.ManyToManyField(blank=True, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='endemism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Endemism', verbose_name=b'Endemism'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True,
                                   verbose_name=b'Author'),
        ),
    ]
