# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0083_auto_20181204_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Taxonomy', verbose_name=b'Parent'),
        ),
    ]
