# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 01:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0084_taxongroup_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='canonical_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Canonical Name'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='scientific_name',
            field=models.CharField(max_length=200, verbose_name=b'Scientific Name'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='vernacular_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=list, max_length=200), blank=True, default=[], null=True, size=None, verbose_name=b'Vernacular Names'),
        ),
    ]
