# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 05:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0085_auto_20181206_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
