# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0085_auto_20181206_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='collection_habitat',
            field=models.CharField(blank=True, choices=[(b'euryhaline', b'Euryhaline'), (b'freshwater', b'Freshwater')], default=b'', max_length=100),
        ),
    ]
