# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0085_auto_20181205_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='category',
            field=models.CharField(blank=True, choices=[(b'SPECIES_CLASS', b'Species Class'), (b'SPECIES_MODULE', b'Species Module')], max_length=50, verbose_name=b'Taxonomic Group Category'),
        ),
    ]
