# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0086_taxongroup_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Author'),
        ),
    ]
