# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0086_biologicalcollectionrecord_additional_data'),
        ('bims', '0086_biologicalcollectionrecord_collection_habitat'),
    ]

    operations = [
    ]
