# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0087_merge_20181206_0607'),
    ]

    operations = [
    ]
