# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 09:37
from __future__ import unicode_literals

from django.db import migrations

# def update_abous_us_flatpage(apps, schema_editor):
        # FlatPage = apps.get_model('flatpages', 'FlatPage')
        # Site = apps.get_model('sites', 'Site')
        # site_id = getattr(settings, 'SITE_ID', 1)
        # current_site = Site.objects.get(pk=site_id)
        # for page_dict in FLATPAGES:
        #     new_page = FlatPage.objects.create(
        #         title=page_dict['title'],
        #         url=page_dict['url'],
        #         content=page_dict['content'])
        #   new_page.sites.add(current_site)


class Migration(migrations.Migration):
    dependencies = [
        ('bims', '0087_merge_20181206_0607'),
    ]

    operations = [
        # migrations.RunPython(update_about_us_flatpage),
    ]
