# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 13:10
from __future__ import unicode_literals

from django.db import migrations


def rename_reference_category_consulting_report(apps, schema_editor):

    my_model = apps.get_model('bims', 'biologicalcollectionrecord')

    for mm in my_model.objects.filter(reference_category='Consulting report'):
        if mm.reference_category == 'Consulting report':
            mm.reference_category = 'Report'
        mm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0087_merge_20181206_0607'),
    ]

    operations = [
        migrations.RunPython(rename_reference_category_consulting_report)
    ]
