# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0087_merge_20181206_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='legacy_site_code',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
