# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0088_auto_20181207_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprocess',
            name='category',
            field=models.CharField(choices=[(b'cluster_generation', b'Cluster Generation'), (b'search_results', b'Search Results'), (b'sites_summary', b'Site Summary')], max_length=50),
        ),
    ]
