# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0090_auto_20181220_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiverCatchment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.RiverCatchment', verbose_name=b'Parent')),
            ],
        ),
    ]
