# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-05 09:47
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion


def ensure_content_type_unique(apps, schema_editor):
    from django.db import connections
    with connections['default'].cursor() as cursor:
        cursor.execute('''select * from INFORMATION_SCHEMA.TABLE_CONSTRAINTS where CONSTRAINT_NAME=\'django_content_type_pkey\'''')
        row = cursor.fetchall()
        if len(row) == 0:
            cursor.execute('''ALTER TABLE django_content_type ADD PRIMARY KEY (id)''')


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bims', '0091_rivercatchment'),
    ]

    operations = [
        migrations.RunPython(ensure_content_type_unique),
        migrations.CreateModel(
            name='FbisUUID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
