# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 04:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0093_auto_20190107_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'Other json data'),
        ),
    ]
