
# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 09:37
from __future__ import unicode_literals

from django.db import migrations

def update_about_us_flatpage(apps, schema_editor):
    data = [
        {
            "pk": 1,
            "model": "flatpages.flatpage",
            "fields": {
                "url": "/about_us/",
                "title": "About Us",
                "content":
                    """<div style=\"text-align: center\">
                         <span><h5>FBIS is a platform for visualising and
                         sharing biodiversity information. \r\nWe strive to
                         follow open standards and work with platforms such
                         as GBIF, IUCN etc.</h3></span>
                         \r\n<hr/>\r\n
                         <span><h5>\r\nVisit a production site at
                         <a href=\"http://freshwaterbiodiversity.org\">
                         http://freshwaterbiodiversity.org</a>. </h5></span>
                         \r\n<hr/>\r\n
                         <span><h5>The project has been developed in
                         partnership with Freshwater Resarch Centre. FBIS is
                         open source software which you can freely download
                         and install in your own institution. The FBIS
                         project builds on Kartoza's BIMS platform to provide
                         freshwater biodiversity specific features.<h5><span>
                         </div>""",
                "enable_comments": "False",
                "template_name": "flatpages/about_us.html",
                "registration_required": "False",
                "sites": [1],
                "id": 1
            }
        }
    ]
    model_class = apps.get_model('flatpages', 'flatpage')
    for record in data:
        obj = model_class(**record['fields'])
        obj.pk = record['pk']
        obj.save()

class Migration(migrations.Migration):
    dependencies = [
        ('bims', '0093_auto_20190107_0256'),
    ]

    operations = [
        migrations.RunPython(update_about_us_flatpage),
    ]

