# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0001_initial'),
        ('bims', '0095_auto_20190108_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='river',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.River'),
        ),
    ]
