# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0097_auto_20190109_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbisuuid',
            name='uuid',
            field=models.CharField(max_length=50),
        ),
    ]
