# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0098_auto_20190109_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
