# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0100_auto_20190109_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxongroup',
            name='category',
            field=models.CharField(blank=True, choices=[(b'SASS_TAXON_GROUP', b'SASS Taxon Group'), (b'SPECIES_CLASS', b'Species Class'), (b'SPECIES_MODULE', b'Species Module')], max_length=50, verbose_name=b'Taxonomic Group Category'),
        ),
    ]
