
# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 09:37
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings
from django.contrib.flatpages.models import FlatPage

# Code adapted from DjangoUnleashed Migrating Flatpages

FLATPAGES = [
        {
            "title": "About",
            "url": "/about_us/",
            "content": """<div style=\"text-align: center\">
                         <span><h5>FBIS is a platform for visualising and
                         sharing biodiversity information. \r\nWe strive to
                         follow open standards and work with platforms such
                         as GBIF, IUCN etc.</h3></span>
                         \r\n<hr/>\r\n
                         <span><h5>\r\nVisit a production site at
                         <a href=\"http://freshwaterbiodiversity.org\">
                         http://freshwaterbiodiversity.org</a>. </h5></span>
                         \r\n<hr/>\r\n
                         <span><h5>The project has been developed in
                         partnership with Freshwater Resarch Centre. FBIS is
                         open source software which you can freely download
                         and install in your own institution. The FBIS
                         project builds on Kartoza's BIMS platform to provide
                         freshwater biodiversity specific features.<h5><span>
                         </div>""",
        }
    ]


def add_about_us_flatpage(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    Site = apps.get_model('sites', 'Site')
    site_id = getattr(settings, 'SITE_ID', 1)
    if Site.objects.filter(pk=site_id).exists():
        current_site = Site.objects.get(pk=site_id)
    else:
        current_site = Site.objects.create(
            pk=site_id,
            domain='test.site.com',
            name='Test Site'
        )
    if len(FlatPage.objects.all()) > 0:
        return
    for page_dict in FLATPAGES:
        new_page = FlatPage.objects.create(
            title=page_dict['title'],
            url=page_dict['url'],
            content=page_dict['content'])
        new_page.sites.add(current_site)


class Migration(migrations.Migration):
    dependencies = [
        ('flatpages', '0001_initial'),
        ('bims', '0100_auto_20190109_0645'),
    ]

    operations = [
        migrations.RunPython(
            add_about_us_flatpage,
        ),
    ]
