# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 07:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0101_auto_20190110_0533'),
        ('bims', '0101_auto_20190109_1122'),
    ]

    operations = [
    ]
