# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0103_move_sass_biotope_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SassBiotope',
            new_name='Biotope',
        ),
        migrations.AlterModelTable(
            name='biotope',
            table=None,
        ),
    ]
