# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-12 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0104_auto_20190111_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotope',
            name='biotope_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Biotope'),
        ),
    ]
