# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0105_biotope_biotope_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='category',
            field=models.CharField(blank=True, choices=[(b'alien', b'Non-native'), (b'indigenous', b'Native'), (b'translocated', b'Translocated')], max_length=50, null=True),
        ),
    ]
