# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0106_auto_20190114_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='source_collection',
            field=models.CharField(blank=True, help_text=b'e.g. SANBI', max_length=200, null=True),
        ),
    ]
