# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0107_biologicalcollectionrecord_source_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(blank=True, choices=[(b'CLASS', b'Class'), (b'CULTIVAR_GROUP', b'Cultivar Group'), (b'DOMAIN', b'Domain'), (b'FAMILY', b'Family'), (b'GENUS', b'Genus'), (b'INFRAORDER', b'Infra Order'), (b'KINGDOM', b'Kingdom'), (b'LIFE', b'Life'), (b'ORDER', b'Order'), (b'PHYLUM', b'Phylum'), (b'SPECIES', b'Species'), (b'SUBORDER', b'Sub Order'), (b'SUBSPECIES', b'Sub Species'), (b'SUPERFAMILY', b'Super Family')], max_length=50, verbose_name=b'Taxonomic Rank'),
        ),
    ]
