# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0108_auto_20190121_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biologicalcollectionrecord',
            options={'permissions': (('can_upload_csv', 'Can upload CSV'), ('can_upload_shapefile', 'Can upload Shapefile'), ('can_validate_data', 'Can validate data'), ('can_add_single_occurrence', 'Can add single Occurrence'))},
        ),
    ]
