# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-03 08:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0109_auto_20190128_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='location_context_document',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text=b'This document is generated from GeoContext by using management command or changing the geometry.', null=True, verbose_name=b'Document for location context as JSON.'),
        ),
    ]
