# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0110_searchprocess_search_raw_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprocess',
            name='category',
            field=models.CharField(choices=[(b'cluster_generation', b'Cluster Generation'), (b'search_results', b'Search Results'), (b'sites_summary', b'Site Summary'), (b'taxon_summary', b'Taxon Summary')], max_length=50),
        ),
    ]
