# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0110_searchprocess_search_raw_query'),
        ('bims', '0111_rivercatchment_location_sites'),
    ]

    operations = [
    ]
