# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0112_merge_20190206_0831'),
        ('bims', '0111_auto_20190204_1252'),
    ]

    operations = [
    ]
