# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 00:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0114_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='location_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text=b'This is intended for filtering', null=True, verbose_name=b'Formatted location_context_document'),
        ),
    ]
