# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0115_locationsite_location_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='abundance_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='biotope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Biotope'),
        ),
    ]
