# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0115_locationsite_location_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(b'input', b'Input'), (b'select', b'Select')], max_length=50)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SpatialScaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.SpatialScaleGroup', verbose_name=b'Parent')),
            ],
        ),
        migrations.AddField(
            model_name='spatialscale',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.SpatialScaleGroup'),
        ),
    ]
