# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0120_auto_20190304_0832'),
        ('bims', '0116_auto_20190226_0923'),
    ]

    operations = [
    ]
