# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0122_auto_20190305_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biologicalcollectionrecord',
            old_name='sampling_method',
            new_name='sampling_method_string',
        ),
    ]
