# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0123_auto_20190305_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='sampling_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.SamplingMethod'),
        ),
    ]
