# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models


def clear_search_process(apps, schema_editor):
    SearchProcess = (
        apps.get_model('bims', 'SearchProcess')
    )
    search_process = SearchProcess.objects.all()
    search_process.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0124_biologicalcollectionrecord_sampling_method'),
    ]

    operations = [
        migrations.RunPython(clear_search_process),
    ]
