# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 08:08
from __future__ import unicode_literals

from django.db import migrations, connection


def clear_all_postgres_view(apps, schema_editor):
    query = (
        'SELECT \'DROP VIEW "\' || table_name || \'";\''
        ' FROM information_schema.views'
        ' WHERE table_schema NOT IN (\'pg_catalog\', \'information_schema\')'
        ' AND table_name !~ \'^pg_\' AND table_name !~ \'^raster\' AND  table_name !~ \'^geo\';'
    )
    cursor = connection.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    for row in rows:
        cursor.execute(row[0])


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0125_auto_20190306_0759'),
    ]

    operations = [
        migrations.RunPython(clear_all_postgres_view)
    ]
