# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0126_auto_20190306_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='collection_habitat',
            field=models.CharField(blank=True,
                                   choices=[(b'euryhaline', b'Euryhaline'),
                                            (b'freshwater', b'Freshwater')],
                                   default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='collector',
            field=models.CharField(blank=True, default=b'', max_length=300,
                                   verbose_name=b'collector or observer'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='institution_id',
            field=models.CharField(default=b'bims',
                                   help_text=b'An identifier for the institution having custody of the object(s) or information referred to in the record.',
                                   max_length=200, verbose_name=b'Custodian'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='original_species_name',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='reference_category',
            field=models.CharField(blank=True, default=b'', max_length=200),
        ),
    ]
