# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 08:42
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0127_auto_20190306_0814'),
    ]

    operations = []
