# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-06 08:42
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def add_default_location_site_view(apps, schema_editor):
    call_command('add_default_location_site_view')


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0127_auto_20190306_0814'),
    ]

    operations = [
        migrations.RunPython(add_default_location_site_view)
    ]
