# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0128_auto_20190306_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='legacy_site_code',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='iucnstatus',
            name=b'category',
            field=models.CharField(blank=True, choices=[(b'LC', b'Least concern'), (b'NT', b'Near threatened'), (b'VU', b'Vulnerable'), (b'EN', b'Endangered'), (b'CR', b'Critically endangered'), (b'EW', b'Extinct in the wild'), (b'EX', b'Extinct'), (b'DD', b'Data deficient'), (b'NE', b'Not evaluated')], default=b'', max_length=50),
        ),
    ]
