# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0129_auto_20190404_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=b'module_logo'),
        ),
    ]
