# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0131_auto_20190404_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxongroup',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, null=True, to='bims.Taxonomy'),
        ),
    ]
