# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0132_auto_20190404_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotope',
            name='taxon_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.TaxonGroup'),
        ),
    ]
