# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0133_biotope_taxon_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='source_collection',
            field=models.CharField(blank=True, help_text=b'Additional filter for search collections', max_length=200, null=True),
        ),
    ]
