# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0134_taxongroup_source_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fbis_username',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='sass_accredited',
            field=models.BooleanField(default=False, verbose_name=b'SASS Accredited'),
        ),
    ]
