# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0135_auto_20190506_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'site_images')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.LocationSite')),
            ],
        ),
    ]
