# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-13 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0136_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sass_accredited_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
