# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0137_profile_sass_accredited_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='refined_geomorphological',
            field=models.CharField(blank=True, help_text=b'Would be used in preference to the one discovered in geocontext', max_length=200, null=True),
        ),
    ]
