# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-20 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0138_locationsite_refined_geomorphological'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsite',
            name='boundary',
        ),
    ]
