# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-22 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0140_spatialscale_from_geocontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='original_geomorphological',
            field=models.CharField(blank=True, help_text=b'Original geomorphological zone from spatial layer', max_length=200, null=True),
        ),
    ]
