# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-29 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0141_locationsite_original_geomorphological'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sass_accredited_time',
            new_name='sass_accredited_date_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sass_accredited',
        ),
        migrations.AddField(
            model_name='profile',
            name='sass_accredited_date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
