# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-14 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0142_auto_20190529_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='latitude',
            field=models.FloatField(blank=True, help_text=b'Latitude of location site', null=True),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='longitude',
            field=models.FloatField(blank=True, help_text=b'Longitude of location site', null=True),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='refined_geomorphological',
            field=models.CharField(blank=True, choices=[(b'LOWER_FOOTHILL', b'Lower foothill'), (b'LOWLAND_RIVER', b'Lowland river'), (b'MOUNTAIN_HEADWATER_STREAM', b'Mountain headwater stream'), (b'MOUNTAIN_STREAM', b'Mountain stream'), (b'REJUVENATED_FOOTHILL', b'Rejunevated foothill'), (b'REJUVENATED_BEDROCK_FALL_CASCADES', b'Rejuvenated bedrock fall / cascades'), (b'SOURCE_ZONE', b'Source Zone'), (b'TRANSITIONAL', b'Transitional'), (b'UPLAND_FLOODPLAIN', b'Upland floodplain'), (b'UPPER_FOOTHILL', b'Upper foothill')], help_text=b'Would be used in preference to the one discovered in geocontext', max_length=200, null=True),
        ),
    ]
