# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-14 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0143_auto_20190614_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='refined_geomorphological',
            field=models.CharField(blank=True, choices=[(b'LOWER_FOOTHILL', b'Lower foothill'), (b'LOWLAND_RIVER', b'Lowland river'), (b'MOUNTAIN_HEADWATER_STREAM', b'Mountain headwater stream'), (b'MOUNTAIN_STREAM', b'Mountain stream'), (b'REJUVENATED_FOOTHILL', b'Rejunevated foothill'), (b'REJUVENATED_BEDROCK_FALL_CASCADES', b'Rejuvenated bedrock fall / cascades'), (b'SOURCE_ZONE', b'Source zone'), (b'TRANSITIONAL', b'Transitional'), (b'UPLAND_FLOODPLAIN', b'Upland floodplain'), (b'UPPER_FOOTHILL', b'Upper foothill')], help_text=b'Would be used in preference to the one discovered in geocontext', max_length=200, null=True),
        ),
    ]
