# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-17 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0144_auto_20190614_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='refined_geomorphological',
            field=models.CharField(blank=True, choices=[(b'LOWER_FOOTHILL', b'LOWER_FOOTHILL'), (b'LOWLAND_RIVER', b'LOWLAND_RIVER'), (b'MOUNTAIN_HEADWATER_STREAM', b'MOUNTAIN_HEADWATER_STREAM'), (b'MOUNTAIN_STREAM', b'MOUNTAIN_STREAM'), (b'REJUVENATED_FOOTHILL', b'REJUVENATED_FOOTHILL'), (b'REJUVENATED_BEDROCK_FALL_CASCADES', b'REJUVENATED_BEDROCK_FALL_CASCADES'), (b'SOURCE_ZONE', b'SOURCE_ZONE'), (b'TRANSITIONAL', b'TRANSITIONAL'), (b'UPLAND_FLOODPLAIN', b'UPLAND_FLOODPLAIN'), (b'UPPER_FOOTHILL', b'UPPER_FOOTHILL')], help_text=b'Would be used in preference to the one discovered in geocontext', max_length=200, null=True),
        ),
    ]
