# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0145_auto_20190617_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='refined_geomorphological',
            field=models.CharField(blank=True, choices=[(b'Lower foothill', b'Lower foothill'), (b'Lowland river', b'Lowland river'), (b'Mountain headwater stream', b'Mountain headwater stream'), (b'Mountain stream', b'Mountain stream'), (b'Rejunevated foothill', b'Rejunevated foothill'), (b'Rejuvenated bedrock fall / cascades', b'Rejuvenated bedrock fall / cascades'), (b'Source zone', b'Source zone'), (b'Transitional', b'Transitional'), (b'Upland floodplain', b'Upland floodplain'), (b'Upper foothill', b'Upper foothill')], help_text=b'Would be used in preference to the one discovered in geocontext', max_length=200, null=True),
        ),
    ]
