# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0146_auto_20190617_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='category',
            field=models.CharField(blank=True, choices=[(b'alien', b'Alien'), (b'indigenous', b'Native'), (b'translocated', b'Extralimital')], max_length=50, null=True),
        ),
    ]
