# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0149_auto_20190702_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='uuid',
            field=models.UUIDField(blank=True, help_text=b'Collection record uuid', null=True),
        ),
    ]
