# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('bims', '0150_auto_20190703_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('site_notice', models.TextField(blank=True, null=True)),
            ],
            bases=('preferences.preferences',),
        ),
    ]
