# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-18 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0151_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[(b'water_resource_manager', b'Water Resource Manager'), (b'researcher', b'Researcher'), (b'consultant', b'Consultant'), (b'conservation_planner', b'Conservation Planner'), (b'citizen', b'Citizen')], max_length=100, null=True),
        ),
    ]
