# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-07 07:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0152_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='map_default_filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], help_text=b'Which filters are selected by default, the format must be as follows : [{"filter_model": "data_source", "filter_value": "bims"},]'),
        ),
    ]
