# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-08 01:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0153_sitesetting_map_default_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='default_location_site_cluster',
            field=models.CharField(default=b'default_location_site_cluster', help_text=b'SQL view name of the location site cluster which used on the map', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='map_default_filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], help_text=b'Which filters are selected by default, the format must be as follows : [{"filter_key": "sourceCollection", "filter_values": ["bims"]}]'),
        ),
    ]
