# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-12 04:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0154_auto_20190808_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='collector_user',
            field=models.ForeignKey(blank=True, help_text=b'The user object of the actual capturer/collector of this data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biologicalcollectionrecord_collector_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='collector',
            field=models.CharField(blank=True, default=b'', help_text=b'Collector name in string value, this is useful for collector values from GBIF and other third party sources', max_length=300, verbose_name=b'collector or observer'),
        ),
    ]
