# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-19 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0155_auto_20190812_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='owner',
            field=models.ForeignKey(blank=True, help_text=b'The owner of the site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='creator',
            field=models.ForeignKey(blank=True, help_text=b'The creator of the site', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
