# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0157_auto_20190820_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='source_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.SourceReference'),
        ),
    ]
