# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0159_bimsdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rivercatchment',
            name='location_sites',
            field=models.ManyToManyField(blank=True, related_name='location_sites', to='bims.LocationSite'),
        ),
        migrations.AlterField(
            model_name='taxongroup',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, to='bims.Taxonomy'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='vernacular_names',
            field=models.ManyToManyField(blank=True, to='bims.VernacularName'),
        ),
    ]
