# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-09 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0170_migrate_source_reference_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='default_data_source',
            field=models.CharField(blank=True, help_text=b'Default data source when adding new collection', max_length=100, null=True),
        ),
    ]
