# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-13 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0172_auto_20190912_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='abundance_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
