# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_biologicalcollectionrecord_charfield(apps, schema_editor):
    BiologicalCollectionRecord = apps.get_model('bims', 'BiologicalCollectionRecord')
    bio = BiologicalCollectionRecord.objects.filter(category__isnull=True)
    bio.update(category='')

    bio = BiologicalCollectionRecord.objects.filter(source_collection__isnull=True)
    bio.update(source_collection='')

    bio = BiologicalCollectionRecord.objects.filter(upstream_id__isnull=True)
    bio.update(upstream_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0177_auto_20190913_0909'),
    ]

    operations = [
        migrations.RunPython(migrate_biologicalcollectionrecord_charfield),
    ]
