# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0178_auto_20190917_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='category',
            field=models.CharField(blank=True, choices=[(b'alien', b'Non-Native'), (b'indigenous', b'Native')], default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='source_collection',
            field=models.CharField(blank=True, default=b'', help_text=b'e.g. SANBI', max_length=200),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='upstream_id',
            field=models.CharField(blank=True, default=b'', help_text=b'Upstream id, e.g. Gbif key', max_length=200),
        ),
    ]
