# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0178_sitesetting_default_team_name'),
        ('bims', '0179_auto_20190918_1451'),
    ]

    operations = [
    ]
