# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_auto_20180414_2120'),
        ('bims', '0180_merge_20190919_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcereferencebibliography',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Document'),
        ),
        migrations.AddField(
            model_name='sourcereferencedatabase',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='uuid',
            field=models.CharField(blank=True, help_text=b'Collection record uuid', max_length=200, null=True),
        ),
    ]
