# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0181_auto_20190923_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcereferencebibliography',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='td_biblio.Entry'),
        ),
    ]
