# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-24 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0182_auto_20190923_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=b'', max_length=100)),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('value', models.CharField(blank=True, default=b'', max_length=255)),
                ('group_key', models.CharField(blank=True, default=b'', max_length=255)),
                ('fetch_time', models.DateTimeField(default=datetime.datetime(2019, 9, 24, 6, 28, 37, 73548, tzinfo=utc))),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.LocationSite')),
            ],
        ),
        migrations.AddField(
            model_name='spatialscalegroup',
            name='type',
            field=models.CharField(blank=True, choices=[(b'input', b'Input'), (b'select', b'Select')], max_length=50, null=True),
        ),
    ]
