# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0183_auto_20190924_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcontext',
            name='fetch_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
