# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0184_auto_20191002_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='module_group',
            field=models.ForeignKey(blank=True, help_text=b'Which module this collection belong to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.TaxonGroup'),
        ),
    ]
