# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0185_biologicalcollectionrecord_module_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotope',
            name='biotope_type',
            field=models.CharField(blank=True, choices=[(b'broad', b'Broad'), (b'specific', b'Specific'), (b'substratum', b'Substratum')], max_length=10),
        ),
    ]
