# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-08 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0186_biotope_biotope_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biotope',
            name='taxon_group',
        ),
        migrations.AddField(
            model_name='biotope',
            name='taxon_group',
            field=models.ManyToManyField(blank=True, null=True, to='bims.TaxonGroup'),
        ),
    ]
