# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0189_samplingmethod_taxon_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='legacy_river_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
