# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0190_locationsite_legacy_river_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingmethod',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
