# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0191_samplingmethod_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalrecord',
            name='chem',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
