# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0049_auto_20191021_0925'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Chem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('chem_code', models.CharField(max_length=100)),
                ('chem_description',
                 models.CharField(blank=True, max_length=200, null=True)),
                ('chem_unit', models.CharField(blank=True,
                                               choices=[(b'PERCENT', b'%'),
                                                        (b'NTU', b'NTU'), (
                                                        b'PER_100_ML',
                                                        b'Per 100ml'),
                                                        (b'M', b'm'),
                                                        (b'MS_M', b'mS/m'),
                                                        (b'MEQ_L', b'meq/l'),
                                                        (b'MG_L', b'mg/l'),
                                                        (b'OC', b'oC'), (
                                                        b'PH_UNIT',
                                                        b'pH unit')],
                                               max_length=200, null=True)),
                ('decimal_place', models.IntegerField(blank=True, null=True)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chemistry record',
                'verbose_name_plural': 'Chemistry records',
                'db_table': 'bims_chem'
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
