# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0192_auto_20191021_0924'),
        ('bims', '0193_chem'),
    ]

    operations = [
    ]
