# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0194_merge_20191021_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalrecord',
            name='chem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_collection_record', to='bims.Chem'),
        ),
        migrations.AlterModelTable(
            name='chem',
            table=None,
        ),
    ]
