# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0197_auto_20191028_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationContextFilterGroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_display_order', models.IntegerField()),
            ],
            options={
                'ordering': ['filter__display_order', 'group_display_order'],
            },
        ),
        migrations.RemoveField(
            model_name='locationcontextgrouporder',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='locationcontextgrouporder',
            name='group',
        ),
        migrations.AlterField(
            model_name='locationcontextfilter',
            name='location_context_groups',
            field=models.ManyToManyField(through='bims.LocationContextFilterGroupOrder', to='bims.LocationContextGroup'),
        ),
        migrations.DeleteModel(
            name='LocationContextGroupOrder',
        ),
        migrations.AddField(
            model_name='locationcontextfiltergrouporder',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.LocationContextFilter'),
        ),
        migrations.AddField(
            model_name='locationcontextfiltergrouporder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.LocationContextGroup'),
        ),
    ]
