# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-28 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0199_auto_20191028_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcontext',
            name='group_key',
        ),
        migrations.RemoveField(
            model_name='locationcontext',
            name='key',
        ),
        migrations.RemoveField(
            model_name='locationcontext',
            name='name',
        ),
    ]
