# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0200_auto_20191028_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='spatial_filter_layer_style',
            field=models.CharField(blank=True, default=b'red_outline', help_text=b'Style name for spatial filter layer', max_length=100),
        ),
    ]
