# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0201_sitesetting_spatial_filter_layer_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='github_feedback_repo',
            field=models.CharField(blank=True, default=b'', help_text=b'Github repo for users`s feedback', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='github_feedback_token',
            field=models.CharField(blank=True, default=b'', help_text=b'Access token for Github feedback repo', max_length=100),
        ),
    ]
