# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-01 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sass', '0053_sitevisit_embeddedness'),
        ('bims', '0201_sitesetting_spatial_filter_layer_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='site_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sass.SiteVisit'),
        ),
    ]
