# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0202_siteimage_site_visit'),
        ('bims', '0202_auto_20191104_0340'),
    ]

    operations = [
    ]
