# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-05 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0203_merge_20191105_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
