# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-06 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0204_taxongroup_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name=b'absent',
        ),
    ]
