# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-11 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0205_remove_biologicalcollectionrecord_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxon',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name='endemism',
        ),
        migrations.RemoveField(
            model_name='taxon',
            name=b'iucn_status',
        ),
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'verbose_name': 'Taxonomy', 'verbose_name_plural': 'Taxa'},
        ),
        migrations.DeleteModel(
            name='Taxon',
        ),
    ]
