# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0206_auto_20191111_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='geocontext_keys',
            field=models.CharField(blank=True, default=b'political_boundary_group,rainfall_group', help_text=b'Default location context group keys that will be fetched from Geocontext, separated by commas.', max_length=300),
        ),
        migrations.AlterField(
            model_name='chem',
            name='chem_unit',
            field=models.CharField(blank=True, choices=[(b'PERCENT', b'%'), (b'NTU', b'NTU'), (b'PER_100_ML', b'Per 100ml'), (b'OC', b'deg C'), (b'M', b'm'), (b'MS_M', b'mS/m'), (b'MEQ_L', b'meq/l'), (b'MG_L', b'mg/l'), (b'PH_UNIT', b'pH unit')], max_length=200, null=True),
        ),
    ]
