# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0208_auto_20191202_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalrecord',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_collection_record', to='bims.Survey'),
        ),
        migrations.AlterField(
            model_name='chemicalrecord',
            name='location_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chemical_collection_record', to='bims.LocationSite'),
        ),
    ]
