# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0209_auto_20191202_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
