# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-02 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0210_auto_20191202_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biological_collection_record', to='bims.Survey'),
        ),
    ]
