# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-04 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0211_biologicalcollectionrecord_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDataOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('survey_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.SurveyData')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyDataValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.Survey')),
                ('survey_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.SurveyData')),
                ('survey_data_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.SurveyDataOption')),
            ],
        ),
    ]
