# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 04:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0214_load_survey_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='gbif_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
