# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-25 07:21
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0215_taxonomy_gbif_data'),
    ]

    operations = [
    ]
