# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-01 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0218_chem_show_in_abiotic_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chem',
            name='chem_unit',
            field=models.CharField(blank=True, choices=[(b'PERCENT', b'%'), (b'APHA_UNITS', b'APHA units'), (b'NTU', b'NTU'), (b'PER_100_ML', b'Per 100ml'), (b'OC', b'degrees C'), (b'M', b'm'), (b'MS_M', b'mS/m'), (b'MEQ_L', b'meq/l'), (b'MG_L', b'mg/l'), (b'MG_L_5_DAYS', b'mg/l (5 days)'), (b'MG_S', b'mg/s'), (b'PH_UNIT', b'pH unit'), (b'PH_UNITS', b'pH units')], max_length=200, null=True),
        ),
    ]
