# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 09:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0219_auto_20200301_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'Additional json data'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='gbif_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name=b'Json data from gbif'),
        ),
    ]
