# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 10:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0220_auto_20200303_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text=b'The person that did the analysis', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biologicalcollectionrecord_analyst', to=settings.AUTH_USER_MODEL),
        ),
    ]
