# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0223_algaedata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algaedata',
            options={'verbose_name': 'Algae data', 'verbose_name_plural': 'Algae data'},
        ),
        migrations.AddField(
            model_name='survey',
            name='embeddedness',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
    ]
