# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0224_auto_20200304_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algaedata',
            old_name='indicator_asdm',
            new_name='indicator_afdm',
        ),
        migrations.RemoveField(
            model_name='algaedata',
            name='asdm',
        ),
        migrations.RemoveField(
            model_name='algaedata',
            name='chl_a',
        ),
    ]
