# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0226_auto_20200305_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algaedata',
            name='biological_collection_record',
        ),
        migrations.AddField(
            model_name='algaedata',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algae_data', to='bims.Survey'),
        ),
    ]
