# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0227_auto_20200305_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='embeddedness',
        ),
    ]
