# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0228_remove_survey_embeddedness'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='get_feature_format',
            field=models.TextField(default=b'text/plain', max_length=100),
        ),
    ]
