# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-30 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0230_sourcereference_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='legacy_canonical_name',
            field=models.CharField(blank=True, default=b'', max_length=255, verbose_name=b'Legacy Canonical Name'),
        ),
    ]
