# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0231_taxonomy_legacy_canonical_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomy',
            name='documents',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='verified',
            field=models.BooleanField(default=False, help_text=b'The data has been verified'),
        ),
    ]
