# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-31 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0232_auto_20200331_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='import_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
