# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-09 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0233_taxonomy_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='category',
            field=models.CharField(blank=True, choices=[(b'alien', b'Non-Native'), (b'indigenous', b'Native')], default=b'', help_text=b'Origin', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxongroup',
            name='category',
            field=models.CharField(blank=True, choices=[(b'DIVISION_GROUP', b'Division Group'), (b'SASS_TAXON_GROUP', b'SASS Taxon Group'), (b'SPECIES_CLASS', b'Species Class'), (b'SPECIES_MODULE', b'Species Module')], max_length=50, verbose_name=b'Taxonomic Group Category'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='legacy_canonical_name',
            field=models.CharField(blank=True, default=b'', max_length=500, verbose_name=b'Legacy Canonical Name'),
        ),
    ]
