# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0234_auto_20200409_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='legacy_canonical_name',
            field=models.CharField(blank=True, default=b'', max_length=700, verbose_name=b'Legacy Canonical Name'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(blank=True, choices=[(b'CLASS', b'Class'), (b'CULTIVAR_GROUP', b'Cultivar Group'), (b'DOMAIN', b'Domain'), (b'FAMILY', b'Family'), (b'GENUS', b'Genus'), (b'INFRAORDER', b'Infra Order'), (b'KINGDOM', b'Kingdom'), (b'LIFE', b'Life'), (b'ORDER', b'Order'), (b'PHYLUM', b'Phylum'), (b'SPECIES', b'Species'), (b'SUBFAMILY', b'Sub Family'), (b'SUBORDER', b'Sub Order'), (b'SUBSPECIES', b'Sub Species'), (b'SUPERFAMILY', b'Super Family')], max_length=50, verbose_name=b'Taxonomic Rank'),
        ),
    ]
