# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0235_auto_20200417_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='origin',
            field=models.CharField(blank=True, choices=[(b'alien', b'Non-Native'), (b'indigenous', b'Native')], default=b'', help_text=b'Origin', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(blank=True, choices=[(b'CLASS', b'Class'), (b'CULTIVAR_GROUP', b'Cultivar Group'), (b'DOMAIN', b'Domain'), (b'FAMILY', b'Family'), (b'GENUS', b'Genus'), (b'INFRAORDER', b'Infra Order'), (b'KINGDOM', b'Kingdom'), (b'LIFE', b'Life'), (b'ORDER', b'Order'), (b'PHYLUM', b'Phylum'), (b'SPECIES', b'Species'), (b'SUBCLASS', b'Sub Class'), (b'SUBFAMILY', b'Sub Family'), (b'SUBORDER', b'Sub Order'), (b'SUBSPECIES', b'Sub Species'), (b'SUPERFAMILY', b'Super Family')], max_length=50, verbose_name=b'Taxonomic Rank'),
        ),
    ]
