# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0236_auto_20200428_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='disclaimer_doc_text',
            field=models.CharField(blank=True, default=b'I hereby confirm that I am the owner of these data and/or document and agree to these being shared via the FBIS platform for download by registered FBIS users.', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='disclaimer_form_text',
            field=models.CharField(blank=True, default=b'I agree to these data being shared via the FBIS platform for visualisation and download by registered FBIS users', max_length=300),
        ),
    ]
