# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-13 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0238_locationcontextgroup_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='default_basemap',
            field=models.CharField(default=b'Terrain', help_text=b'The default basemap layer that is displayed on the map', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_center_map',
            field=models.CharField(default=b'22.948492328125,-31.12543669218031', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_extent_map',
            field=models.CharField(default=b'-37.72038269917067,5.207535937500003,47.3950359375,-18.54426493227018', max_length=100),
        ),
    ]
