# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-13 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0239_auto_20200513_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='default_extent_map',
            field=models.CharField(default=b'5.207535937500003,-37.72038269917067,47.3950359375,-18.54426493227018', max_length=100),
        ),
    ]
