# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-08 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0240_auto_20200513_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimsdocument',
            name='authors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='abundance_type',
            field=models.CharField(blank=True, choices=[(b'number', b'Number'), (b'percentage', b'Percentage'), (b'density', b'Density'), (b'species_valve_per_frustule_count', b'Species valve/frustule count'), (b'density_cells_per_m2', b'Density (cells/m2)'), (b'density_cells_per_mL', b'Density (cells/mL)')], default=b'number', max_length=50),
        ),
    ]
