# Generated by Django 2.2.12 on 2020-05-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0241_auto_20200519_0407'),
    ]

    operations = [
    ]
