# Generated by Django 2.2.12 on 2020-05-20 05:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0242_auto_20200519_0946'),
    ]

    operations = [
    ]
