# Generated by Django 2.2.12 on 2020-05-20 05:00

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0243_blogpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bimsdocument',
            name='authors',
            field=models.ManyToManyField(blank=True,
                                         to=settings.AUTH_USER_MODEL),
        ),
    ]
