# Generated by Django 2.2.12 on 2020-06-19 06:18

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0244_bimsdocument_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Survey'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='abundance_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('percentage', 'Percentage'), ('density', 'Density'), ('species_valve_per_frustule_count', 'Species valve/frustule count'), ('density_cells_per_m2', 'Density (cells/m2)'), ('density_cells_per_mL', 'Density (cells/mL)')], default='number', max_length=50),
        ),
        migrations.AlterField(
            model_name='biotope',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
