# Generated by Django 2.2.12 on 2020-06-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0241_auto_20200608_0801'),
        ('bims', '0245_auto_20200619_0618'),
    ]

    operations = [
    ]
