# Generated by Django 2.2.12 on 2020-07-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0245_auto_20200619_0618'),
        ('bims', '0241_auto_20200608_0801'),
    ]

    operations = [
    ]
