# Generated by Django 2.2.12 on 2020-06-30 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0246_merge_20200630_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='abundance_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('percentage', 'Percentage'), ('density', 'Density'), ('species_valve_per_frustule_count', 'Species valve/frustule count'), ('density_cells_per_m2', 'Density (cells/m2)'), ('density_cells_per_mL', 'Density (cells/mL)')], default='number', max_length=50),
        ),
        migrations.CreateModel(
            name='TaxaUploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('uploaded_at', models.DateField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('error_notes', models.TextField(blank=True, null=True)),
                ('success_file', models.FileField(null=True, upload_to='taxa-file/')),
                ('error_file', models.FileField(null=True, upload_to='taxa-file/')),
                ('updated_file', models.FileField(null=True, upload_to='taxa-file/')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taxa Upload Session',
                'verbose_name_plural': 'Taxa Upload Sessions',
            },
        ),
    ]
