# Generated by Django 2.2.12 on 2020-07-09 02:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0247_auto_20200701_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(blank=True, choices=[('taxa', 'Taxa'), ('collections', 'Collections')], default='', max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('error_notes', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, default='', max_length=200)),
                ('process_file', models.FileField(null=True, upload_to='taxa-file/')),
                ('success_file', models.FileField(blank=True, null=True, upload_to='taxa-file/')),
                ('error_file', models.FileField(blank=True, null=True, upload_to='taxa-file/')),
                ('updated_file', models.FileField(blank=True, null=True, upload_to='taxa-file/')),
                ('module_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.TaxonGroup')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_session_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taxa Upload Session',
                'verbose_name_plural': 'Taxa Upload Sessions',
            },
        ),
        migrations.DeleteModel(
            name='TaxaUploadSession',
        ),
    ]
