# Generated by Django 2.2.12 on 2020-07-13 08:55

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0248_auto_20200709_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadsession',
            options={'verbose_name': 'Upload Session', 'verbose_name_plural': 'Upload Sessions'},
        ),
        migrations.CreateModel(
            name='DashboardConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('additional_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('module_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bims.TaxonGroup')),
            ],
            options={
                'verbose_name': 'Dashboard Configuration',
                'verbose_name_plural': 'Dashboard Configurations',
            },
        ),
    ]
