# Generated by Django 2.2.12 on 2020-06-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0248_auto_20200630_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxauploadsession',
            name='module_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.TaxonGroup'),
        ),
        migrations.AlterField(
            model_name='taxauploadsession',
            name='error_file',
            field=models.FileField(blank=True, null=True, upload_to='taxa-file/'),
        ),
        migrations.AlterField(
            model_name='taxauploadsession',
            name='progress',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxauploadsession',
            name='success_file',
            field=models.FileField(blank=True, null=True, upload_to='taxa-file/'),
        ),
        migrations.AlterField(
            model_name='taxauploadsession',
            name='updated_file',
            field=models.FileField(blank=True, null=True, upload_to='taxa-file/'),
        ),
    ]
