# Generated by Django 2.2.12 on 2020-06-30 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0249_auto_20200630_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxauploadsession',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
