# Generated by Django 2.2.12 on 2020-06-30 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0250_auto_20200630_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxauploadsession',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
