# Generated by Django 2.2.12 on 2020-07-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0250_auto_20200716_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
