# Generated by Django 2.2.12 on 2020-08-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0251_uploadsession_canceled'),
    ]

    operations = [
    ]
