# Generated by Django 2.2.12 on 2020-08-07 10:26

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0252_auto_20200807_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpage',
            name='body',
            field=wagtailmarkdown.fields.MarkdownField(),
        ),
    ]
