# Generated by Django 2.2.12 on 2020-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0253_auto_20200811_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestsession',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
