# Generated by Django 2.2.12 on 2020-08-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0254_harvestsession_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcontextfiltergrouporder',
            name='show_in_dashboard',
            field=models.BooleanField(default=False, help_text='Show this location context group in dashboard'),
        ),
    ]
