# Generated by Django 2.2.12 on 2020-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0255_locationcontextfiltergrouporder_show_in_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='default_team_name',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_site_name',
            field=models.CharField(blank=True, help_text='Default site name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='geocontext_keys',
            field=models.TextField(blank=True, default='political_boundary_group,rainfall_group', help_text='Default location context group keys that will be fetched from Geocontext, separated by commas.'),
        ),
    ]
