# Generated by Django 2.2.12 on 2020-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0255_auto_20200826_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('main_accent_color', models.CharField(default='#18A090', max_length=30)),
                ('secondary_accent_color', models.CharField(default='#DBAF00', max_length=30)),
                ('main_button_text_color', models.CharField(default='#fff', max_length=30)),
                ('navbar_background_color', models.CharField(default='#343a40', max_length=30)),
                ('navbar_text_color', models.CharField(default='#fff', max_length=30)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Custom Themes',
                'ordering': ('date',),
            },
        ),
    ]
