# Generated by Django 2.2.12 on 2020-09-02 06:16

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0256_customtheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtheme',
            name='main_accent_color',
            field=colorfield.fields.ColorField(default='#18A090', max_length=18),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='main_button_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='navbar_background_color',
            field=colorfield.fields.ColorField(default='#343a40', max_length=18),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='navbar_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='secondary_accent_color',
            field=colorfield.fields.ColorField(default='#DBAF00', max_length=18),
        ),
    ]
