# Generated by Django 2.2.12 on 2020-09-03 05:33

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bims', '0258_auto_20200903_0419'), ('bims', '0259_auto_20200903_0424'), ('bims', '0260_auto_20200903_0447'), ('bims', '0261_auto_20200903_0502'), ('bims', '0262_auto_20200903_0528')]

    dependencies = [
        ('bims', '0257_auto_20200902_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='carousels',
            field=models.ManyToManyField(blank=True, help_text='Carousels that will appear on the landing page', null=True, to='bims.CarouselHeader'),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='description',
            field=models.TextField(blank=True, help_text='Will not appear anywhere', null=True),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='name',
            field=models.CharField(help_text='Will not appear anywhere', max_length=100),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title',
            field=models.TextField(blank=True, default='', help_text='Title of the carousel'),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Paragraph inside carousel', verbose_name='Paragraph'),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Color of the text inside carousel', max_length=18),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='site_name',
            field=models.CharField(blank=True, default='', help_text='The name of the site', max_length=100),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='background_overlay_opacity',
            field=models.PositiveIntegerField(default=0, help_text='Opacity of the background overlay, in percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='background_color_overlay',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color overlay behind the text', max_length=18),
        ),
    ]
