# Generated by Django 2.2.12 on 2020-09-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0258_auto_20200903_0419_squashed_0262_auto_20200903_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtheme',
            name='carousels',
        ),
        migrations.DeleteModel(
            name='CarouselHeader',
        ),
        migrations.DeleteModel(
            name='CustomTheme',
        ),
    ]
