# Generated by Django 2.2.12 on 2020-09-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0259_auto_20200903_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcontextgroup',
            name='layer_identifier',
            field=models.CharField(blank=True, default='', help_text='Identifier to retrieve the desired value (for border)', max_length=255),
        ),
        migrations.AddField(
            model_name='locationcontextgroup',
            name='wms_format',
            field=models.CharField(blank=True, default='image/png', help_text='WMS format of the layer (for border)', max_length=255),
        ),
        migrations.AddField(
            model_name='locationcontextgroup',
            name='wms_url',
            field=models.CharField(blank=True, default='', help_text='WMS URL of the layer (for border)', max_length=255),
        ),
        migrations.AlterField(
            model_name='locationcontextgroup',
            name='layer_name',
            field=models.CharField(blank=True, default='', help_text='Name of the layer (for border)', max_length=255),
        ),
    ]
