# Generated by Django 2.2.12 on 2020-09-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0260_auto_20200909_0305'),
    ]

    operations = [
    ]
