# Generated by Django 2.2.12 on 2020-10-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0261_contentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chem',
            name='chem_unit',
            field=models.CharField(blank=True, choices=[('MEQ_L', 'meq/l'), ('PERCENT', '%'), ('PH_UNIT', 'pH unit'), ('PH_UNITS', 'pH units'), ('NTU', 'NTU'), ('MS_M', 'mS/m'), ('MG_L', 'mg/l'), ('MG_L_5_DAYS', 'mg/l (5 days)'), ('PER_100_ML', 'Per 100ml'), ('M', 'm'), ('OC', 'degrees C'), ('APHA_UNITS', 'APHA units'), ('MG_S', 'mg/s'), ('MG_M2', 'mg/m2'), ('M_S', 'm/s')], max_length=200, null=True),
        ),
    ]
