# Generated by Django 2.2.12 on 2020-10-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0263_sitesetting_site_code_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='base_country',
            field=models.CharField(blank=True, default='', help_text='Base country for the site', max_length=100),
        ),
    ]
