# Generated by Django 2.2.12 on 2020-10-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0264_sitesetting_base_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='base_country',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='base_country_code',
            field=models.CharField(blank=True, default='', help_text='Base country code for the site, using ISO 3166-1 (See here for the list : https://wiki.openstreetmap.org/wiki/Nominatim/Country_Codes)', max_length=100),
        ),
    ]
