# Generated by Django 2.2.12 on 2020-10-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0264_sitesetting_show_third_party_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_sass',
            field=models.BooleanField(default=False, help_text='Enable or disable SASS'),
        ),
    ]
