# Generated by Django 2.2.12 on 2020-11-03 08:22

import bims.models.download_request
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0265_sitesetting_enable_sass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxongroup',
            options={'ordering': ('display_order',)},
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(default=datetime.datetime.now)),
                ('request_file', models.FileField(help_text='Only csv file', null=True, upload_to='request-files/', validators=[bims.models.download_request.validate_file_extension])),
                ('processing', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('request_category', models.CharField(default='', max_length=256)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_request_requester', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download request',
                'verbose_name_plural': 'Download requests',
            },
        ),
    ]
