# Generated by Django 2.2.12 on 2020-11-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0266_auto_20201103_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadrequest',
            options={'ordering': ('-request_date',), 'verbose_name': 'Download request', 'verbose_name_plural': 'Download requests'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enable_download_request_approval',
            field=models.BooleanField(default=False, help_text='Download requests must be approved by the staff before they are sent to users'),
        ),
    ]
