# Generated by Django 2.2.12 on 2020-11-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0267_auto_20201104_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='rejection_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
