# Generated by Django 2.2.12 on 2020-11-04 05:44

import bims.models.download_request
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0268_auto_20201104_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_file',
            field=models.FileField(help_text='Only csv file', max_length=300, null=True, upload_to='request-files/', validators=[bims.models.download_request.validate_file_extension]),
        ),
    ]
