# Generated by Django 2.2.12 on 2020-11-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0269_auto_20201104_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_code_generator',
            field=models.CharField(blank=True, choices=[('bims', 'BIMS (2 Site Name + 2 Site Description + Site count)'), ('fbis', 'FBIS (2 Secondary catchment + 4 River + Site count)'), ('rbis', 'RBIS (Catchment + Province ID + District ID + Site count)')], default='bims', help_text='How site code generated', max_length=50),
        ),
    ]
