# Generated by Django 2.2.12 on 2020-11-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0270_auto_20201112_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='show_module_summary_on_dashboard',
            field=models.BooleanField(default=False, help_text='Show summative figure for data by taxon group'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_summary_data_on_dashboard',
            field=models.BooleanField(default=True, help_text='Show summary data on the dashboard (Total Location Sites, Collection Records, Site Visits)'),
        ),
    ]
