# Generated by Django 2.2.12 on 2020-11-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0271_auto_20201112_0409'),
    ]

    operations = [
    ]
