# Generated by Django 2.2.12 on 2020-11-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0272_blogpage_intro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('water_resource_manager', 'Water Resource Manager'), ('researcher', 'Researcher'), ('consultant', 'Consultant'), ('conservation_planner', 'Conservation Planner'), ('citizen', 'Citizen'), ('national_park_management', 'National Park management'), ('district_environmental_officer', 'District Environmental Officer'), ('government_staff', 'Government staff'), ('academic_staff', 'Academic staff'), ('policy_maker', 'Policy maker')], max_length=100, null=True),
        ),
    ]
