# Generated by Django 2.2.12 on 2020-11-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0273_auto_20201119_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_remove_all_occurrences_tool',
            field=models.BooleanField(default=False, help_text='Enable tool to remove all occurrences for a taxon group'),
        ),
    ]
