# Generated by Django 2.2.12 on 2020-12-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0276_sitesetting_readme_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='occurrence_upload_template',
            field=models.FileField(blank=True, help_text='File template for occurrence uploader', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='taxonomic_upload_template',
            field=models.FileField(blank=True, help_text='File template for taxonomic uploader', null=True, upload_to=''),
        ),
    ]
