# Generated by Django 2.2.12 on 2021-01-14 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0278_basemaplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_address', models.CharField(blank=True, max_length=100, null=True)),
                ('server_hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('start_time', models.FloatField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
