# Generated by Django 2.2.12 on 2021-02-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0280_ingesteddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemism',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
