# Generated by Django 2.2.12 on 2021-02-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0280_ingesteddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='github_repo_path',
            field=models.CharField(blank=True, default='', help_text='Path to git repository from where the version info can be retrieved', max_length=255),
        ),
    ]
