# Generated by Django 2.2.12 on 2021-02-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0281_sitesetting_github_repo_path'),
        ('bims', '0281_endemism_display_order'),
    ]

    operations = [
    ]
