# Generated by Django 2.2.12 on 2021-02-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0283_auto_20210218_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='collector_string',
            field=models.CharField(blank=True, default='', help_text='Collector name in string value, this is useful for collector values from GBIF and other third party sources', max_length=500, verbose_name='collector or observer'),
        ),
    ]
