# Generated by Django 2.2.12 on 2021-02-25 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0284_survey_collector_string'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='BimsDocumentAuthorship',
                fields=[
                    ('id',
                     models.AutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID')),
                    ('profile', models.ForeignKey(blank=True, null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 to=settings.AUTH_USER_MODEL)),
                ],
                options={
                    'db_table': 'bims_bimsdocument_authors',
                },
            ),
            migrations.AlterField(
                model_name='bimsdocument',
                name='profile',
                field=models.ManyToManyField(blank=True,
                                             through='bims.BimsDocumentAuthorship',
                                             to=settings.AUTH_USER_MODEL),
            ),
            migrations.AddField(
                model_name='bimsdocumentauthorship',
                name='bimsdocument',
                field=models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='bims.BimsDocument'),
            ),
        ])
    ]
