# Generated by Django 2.2.12 on 2021-02-25 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0285_auto_20210225_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bimsdocumentauthorship',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='bimsdocumentauthorship',
            name='ordering',
            field=models.PositiveIntegerField(default=1),
        )
    ]
