# Generated by Django 2.2.12 on 2021-03-17 02:38

from django.db import migrations

def update_empty_taxa_origin(apps, schema_editor):
    BiologicalCollectionRecord = apps.get_model('bims', 'BiologicalCollectionRecord')
    Taxonomy = apps.get_model('bims', 'Taxonomy')
    taxa = Taxonomy.objects.filter(origin='')
    try:
        bio = BiologicalCollectionRecord.objects.filter(
            taxonomy__in=taxa,
        ).exclude(category='').distinct('taxonomy')
    except Exception:
        print('the category field has been removed in bio')
        return
    print(bio.count())
    for b in bio:
        taxonomy = Taxonomy.objects.get(id=b.taxonomy.id)
        print('Updating {}'.format(taxonomy))
        try:
            taxonomy.origin = b.category
            taxonomy.save()
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0286_auto_20210225_0646'),
    ]

    operations = [
        migrations.RunPython(update_empty_taxa_origin, reverse_code=migrations.RunPython.noop),
    ]

