# Generated by Django 2.2.12 on 2021-03-17 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0287_auto_20210317_0238'),
    ]

    operations = [
    ]
