# Generated by Django 2.2.12 on 2021-03-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0288_auto_20210317_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name='category',
        ),
    ]
