# Generated by Django 2.2.12 on 2021-06-02 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0290_auto_20210421_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='analyst',
            field=models.ForeignKey(blank=True, help_text='The person that did the analysis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationsite_analyst', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='collector_user',
            field=models.ForeignKey(blank=True, help_text='The user object of the actual capturer/collector of this data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locationsite_collector_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='ready_for_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='validation_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
