# Generated by Django 2.2.12 on 2021-06-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0290_auto_20210521_0831'),
        ('bims', '0290_auto_20210421_0548'),
    ]

    operations = [
    ]
