# Generated by Django 2.2.12 on 2021-06-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0291_auto_20210602_1048'),
        ('bims', '0291_merge_20210606_1834'),
    ]

    operations = [
    ]
