# Generated by Django 2.2.16 on 2021-09-30 18:39

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0292_merge_20210623_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='siteimage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
