# Generated by Django 2.2.16 on 2021-10-25 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0293_auto_20210930_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('is_daily', models.BooleanField(default=False, help_text='Whether the data is daily or sub-daily.')),
                ('value', models.FloatField(help_text='Water temperature data, if daily data then this is the Mean value.')),
                ('minimum', models.FloatField(blank=True, help_text='This is for daily data', null=True)),
                ('maximum', models.FloatField(blank=True, help_text='This is for daily data', null=True)),
                ('location_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.LocationSite')),
            ],
            options={
                'ordering': ('date_time',),
            },
        ),
    ]
