# Generated by Django 2.2.16 on 2021-10-25 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0294_auto_20211025_0244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watertemperature',
            options={'ordering': ('-date_time',)},
        ),
        migrations.AddField(
            model_name='watertemperature',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the data (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_temperature_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watertemperature',
            name='source_file',
            field=models.CharField(blank=True, default='', help_text='Name of the source file', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watertemperature',
            name='uploader',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the data (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_temperature_uploader', to=settings.AUTH_USER_MODEL),
        )
    ]
