# Generated by Django 2.2.16 on 2021-12-01 06:33

import bims.models.upload_session
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0296_auto_20211025_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonextraattribute',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='boundary_key',
            field=models.CharField(blank=True, default='', help_text='The key of the boundary data form GeoContext', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='category',
            field=models.CharField(blank=True, choices=[('taxa', 'Taxa'), ('collections', 'Collections'), ('water_temperature', 'Water Temperature')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='error_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=bims.models.upload_session.UploadSession.file_storage),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='process_file',
            field=models.FileField(max_length=512, null=True, upload_to=bims.models.upload_session.UploadSession.file_storage),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='success_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=bims.models.upload_session.UploadSession.file_storage),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='updated_file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=bims.models.upload_session.UploadSession.file_storage),
        ),
    ]
