# Generated by Django 2.2.16 on 2022-01-27 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0299_auto_20220126_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='form_uploader',
            field=models.CharField(blank=True, choices=[('collection_record', 'Collection Record'), ('site', 'Site'), ('water_temperature', 'Water Temperature')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
