# Generated by Django 2.2.16 on 2022-02-22 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0300_auto_20220127_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertemperature',
            name='value',
            field=models.FloatField(blank=True, help_text='Water temperature data, if daily data then this is the Mean value.', null=True),
        ),
    ]
