# Generated by Django 2.2.16 on 2022-03-02 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.management import call_command

def add_default_location_site_view(apps, schema_editor):
    call_command('add_default_location_site_view')

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0301_auto_20220223_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSupportTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('biological_collection_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.BiologicalCollectionRecord')),
            ],
        ),
        migrations.RunPython(add_default_location_site_view)
    ]
