# Generated by Django 2.2.16 on 2022-03-01 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0301_auto_20220223_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='virtual_museum_source_filter',
            field=models.TextField(blank=True, default='', help_text='Sources to filter virtual museum data, separated by comma'),
        ),
    ]
