# Generated by Django 2.2.16 on 2022-03-30 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0302_auto_20220302_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='record_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
