# Generated by Django 2.2.28 on 2022-05-16 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0305_auto_20220426_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequestPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, help_text='Optional', null=True)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='dashboard_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='location_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.LocationSite'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='resource_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='resource_type',
            field=models.CharField(choices=[('CSV', 'Csv'), ('CHART', 'Chart')], default='CSV', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Survey'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='taxon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.Taxonomy'),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.DownloadRequestPurpose'),
        ),
    ]
