# Generated by Django 2.2.16 on 2022-04-27 14:19

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import signals

from sass.enums.chem_unit import ChemUnit


def init_unit(apps, schema_editor):
    """ Initialize table Unit"""
    try:
        from easyaudit.signals.model_signals import post_save
        signals.post_save.disconnect(post_save, dispatch_uid='easy_audit_signals_post_save')
    except RuntimeError:
        pass
    Unit = apps.get_model('bims', 'Unit')

    for unit in ChemUnit:
        obj = Unit(unit_name=unit.name, unit=unit.value)
        obj.save()
    try:
        from easyaudit.signals.model_signals import post_save
        signals.post_save.connect(post_save, dispatch_uid='easy_audit_signals_post_save')
    except RuntimeError:
        pass


def insert_value_to_unit_foreign_key(apps, schema_editor):
    """ Insert value to field unit"""

    Chem = apps.get_model('bims', 'Chem')
    Unit = apps.get_model('bims', 'Unit')
    for unit in ChemUnit:
        chem_unit = Chem.objects.filter(chem_unit=unit.name)
        chem_unit.update(unit=Unit.objects.get(unit_name=unit.name).id)


class Migration(migrations.Migration):
    dependencies = [
        ('bims', '0305_auto_20220426_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        # load chem unit to the database
        migrations.RunPython(init_unit),

        migrations.AddField(
            model_name='chem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.Unit'),
        ),

        # insert value to unit
        # migrations.RunPython(insert_value_to_unit_foreign_key),

        # remove chem_unit field
        migrations.RemoveField(
            model_name='chem',
            name='chem_unit',
        ),

        migrations.RenameField(
            model_name='chem',
            old_name='unit',
            new_name='chem_unit',
        ),

    ]

