# Generated by Django 2.2.28 on 2022-05-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0306_auto_20220516_0404'),
        ('bims', '0307_auto_20220517_0656'),
    ]

    operations = [
    ]
