# Generated by Django 2.2.28 on 2022-05-24 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0309_auto_20220523_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download_request_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
