# Generated by Django 2.2.28 on 2022-05-24 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0310_auto_20220524_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watertemperature',
            name='location_site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.LocationSite'),
        ),
    ]
