# Generated by Django 2.2.28 on 2022-06-20 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0311_auto_20220524_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='progress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
