# Generated by Django 2.2.28 on 2022-06-23 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0312_auto_20220620_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(blank=True, default='Copyright © Kartoza', max_length=200),
        ),
    ]
