# Generated by Django 2.2.28 on 2022-06-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0313_auto_20220623_0641'),
        ('bims', '0313_auto_20220622_0824'),
    ]

    operations = [
    ]
