# Generated by Django 2.2.28 on 2022-06-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0314_merge_20220623_0808'),
        ('bims', '0313_auto_20220622_0602'),
    ]

    operations = [
    ]
