# Generated by Django 2.2.28 on 2022-06-27 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0315_merge_20220627_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_water_temperature',
            field=models.BooleanField(default=False, help_text='Enable or disable Water Temperature data'),
        ),
        migrations.AddField(
            model_name='taxongroup',
            name='singular_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
