# Generated by Django 2.2.28 on 2022-07-01 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0316_auto_20220627_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='show_summary_data_on_dashboard',
        ),
    ]
