# Generated by Django 2.2.28 on 2022-07-20 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0317_auto_20220701_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('display_order', models.IntegerField(default=0)),
                ('climate_geocontext_group_key', models.CharField(help_text='Geocontext group used for climate data', max_length=128)),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
    ]
