# Generated by Django 2.2.28 on 2022-07-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0317_auto_20220628_0344'),
        ('bims', '0317_auto_20220701_0636'),
    ]

    operations = [
    ]
