# Generated by Django 2.2.28 on 2022-07-10 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0317_auto_20220701_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='chart_data',
            field=models.CharField(blank=True, choices=[('conservation status', 'Conservation Status'), ('division', 'DIVISION'), ('sass', 'SASS'), ('origin', 'ORIGIN'), ('endemism', 'ENDEMISM')], default='', help_text='Data to display on chart', max_length=100, null=True),
        ),
    ]
