# Generated by Django 2.2.28 on 2022-07-26 07:13

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0318_merge_20220718_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='mobile',
            field=models.BooleanField(default=False, help_text='Also available for mobile app'),
        ),
    ]
