# Generated by Django 2.2.28 on 2022-07-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0318_auto_20220710_2211'),
        ('bims', '0318_auto_20220720_0228'),
    ]

    operations = [
    ]
