# Generated by Django 2.2.28 on 2022-07-27 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0319_auto_20220726_0713'),
        ('bims', '0318_auto_20220720_0228'),
    ]

    operations = [
    ]
