# Generated by Django 2.2.28 on 2022-07-27 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('bims', '0320_merge_20220727_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocontextSetting',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('geocontext_url', models.URLField(blank=True, default='https://geocontext.kartoza.com/', help_text='Full URL for GeoContext service (include http:// and ends with /).')),
                ('geocontext_keys', models.TextField(blank=True, default='provinces,rainfall_group', help_text='Geocontext group keys that will be fetched from Geocontext, separated by commas.', verbose_name='Geocontext Group Keys')),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='geocontext_keys',
        ),
    ]
