# Generated by Django 2.2.28 on 2022-09-02 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0321_auto_20220727_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingmethod',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
