# Generated by Django 2.2.28 on 2022-07-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0319_merge_20220725_1439'),
        ('bims', '0321_auto_20220727_0237'),
    ]

    operations = [
    ]
