# Generated by Django 2.2.28 on 2022-09-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0323_auto_20220907_0957'),
        ('bims', '0322_merge_20220727_1136'),
    ]

    operations = [
    ]
