# Generated by Django 2.2.28 on 2022-11-28 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0327_auto_20221124_0807'),
        ('bims', '0327_auto_20221122_1819'),
    ]

    operations = [
    ]
