# Generated by Django 2.2.28 on 2023-01-24 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0328_merge_20221128_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='endemism',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
