# Generated by Django 2.2.28 on 2023-01-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0329_auto_20230124_1055'),
        ('bims', '0329_auto_20230125_0859'),
    ]

    operations = [
    ]
