# Generated by Django 2.2.28 on 2023-02-08 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0330_merge_20230127_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='layer_style',
            field=models.CharField(default='', help_text='Leave blank to use default style', max_length=256),
        ),
    ]
