# Generated by Django 2.2.28 on 2023-03-06 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0331_auto_20230208_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='vernacularname',
            name='is_upload',
            field=models.BooleanField(default=False, help_text='Whether this data coming from data upload'),
        ),
        migrations.AddField(
            model_name='vernacularname',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nonbiodiversitylayer',
            name='layer_style',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use default style', max_length=256),
        ),
    ]
