# Generated by Django 2.2.28 on 2023-05-11 08:08

from django.conf import settings
from django.db import migrations, models

def forwards(apps, schema_editor):
    LocationContextGroup = apps.get_model('bims', 'LocationContextGroup')
    for group in LocationContextGroup.objects.all():
        group.order = group.id
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0335_auto_20230413_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcontextgroup',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
