# Generated by Django 2.2.28 on 2023-06-15 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0336_auto_20230511_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcontextgroup',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name='sampling_method_string',
        ),
    ]
