# Generated by Django 3.2.20 on 2023-07-13 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0337_auto_20230615_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSupportToolName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='decisionsupporttool',
            name='dst_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.decisionsupporttoolname'),
        ),
    ]
