# Generated by Django 3.2.20 on 2023-07-13 05:45

from django.db import migrations


def migrate_names(apps, schema_editor):
    DecisionSupportTool = apps.get_model('bims', 'DecisionSupportTool')
    DecisionSupportToolName = apps.get_model('bims', 'DecisionSupportToolName')

    names = list(
        DecisionSupportTool.objects.all().distinct('name').values_list('name', flat=True)
    )

    for name in names:
        dst_name, _ = DecisionSupportToolName.objects.get_or_create(
            name=name
        )
        DecisionSupportTool.objects.filter(
            name=name
        ).update(
            dst_name=dst_name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0338_auto_20230713_0544'),
    ]

    operations = [
        migrations.RunPython(migrate_names),
    ]
