# Generated by Django 3.2.20 on 2023-07-14 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0339_auto_20230713_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTemperatureThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_maximum_threshold', models.FloatField(default=23.2)),
                ('upper_minimum_threshold', models.FloatField(default=12.0)),
                ('upper_mean_threshold', models.FloatField(default=18.0)),
                ('upper_record_length', models.FloatField(default=0.0)),
                ('upper_degree_days', models.FloatField(default=10.0)),
                ('lower_maximum_threshold', models.FloatField(default=23.2)),
                ('lower_minimum_threshold', models.FloatField(default=12.0)),
                ('lower_mean_threshold', models.FloatField(default=25.0)),
                ('lower_record_length', models.FloatField(default=0.0)),
                ('lower_degree_days', models.FloatField(default=10.0)),
                ('creator', models.ForeignKey(blank=True, help_text='Creator of the threshold', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('location_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.locationsite')),
            ],
        ),
    ]
