# Generated by Django 4.1.10 on 2023-08-23 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0342_biologicalcollectionrecord_ecosystem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='ecosystem_type',
            field=models.CharField(blank=True, choices=[('River', 'River'), ('Wetland', 'Wetland'), ('Open waterbody', 'Open waterbody')], default='', max_length=128, null=True),
        ),
    ]
