# Generated by Django 4.1.10 on 2023-08-25 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0346_alter_bimsdocument_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='hydrogeomorphic_type',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='user_hydrogeomorphic_type',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Floodplain', 'Floodplain'), ('Channelled valley-bottom', 'Channelled valley-bottom'), ('Unchannelled valley-bottom', 'Unchannelled valley-bottom'), ('Seep', 'Seep'), ('Depression', 'Depression'), ('Wetland flat', 'Wetland flat'), ('Unknown', 'Unknown')], default='-', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='user_wetland_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='wetland_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
