# Generated by Django 4.1.10 on 2023-09-15 02:48

from django.conf import settings
from django.db import migrations, models
from django.core.management import call_command
import django.db.models.deletion

def load_fixture(apps, schema_editor):
    call_command('add_default_fbis_location_site_view')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0347_locationsite_hydrogeomorphic_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonimage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonimage',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of the taxon image (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxon_image_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonimage',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.survey'),
        ),
        migrations.AddField(
            model_name='taxonimage',
            name='uploader',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the taxon image (Optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxon_image_uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(load_fixture),
    ]
