# Generated by Django 4.1.10 on 2023-09-26 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0348_taxonimage_date_taxonimage_owner_taxonimage_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcontextfiltergrouporder',
            name='is_hidden_in_spatial_filter',
            field=models.BooleanField(default=False, help_text='Indicates if the item should be hidden in the spatial filter.'),
        ),
        migrations.AddField(
            model_name='locationcontextfiltergrouporder',
            name='use_autocomplete_in_filter',
            field=models.BooleanField(default=False, help_text='Enable autocomplete for the filter. Useful when dealing with large datasets in the location context.'),
        ),
    ]
