# Generated by Django 4.1.10 on 2023-09-29 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0349_locationcontextfiltergrouporder_is_hidden_in_spatial_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_hidden_in_form', models.BooleanField(default=False, help_text='Indicate if this record type should be hidden in forms.')),
            ],
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='record_type_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.recordtype'),
        ),
    ]
