# Generated by Django 4.1.10 on 2023-09-29 04:15

from django.db import migrations

def link_record_type(apps, schema_editor):
    RecordType = apps.get_model('bims', 'RecordType')
    BiologicalCollectionRecord = apps.get_model('bims', 'BiologicalCollectionRecord')

    record_types = list(
        BiologicalCollectionRecord.objects.filter(
            record_type__isnull=False).exclude(
            record_type='').values_list('record_type', flat=True).distinct()
    )

    for record_type in record_types:
        record_type_obj, created = RecordType.objects.get_or_create(
            name=record_type
        )
        BiologicalCollectionRecord.objects.filter(
            record_type=record_type
        ).update(record_type_link=record_type_obj)


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0350_recordtype_alter_bimsdocument_authors_and_more'),
    ]

    operations = [
        migrations.RunPython(link_record_type),
    ]
