# Generated by Django 4.1.10 on 2023-09-29 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0352_remove_biologicalcollectionrecord_record_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biologicalcollectionrecord',
            old_name='record_type_link',
            new_name='record_type',
        ),
    ]
