# Generated by Django 4.1.10 on 2023-10-04 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0356_hydroperiod_wetlandindicatorstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name='hydroperiod',
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='hydroperiod_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.hydroperiod'),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='wetland_indicator_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.wetlandindicatorstatus'),
        ),
    ]
