# Generated by Django 4.1.10 on 2023-10-05 09:08

from django.db import migrations

abundance_type_list = {
    'number': 'Number',
    'percentage': 'Percentage',
    'density': 'Density',
    'species_valve_per_frustule_count': 'Species valve/frustule count',
    'density_cells_per_m2': 'Density (cells/m2)',
    'density_cells_per_mL': 'Density (cells/mL)',
}


def link_abundance_type(apps, schema_editor):
    AbundanceType = apps.get_model('bims', 'AbundanceType')
    BiologicalCollectionRecord = apps.get_model('bims', 'BiologicalCollectionRecord')
    TaxonGroup = apps.get_model('bims', 'TaxonGroup')
    order = 0

    abundance_types = list(
        BiologicalCollectionRecord.objects.filter(
            abundance_type__isnull=False).exclude(
            abundance_type='').values_list('abundance_type', flat=True).distinct()
    )

    for abundance_type in abundance_types:
        if abundance_type not in abundance_type_list:
            continue
        abundance_type_obj, created = AbundanceType.objects.get_or_create(
            name=abundance_type_list[abundance_type],
            order=order
        )
        order += 1
        BiologicalCollectionRecord.objects.filter(
            abundance_type=abundance_type
        ).update(abundance_type_link=abundance_type_obj)

    algae = TaxonGroup.objects.filter(name__iexact='algae').first()
    if algae:
        algae_abundance_types = [
            'Species valve/frustule count',
            'Percentage Abundance',
            'Density (cells/m2)',
            'Density (cells/mL)'
        ]
        for algae_abundance_type in algae_abundance_types:
            AbundanceType.objects.filter(
                name__icontains=algae_abundance_type
            ).update(specific_module=algae)


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0359_alter_bimsdocument_authors_abundancetype_and_more'),
    ]

    operations = [
        migrations.RunPython(link_abundance_type),
    ]
