# Generated by Django 4.1.10 on 2023-10-06 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0361_remove_biologicalcollectionrecord_abundance_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biologicalcollectionrecord',
            old_name='abundance_type_link',
            new_name='abundance_type',
        ),
    ]
