# Generated by Django 4.1.10 on 2023-10-24 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0363_alter_basemaplayer_key_alter_bimsdocument_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='refined_geomorphological',
            field=models.CharField(blank=True, choices=[('Source zone', 'Source zone'), ('Mountain headwater stream', 'Mountain headwater stream'), ('Mountain stream', 'Mountain stream'), ('Transitional', 'Transitional'), ('Upper foothill', 'Upper foothill'), ('Lower foothill', 'Lower foothill'), ('Lowland river', 'Lowland river'), ('Rejuvenated bedrock fall / cascades', 'Rejuvenated bedrock fall / cascades'), ('Rejunevated foothill', 'Rejunevated foothill'), ('Upland floodplain', 'Upland floodplain'), ('Upland transitional', 'Upland transitional'), ('Foothil/Transitional', 'Foothil/Transitional'), ('Upland plateau', 'Upland plateau'), ('Foothill', 'Foothill')], help_text='Would be used in preference to the one discovered in geocontext', max_length=200, null=True, verbose_name='User geomorphological'),
        ),
        migrations.CreateModel(
            name='SamplingEffortMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=256)),
                ('specific_module', models.ForeignKey(blank=True, help_text='If specified, then this sampling effort measure will be available only for this module.', null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.taxongroup')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='sampling_effort_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.samplingeffortmeasure'),
        ),
    ]
