# Generated by Django 4.1.10 on 2023-10-25 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0365_auto_20231024_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='document',
            field=models.FileField(blank=True, help_text='File to be displayed as an attachment in the attribute popup.', null=True, upload_to='non_biodiversity_layer_document'),
        ),
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='document_title',
            field=models.CharField(blank=True, help_text='Title for the attached document. Displayed on the download button.', max_length=128, null=True),
        ),
    ]
