# Generated by Django 4.1.10 on 2023-12-05 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0367_remove_locationsite_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='end_embargo_date',
            field=models.DateField(blank=True, help_text='The date when the embargo on the data expires. After this date, the data will become public.', null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='end_embargo_date',
            field=models.DateField(blank=True, help_text='The date when the embargo on the data expires. After this date, the data will become public.', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='end_embargo_date',
            field=models.DateField(blank=True, help_text='The date when the embargo on the data expires. After this date, the data will become public.', null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='end_embargo_date',
            field=models.DateField(blank=True, help_text='The date when the embargo on the data expires. After this date, the data will become public.', null=True),
        ),
    ]
