# Generated by Django 4.2.8 on 2023-12-22 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0374_alter_taxongroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='experts',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
