# Generated by Django 4.2.8 on 2023-12-22 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0375_taxongroup_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='level',
            field=models.CharField(blank=True, choices=[('level_1', 'Level 1: Organism'), ('level_2', 'Level 2: Regions and/or ecosystem type'), ('level_3', 'Level 3: Country')], help_text='Level of the taxon group', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxongroup',
            name='category',
            field=models.CharField(blank=True, choices=[('SPECIES_MODULE', 'Species Module'), ('SPECIES_CLASS', 'Species Class'), ('SASS_TAXON_GROUP', 'SASS Taxon Group'), ('DIVISION_GROUP', 'Division Group')], max_length=50, verbose_name='Taxonomic Group Category'),
        ),
    ]
