# Generated by Django 4.2.8 on 2024-01-02 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0376_taxongroup_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprocess',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='map_default_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Which filters are selected by default, the format must be as follows : [{"filter_key": "sourceCollection", "filter_values": ["bims"]}]', null=True),
        ),
    ]
