# Generated by Django 4.2.8 on 2024-02-01 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('bims', '0377_searchprocess_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestsession',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.boundary'),
        ),
        migrations.AddField(
            model_name='harvestsession',
            name='is_fetching_species',
            field=models.BooleanField(default=False, help_text='Flag indicating whether it is only fetching species'),
        ),
        migrations.AddField(
            model_name='taxongroup',
            name='gbif_parent_species',
            field=models.ForeignKey(blank=True, help_text='Used to fetch species from GBIF', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxon_groups', to='bims.taxonomy'),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
