# Generated by Django 4.2.8 on 2024-02-02 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('bims', '0378_harvestsession_boundary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcontextfilter',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site this LocationContextFilter is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Associated Site'),
        ),
        migrations.AddField(
            model_name='locationcontextfiltergrouporder',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site this LocationContextFilterGroupOrder is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Associated Site'),
        ),
    ]
