# Generated by Django 4.2.8 on 2024-02-06 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0381_nonbiodiversitylayer_source_site_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='bimsdocument',
                    name='authors',
                    field=models.ManyToManyField(blank=True, through='bims.BimsDocumentAuthorship', to=settings.AUTH_USER_MODEL),
                ),
        ])
    ]
