# Generated by Django 4.2.8 on 2024-02-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0383_taxongrouptaxonomy_alter_taxongroup_taxonomies'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongrouptaxonomy',
            name='endemism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.endemism', verbose_name='Endemism'),
        ),
        migrations.AddField(
            model_name='taxongrouptaxonomy',
            name='origin',
            field=models.CharField(blank=True, choices=[('alien', 'Non-Native'), ('indigenous', 'Native'), ('unknown', 'Unknown'), ('alien-invasive', 'Non-native: invasive'), ('alien-non-invasive', 'Non-native: non-invasive')], default='', help_text='Origin', max_length=50),
        ),
    ]
