# Generated by Django 4.2.8 on 2024-02-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0384_taxongrouptaxonomy_endemism_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyUpdateProposal',
            fields=[
                ('taxonomy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bims.taxonomy')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='bims.taxonomy', verbose_name='Original Taxonomy')),
                ('taxon_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.taxongroup')),
            ],
            options={
                'db_table': 'taxonomy_update_proposal',
            },
            bases=('bims.taxonomy',),
        ),
    ]
