# Generated by Django 4.2.8 on 2024-02-09 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0385_taxonomyupdateproposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyUpdateReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('taxonomy_update_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.taxonomyupdateproposal')),
            ],
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='reviewers',
            field=models.ManyToManyField(blank=True, through='bims.TaxonomyUpdateReviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
