# Generated by Django 4.2.8 on 2024-02-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bims', '0386_taxonomyupdatereviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='additional_observation_sites',
            field=models.ManyToManyField(blank=True, help_text="List of sites where this biological occurrence has also been observed. This attribute allows for recording multiple observation locations beyond the primary source site. For instance, if an occurrence is recorded at the main location 'FBIS' and is also observed at 'SanParks', this field facilitates linking the occurrence to 'SanParks' as an additional observation site.", related_name='additional_observation_sites', to='sites.site'),
        ),
    ]
