# Generated by Django 4.2.8 on 2024-02-12 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bims', '0387_biologicalcollectionrecord_additional_observation_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='source_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
        migrations.AddField(
            model_name='downloadrequestpurpose',
            name='source_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_source_site',
            field=models.ForeignKey(blank=True, help_text='The source site where the user signed up. For tracking user registration origins.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
        migrations.AddField(
            model_name='taxongroup',
            name='additional_sites',
            field=models.ManyToManyField(blank=True, help_text='A list of additional sites associated with this taxon group.', related_name='additional_sites', to='sites.site'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='source_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
    ]
