# Generated by Django 4.2.8 on 2024-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0388_downloadrequest_source_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongrouptaxonomy',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
