# Generated by Django 4.2.8 on 2024-02-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0389_boundary_owner'),
        ('bims', '0389_taxongrouptaxonomy_is_rejected'),
    ]

    operations = [
    ]
