# Generated by Django 4.2.8 on 2024-03-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bims', '0391_biologicalcollectionrecord_accuracy_of_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='additional_sites',
            field=models.ManyToManyField(blank=True, help_text='Additional sites where this layer will be displayed.', related_name='non_bio_layer_additional_sites', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='nonbiodiversitylayer',
            name='source_site',
            field=models.ForeignKey(blank=True, help_text='The site this record is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Source Site'),
        ),
    ]
