# Generated by Django 4.2.8 on 2024-03-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bims', '0394_locationsite_additional_observation_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site'),
        ),
    ]
