# Generated by Django 4.2.8 on 2024-04-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bims', '0395_notification_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcereference',
            name='active_sites',
            field=models.ManyToManyField(blank=True, help_text='Identifies the sites where the source reference is actively used.', related_name='source_reference_active_sites', to='sites.site'),
        ),
    ]
