# Generated by Django 4.2.8 on 2024-05-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0401_alter_taxonomy_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='cites_token_api',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
