# Generated by Django 4.2.8 on 2024-06-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0404_sitesetting_geoserver_location_site_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='park_wfs_attribute_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='park_wfs_layer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='park_wfs_url',
            field=models.CharField(blank=True, default='https://maps.kartoza.com/geoserver/wfs', max_length=200),
        ),
    ]
