# Generated by Django 4.2.8 on 2024-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0406_citeslistinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='occurrence_upload_template',
            field=models.FileField(blank=True, help_text='File template for occurrence data upload', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='taxongroup',
            name='taxa_upload_template',
            field=models.FileField(blank=True, help_text='File template for taxa data upload', null=True, upload_to=''),
        ),
    ]
