# Generated by Django 4.2.8 on 2024-06-20 17:11

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0408_taxonomy_hierarchical_data_alter_taxonomy_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='A taxon tag name')),
                ('doubtful', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Taxonomy Tag',
                'verbose_name_plural': 'Taxonomy Tags',
            },
        ),
        migrations.CreateModel(
            name='CustomTaggedTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.taxonomy')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='bims.taxontag')),
            ],
            options={
                'verbose_name': 'Custom Tagged Taxonomy',
                'verbose_name_plural': 'Custom Tagged Taxa',
            },
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='biographic_distributions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='bims.CustomTaggedTaxonomy', to='bims.TaxonTag', verbose_name='Tags'),
        ),
    ]
