# Generated by Django 4.2.8 on 2024-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0410_importtask_sitesetting_virtual_museum_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
