# Generated by Django 4.2.8 on 2024-06-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0411_importtask_cancel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iucnstatus',
            options={'ordering': ['order'], 'verbose_name': 'IUCN Status', 'verbose_name_plural': 'IUCN Status'},
        ),
        migrations.AddField(
            model_name='iucnstatus',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iucnstatus',
            name='category',
            field=models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('CR PE', 'Critically Endangered, Possibly Extinct'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct'), ('RE', 'Regionally Extinct'), ('CA', 'Critically Rare'), ('RA', 'Rare'), ('D', 'Declining'), ('DD', 'Data Deficient'), ('DDD', 'Data Deficient - Insufficient Information'), ('DDT', 'Data Deficient - Taxonomically Problematic'), ('NE', 'Not Evaluated')], default='', max_length=50),
        ),
    ]
