# Generated by Django 4.2.8 on 2024-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0412_alter_iucnstatus_options_iucnstatus_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonbiodiversitylayer',
            name='additional_sites',
        ),
        migrations.AlterField(
            model_name='iucnstatus',
            name='category',
            field=models.CharField(blank=True, choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('CR PE', 'Critically Endangered, Possibly Extinct'), ('EW', 'Extinct in the Wild'), ('EX', 'Extinct'), ('RE', 'Regionally Extinct'), ('CA', 'Critically Rare'), ('RA', 'Rare'), ('D', 'Declining'), ('DD', 'Data Deficient'), ('DDD', 'Data Deficient - Insufficient Information'), ('DDT', 'Data Deficient - Taxonomically Problematic'), ('NE', 'Not Evaluated'), ('LR/cd', 'Conservation Dependent'), ('LR/nt', 'Near Threatened - Legacy'), ('LR/lc', 'Least Concern - Legacy')], default='', max_length=50),
        ),
    ]
