# Generated by Django 4.2.9 on 2024-07-02 12:59

from django.db import migrations


def populate_roles(apps, schema_editor):
    Role = apps.get_model('bims', 'Role')
    roles = [
        ('citizen', 'Citizen'),
        ('water_resource_manager', 'Water Resource Manager'),
        ('researcher', 'Researcher'),
        ('consultant', 'Consultant'),
        ('conservation_planner', 'Conservation Planner'),
        ('national_park_management', 'National Park management'),
        ('district_environmental_officer', 'District Environmental Officer'),
        ('government_staff', 'Government staff'),
        ('academic_staff', 'Academic staff'),
        ('policy_maker', 'Policy maker')
    ]
    index = 0
    for name, display_name in roles:
        try:
            Role.objects.update_or_create(
                name=name,
                display_name=display_name,
                defaults={
                    'order': index,
                }
            )
        except Exception as e:
            print(e)
        index += 1


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0414_role'),
    ]

    operations = [
        migrations.RunPython(populate_roles),
    ]
