# Generated by Django 4.2.9 on 2024-07-02 13:10

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0415_auto_20240702_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bims.role'),
        ),
    ]
