# Generated by Django 4.2.9 on 2024-07-02 13:18

from django.db import migrations


def link_designation(apps, schema_editor):
    LEGACY_ROLE_CHOICES = (
        ('water_resource_manager', 'Water Resource Manager'),
        ('researcher', 'Researcher'),
        ('consultant', 'Consultant'),
        ('conservation_planner', 'Conservation Planner'),
        ('citizen', 'Citizen'),
        ('national_park_management', 'National Park management'),
        ('district_environmental_officer', 'District Environmental Officer'),
        ('government_staff', 'Government staff'),
        ('academic_staff', 'Academic staff'),
        ('policy_maker', 'Policy maker')
    )
    Role = apps.get_model('bims', 'Role')
    Profile = apps.get_model('bims', 'Profile')
    for profile in Profile.objects.all():
        role_choices = dict(LEGACY_ROLE_CHOICES)
        try:
            profile_role = profile.role
            if profile_role and profile_role in role_choices:
                role, created = Role.objects.get_or_create(
                    name=profile.role,
                    display_name=role_choices[profile.role])
                profile.role_link = role
                profile.save()
        except Exception as e:
            print(e)

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0416_profile_role_link'),
    ]

    operations = [
        migrations.RunPython(link_designation),
    ]
