# Generated by Django 4.2.9 on 2024-07-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0417_auto_20240702_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
