# Generated by Django 4.2.9 on 2024-07-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0418_remove_profile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role_link',
            new_name='role',
        ),
    ]
