# Generated by Django 4.2.11 on 2024-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0419_rename_role_link_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name='additional_observation_sites',
        ),
        migrations.RemoveField(
            model_name='locationsite',
            name='additional_observation_sites',
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='data_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('sensitive', 'Sensitive')], default='', help_text='Specify data sharing level of this record', max_length=128),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='date_accuracy',
            field=models.CharField(blank=True, choices=[('accurate', 'Accurate'), ('artificial', 'Artificial')], default='', help_text='Indicate if date is accurate or artificial', max_length=64),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='iucn_api_key',
            field=models.CharField(blank=True, default='', help_text='Token key for IUCN api', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_code_generator',
            field=models.CharField(blank=True, choices=[('bims', 'BIMS (2 Site Name + 2 Site Description + Site count)'), ('fbis', 'FBIS (2 Secondary catchment + 4 River + Site count)'), ('rbis', 'RBIS (Catchment + Province ID + District ID + Site count)'), ('sanparks', 'SANPARKS (1st three park name + 1st two site description + site count)')], default='bims', help_text='How site code generated', max_length=50),
        ),
    ]
