# Generated by Django 4.2.11 on 2024-07-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0420_remove_biologicalcollectionrecord_additional_observation_sites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='identified_by',
            field=models.CharField(blank=True, default='', help_text='Name of the person who identified the species', max_length=300, verbose_name='Identifier'),
        ),
    ]
