# Generated by Django 4.2.11 on 2024-07-10 15:27

from django.db import migrations

def delete_old_table(apps, schema_editor):
    schema_editor.execute("DROP TABLE IF EXISTS taxonomy_update_proposal CASCADE")

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0421_biologicalcollectionrecord_identified_by'),
    ]

    operations = [
        migrations.RunPython(delete_old_table),
    ]
