# Generated by Django 4.2.11 on 2024-07-10 15:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0425_alter_taxonomyupdateproposal_accepted_taxonomy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTaggedUpdateTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims.taxonomyupdateproposal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='bims.taxontag')),
            ],
            options={
                'verbose_name': 'Custom Tagged Taxonomy',
                'verbose_name_plural': 'Custom Tagged Taxa',
            },
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='biographic_distributions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='bims.CustomTaggedUpdateTaxonomy', to='bims.TaxonTag', verbose_name='Tags'),
        ),
    ]
