# Generated by Django 4.2.11 on 2024-07-15 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0426_customtaggedupdatetaxonomy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='source_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_source_reference', to='bims.sourcereference'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='source_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_source_reference', to='bims.sourcereference'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='biographic_distributions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='bims.CustomTaggedTaxonomy', to='bims.TaxonTag', verbose_name='Biographic Distributions'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='import_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='import_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
