# Generated by Django 4.2.11 on 2024-07-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0428_remove_biologicalcollectionrecord_accuracy_of_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchprocess',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(blank=True, choices=[('DOMAIN', 'Domain'), ('KINGDOM', 'Kingdom'), ('PHYLUM', 'Phylum'), ('SUBPHYLUM', 'SubPhylum'), ('CLASS', 'Class'), ('SUBCLASS', 'Sub Class'), ('ORDER', 'Order'), ('SUBORDER', 'Sub Order'), ('INFRAORDER', 'Infra Order'), ('SUPERFAMILY', 'Super Family'), ('FAMILY', 'Family'), ('SUBFAMILY', 'Sub Family'), ('TRIBE', 'Tribe'), ('SUBTRIBE', 'Sub Tribe'), ('GENUS', 'Genus'), ('SUBGENUS', 'Sub Genus'), ('SPECIES', 'Species'), ('SUBSPECIES', 'Sub Species'), ('VARIETY', 'Variety'), ('FORMA', 'Forma')], max_length=50, verbose_name='Taxonomic Rank'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='rank',
            field=models.CharField(blank=True, choices=[('DOMAIN', 'Domain'), ('KINGDOM', 'Kingdom'), ('PHYLUM', 'Phylum'), ('SUBPHYLUM', 'SubPhylum'), ('CLASS', 'Class'), ('SUBCLASS', 'Sub Class'), ('ORDER', 'Order'), ('SUBORDER', 'Sub Order'), ('INFRAORDER', 'Infra Order'), ('SUPERFAMILY', 'Super Family'), ('FAMILY', 'Family'), ('SUBFAMILY', 'Sub Family'), ('TRIBE', 'Tribe'), ('SUBTRIBE', 'Sub Tribe'), ('GENUS', 'Genus'), ('SUBGENUS', 'Sub Genus'), ('SPECIES', 'Species'), ('SUBSPECIES', 'Sub Species'), ('VARIETY', 'Variety'), ('FORMA', 'Forma')], max_length=50, verbose_name='Taxonomic Rank'),
        ),
    ]
