# Generated by Django 4.2.11 on 2024-08-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0429_searchprocess_locked_alter_taxonomy_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invasion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('category', models.CharField()),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Invasion',
                'verbose_name_plural': 'Invasions',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='invasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.invasion'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='invasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.invasion'),
        ),
    ]
