# Generated by Django 4.2.11 on 2024-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0431_auto_20240807_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='park_layer_csv',
            field=models.FileField(blank=True, null=True, upload_to='park_layer_csv/'),
        ),
    ]
