# Generated by Django 4.2.15 on 2024-08-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0433_sitesetting_minisass_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtype',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
