# Generated by Django 4.2.15 on 2024-08-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0434_recordtype_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='new_data',
            field=models.BooleanField(default=False),
        ),
    ]
