# Generated by Django 4.2.15 on 2024-08-22 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('bims', '0434_recordtype_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_navbar', models.BooleanField(default=False, verbose_name='Show in Navbar')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('flatpage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='flatpages.flatpage')),
            ],
            options={
                'verbose_name': 'Custom Flat Page',
                'verbose_name_plural': 'Custom Flat Pages',
                'ordering': ['display_order'],
            },
        ),
    ]
