# Generated by Django 4.2.15 on 2024-08-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0435_flatpageextension'),
        ('bims', '0435_taxonomyupdateproposal_new_data'),
    ]

    operations = [
    ]
