# Generated by Django 4.2.15 on 2024-08-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0436_merge_20240823_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpageextension',
            name='redirect_only',
            field=models.BooleanField(default=False, verbose_name='Redirect Only'),
        ),
    ]
