# Generated by Django 4.2.15 on 2024-08-28 09:23

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('bims', '0437_flatpageextension_redirect_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('colour', colorfield.fields.ColorField(default='#FF5733', image_field=None, max_length=18, samples=None)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the tag group')),
                ('tags', models.ManyToManyField(related_name='tag_groups', to='taggit.tag')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
