# Generated by Django 4.2.15 on 2024-09-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_native_gis', '0001_initial'),
        ('bims', '0441_alter_dataset_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonbiodiversitylayer',
            name='source_site',
        ),
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='native_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_native_gis.layer'),
        ),
        migrations.AddField(
            model_name='nonbiodiversitylayer',
            name='native_layer_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloud_native_gis.style'),
        ),
        migrations.AlterField(
            model_name='nonbiodiversitylayer',
            name='layer_style',
            field=models.CharField(blank=True, default='', help_text='Leave blank to use default style', max_length=256, verbose_name='External layer style name'),
        ),
        migrations.AlterField(
            model_name='nonbiodiversitylayer',
            name='wms_format',
            field=models.CharField(blank=True, default='image/png', max_length=64, verbose_name='Layer format'),
        ),
        migrations.AlterField(
            model_name='nonbiodiversitylayer',
            name='wms_layer_name',
            field=models.CharField(max_length=128, verbose_name='Layer name'),
        ),
        migrations.AlterField(
            model_name='nonbiodiversitylayer',
            name='wms_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='Url'),
        ),
    ]
