# Generated by Django 4.2.15 on 2024-10-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0442_remove_nonbiodiversitylayer_source_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationcontextgroup',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
