# Generated by Django 4.2.16 on 2024-10-11 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0443_locationcontextgroup_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='upstream_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Upstream id, e.g. Gbif key', max_length=200),
        ),
    ]
