# Generated by Django 4.2.16 on 2024-10-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0444_alter_biologicalcollectionrecord_upstream_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='data_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('public', 'Public'), ('sensitive', 'Sensitive')], db_index=True, default='', help_text='Specify data sharing level of this record', max_length=128),
        ),
        migrations.AddIndex(
            model_name='biologicalcollectionrecord',
            index=models.Index(fields=['source_collection', 'taxonomy'], name='bims_biolog_source__2d27a3_idx'),
        ),
        migrations.AddIndex(
            model_name='biologicalcollectionrecord',
            index=models.Index(fields=['owner', 'end_embargo_date'], name='bims_biolog_owner_i_6e33af_idx'),
        ),
        migrations.AddIndex(
            model_name='biologicalcollectionrecord',
            index=models.Index(fields=['data_type'], name='bims_biolog_data_ty_ed8f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='locationcontext',
            index=models.Index(fields=['group', 'value'], name='bims_locati_group_i_0c9073_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['site', 'date', 'collector_user', 'owner'], name='bims_survey_site_id_84f46d_idx'),
        ),
    ]
