# Generated by Django 4.2.16 on 2024-10-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_native_gis', '0002_layer_pmtile'),
        ('bims', '0445_alter_biologicalcollectionrecord_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='park_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cloud_native_gis.layer'),
        ),
    ]
