# Generated by Django 4.2.16 on 2024-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0446_sitesetting_park_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='park_wfs_attribute_key',
            field=models.CharField(blank=True, default='', help_text='Park attribute key', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxongrouptaxonomy',
            name='is_rejected',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='taxongrouptaxonomy',
            name='is_validated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='canonical_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Canonical Name'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='canonical_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Canonical Name'),
        ),
    ]
