# Generated by Django 4.2.16 on 2024-10-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0447_alter_sitesetting_park_wfs_attribute_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='section_layer_csv',
            field=models.FileField(blank=True, null=True, upload_to='section_layer_csv/'),
        ),
    ]
