# Generated by Django 4.2.16 on 2024-12-03 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0448_sitesetting_section_layer_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Collection record uuid', null=True, unique=True),
        ),
    ]
