# Generated by Django 4.2.16 on 2025-01-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0449_alter_biologicalcollectionrecord_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='auto_validate_taxa_on_upload',
            field=models.BooleanField(default=True, help_text='If True, taxa from CSV uploads are automatically validated.'),
        ),
    ]
