# Generated by Django 4.2.16 on 2025-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0451_auto_20250224_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalcollectionrecord',
            name='source_site',
        ),
        migrations.RemoveField(
            model_name='locationsite',
            name='source_site',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='source_site',
        ),
        migrations.RemoveField(
            model_name='taxonomy',
            name='source_site',
        ),
        migrations.RemoveField(
            model_name='taxonomyupdateproposal',
            name='source_site',
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='fada_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='FADA ID'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='fada_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='FADA ID'),
        ),
    ]
