# Generated by Django 4.2.16 on 2025-03-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0452_remove_biologicalcollectionrecord_source_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='origin',
            field=models.CharField(blank=True, choices=[('alien', 'Non-Native'), ('indigenous', 'Native'), ('unknown', 'Unknown'), ('alien-invasive', 'Non-native: invasive'), ('alien-non-invasive', 'Non-native: non-invasive')], default='', help_text='Origin', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='fada_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='FADA ID'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='origin',
            field=models.CharField(blank=True, choices=[('alien', 'Non-Native'), ('indigenous', 'Native'), ('unknown', 'Unknown'), ('alien-invasive', 'Non-native: invasive'), ('alien-non-invasive', 'Non-native: non-invasive')], default='', help_text='Origin', max_length=50),
        ),
    ]
