# Generated by Django 4.2.16 on 2025-05-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0453_alter_taxonomy_origin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggroup',
            options={'ordering': ('order',)},
        ),
    ]
