# Generated by Django 4.2.20 on 2025-05-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0454_alter_taggroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='map_min_zoom',
            field=models.IntegerField(default=5, help_text='Minimum zoom level allowed for the map. Lower values show a wider area.'),
        ),
    ]
