# Generated by Django 4.2.20 on 2025-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0454_alter_taggroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='is_public_taxa',
            field=models.BooleanField(default=False, help_text='Allow non-logged-in users to view the taxa page.'),
        ),
    ]
