# Generated by Django 4.2.20 on 2025-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0455_sitesetting_map_min_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_code_generator',
            field=models.CharField(blank=True, choices=[('bims', 'BIMS (2 Site Name + 2 Site Description + Site count)'), ('fbis', 'FBIS (2 Secondary catchment + 4 River + Site count)'), ('fbis_africa', 'FBIS Africa (3 × ISO Country Code + base-36 Site count)'), ('rbis', 'RBIS (Catchment + Province ID + District ID + Site count)'), ('sanparks', 'SANPARKS (1st three park name + site count)')], default='bims', help_text='How site code generated', max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(blank=True, choices=[('DOMAIN', 'Domain'), ('KINGDOM', 'Kingdom'), ('PHYLUM', 'Phylum'), ('SUBPHYLUM', 'SubPhylum'), ('SUPERCLASS', 'Super Class'), ('CLASS', 'Class'), ('SUBCLASS', 'Sub Class'), ('SUPERORDER', 'Super Order'), ('ORDER', 'Order'), ('SUBORDER', 'Sub Order'), ('INFRAORDER', 'Infra Order'), ('SUPERFAMILY', 'Super Family'), ('FAMILY', 'Family'), ('SUBFAMILY', 'Sub Family'), ('TRIBE', 'Tribe'), ('SUBTRIBE', 'Sub Tribe'), ('GENUS', 'Genus'), ('SUBGENUS', 'Sub Genus'), ('SPECIES', 'Species'), ('SUBSPECIES', 'Sub Species'), ('VARIETY', 'Variety'), ('FORMA', 'Forma')], max_length=50, verbose_name='Taxonomic Rank'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='rank',
            field=models.CharField(blank=True, choices=[('DOMAIN', 'Domain'), ('KINGDOM', 'Kingdom'), ('PHYLUM', 'Phylum'), ('SUBPHYLUM', 'SubPhylum'), ('SUPERCLASS', 'Super Class'), ('CLASS', 'Class'), ('SUBCLASS', 'Sub Class'), ('SUPERORDER', 'Super Order'), ('ORDER', 'Order'), ('SUBORDER', 'Sub Order'), ('INFRAORDER', 'Infra Order'), ('SUPERFAMILY', 'Super Family'), ('FAMILY', 'Family'), ('SUBFAMILY', 'Sub Family'), ('TRIBE', 'Tribe'), ('SUBTRIBE', 'Sub Tribe'), ('GENUS', 'Genus'), ('SUBGENUS', 'Sub Genus'), ('SPECIES', 'Species'), ('SUBSPECIES', 'Sub Species'), ('VARIETY', 'Variety'), ('FORMA', 'Forma')], max_length=50, verbose_name='Taxonomic Rank'),
        ),
    ]
