# Generated by Django 4.2.16 on 2025-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0456_alter_sitesetting_site_code_generator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(help_text='Human-readable group name.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe unique identifier (auto-fill in admin).', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional longer description shown in layer selector.')),
                ('layers', models.ManyToManyField(blank=True, help_text='Layers that belong to this group (drag or multi-select).', related_name='layer_groups', to='bims.nonbiodiversitylayer')),
            ],
            options={
                'verbose_name': 'Layer group',
                'verbose_name_plural': 'Layer groups',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
