# Generated by Django 4.2.21 on 2025-07-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0456_alter_sitesetting_site_code_generator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocontextsetting',
            name='tolerance',
            field=models.FloatField(default=0.0, help_text='The radius tolerance for the spatial query'),
        ),
    ]
