# Generated by Django 4.2.16 on 2025-07-21 09:15

from django.db import migrations, connection

def create_empty_view(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
        CREATE OR REPLACE VIEW public.empty_location_site_view AS
        SELECT NULL::integer AS site_id,
               NULL::geometry(Point, 4326) AS geometry_point,
               NULL::varchar(300) AS name,
               NULL::varchar(128) AS ecosystem_type
        WHERE FALSE;
        """)

class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0457_geocontextsetting_tolerance'),
    ]

    operations = [
        migrations.RunPython(create_empty_view),
    ]
