# Generated by Django 4.2.16 on 2025-08-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0457_layergroup'),
        ('bims', '0458_auto_20250721_0915'),
    ]

    operations = [
    ]
