# Generated by Django 4.2.16 on 2025-08-07 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0459_merge_0457_layergroup_0458_auto_20250721_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='key',
            field=models.CharField(blank=True, default='', help_text='Key is required if the source of the map is Bing, Stamen, or MapTiler.', max_length=256),
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='source_type',
            field=models.CharField(choices=[('xyz', 'XYZ'), ('bing', 'BingMaps'), ('osm', 'OSM'), ('stamen', 'Stamen'), ('map_tiler', 'MapTiler')], max_length=100),
        ),
        migrations.AlterField(
            model_name='layergroup',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-safe unique identifier (auto-fill in admin).', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='species_group',
            field=models.ForeignKey(blank=True, help_text='Informal group of closely related species', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.speciesgroup'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='species_group',
            field=models.ForeignKey(blank=True, help_text='Informal group of closely related species', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.speciesgroup'),
        ),
    ]
