# Generated by Django 4.2.16 on 2025-08-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0460_speciesgroup_alter_basemaplayer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='template',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='progress',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
