# Generated by Django 4.2.16 on 2025-08-22 14:01

import bims.models.taxon_group_citation
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0461_uploadsession_template_alter_uploadsession_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonGroupCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(help_text='Author(s), e.g. "Doe J., Smith A."', max_length=500)),
                ('citation_text', models.CharField(help_text='Citation title/text, e.g. "Ostracoda Checklist; Freshwater Animal Diversity Assessment (FADA)".', max_length=500)),
                ('year', models.PositiveSmallIntegerField(default=bims.models.taxon_group_citation.current_year, help_text='Publication year (defaults to current year).')),
                ('access_date', models.DateField(default=django.utils.timezone.now, help_text='Access date (defaults to today).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taxon_group', models.ForeignKey(help_text='Organism group this citation refers to.', on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='bims.taxongroup')),
            ],
            options={
                'verbose_name': 'Taxon Group Citation',
                'verbose_name_plural': 'Taxon Group Citations',
                'ordering': ('taxon_group__display_order', 'taxon_group__name'),
            },
        ),
    ]
