# Generated by Django 4.2.16 on 2025-08-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0462_taxongroupcitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='landing_page_occurrence_records_title',
        ),
    ]
