# Generated by Django 4.2.16 on 2025-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0464_biologicalcollectionrecord_dataset_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='collector',
            field=models.CharField(blank=True, default='', help_text='Collector name in string value, this is useful for collector values from GBIF and other third party sources', max_length=1024, verbose_name='collector or observer'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='identified_by',
            field=models.CharField(blank=True, default='', help_text='Name of the person who identified the species', max_length=512, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='samplingmethod',
            name='effort_measure',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='samplingmethod',
            name='factor_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
