# Generated by Django 4.2.16 on 2025-09-08 08:10

import django.core.validators
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0465_alter_biologicalcollectionrecord_collector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='gbif_password',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', help_text='GBIF password used for API downloads (encrypted at rest).', max_length=256)),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='gbif_username',
            field=models.CharField(blank=True, default='', help_text='GBIF username used for API downloads.', max_length=150, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username.')]),
        ),
    ]
