# Generated by Django 4.2.16 on 2025-09-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0466_sitesetting_gbif_password_sitesetting_gbif_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestsession',
            name='harvest_synonyms',
            field=models.BooleanField(default=False, help_text='When checked, synonyms for each accepted taxon will be harvested'),
        ),
    ]
