# Generated by Django 4.2.24 on 2025-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0467_harvestsession_harvest_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='harvest_synonyms',
            field=models.BooleanField(default=False, help_text='When checked, synonyms for each accepted taxon will be harvested'),
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='layer_name',
            field=models.CharField(blank=True, default='', help_text='For Stamen and WMS', max_length=100),
        ),
        migrations.AlterField(
            model_name='basemaplayer',
            name='source_type',
            field=models.CharField(choices=[('xyz', 'XYZ'), ('bing', 'BingMaps'), ('osm', 'OSM'), ('stamen', 'Stamen'), ('map_tiler', 'MapTiler'), ('wms', 'WMSTile')], max_length=100),
        ),
    ]
