# Generated by Django 4.2.24 on 2025-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0468_uploadsession_harvest_synonyms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='gbif_excluded_project_ids',
            field=models.TextField(blank=True, default='', help_text="Comma-separated GBIF projectId values to exclude for this tenant (case-insensitive). Example: 'fbis, legacy123'"),
        ),
    ]
