# Generated by Django 4.2.24 on 2025-09-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0469_sitesetting_gbif_excluded_project_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestsession',
            name='since_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harvestsession',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='harvestsession',
            name='until_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HarvestSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom (cron)')], default='DAILY', max_length=10)),
                ('run_at', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=9)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('harvest_synonyms_default', models.BooleanField(default=False)),
                ('last_harvest_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boundary_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.boundary')),
                ('module_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_schedule', to='bims.taxongroup')),
            ],
        ),
        migrations.AddField(
            model_name='harvestsession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='bims.harvestschedule'),
        ),
    ]
