# Generated by Django 4.2.24 on 2025-09-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0470_harvestsession_since_time_harvestsession_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestschedule',
            name='is_fetching_species',
            field=models.BooleanField(default=False, help_text='Harvest species'),
        ),
        migrations.AlterField(
            model_name='harvestschedule',
            name='harvest_synonyms_default',
            field=models.BooleanField(default=False, help_text='Harvest synonyms'),
        ),
    ]
