# Generated by Django 4.2.24 on 2025-10-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0455_sitesetting_is_public_taxa'),
        ('bims', '0472_alter_dataset_name_and_more'),
    ]

    operations = [
    ]
