# Generated by Django 4.2.24 on 2025-10-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0472_alter_dataset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceUploadTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Occurrence data upload template file.', upload_to='occurrence_templates/')),
                ('label', models.CharField(blank=True, help_text='Optional display name (e.g. “Standard”, “With traits”).', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxon_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_upload_templates', to='bims.taxongroup')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
