# Generated by Django 4.2.24 on 2025-10-20 16:25

import bims.models.upload_request
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bims', '0472_alter_dataset_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('upload_type', models.CharField(choices=[('occurrence', 'Occurrence Data'), ('spatial', 'Spatial Layer')], max_length=20)),
                ('upload_file', models.FileField(upload_to=bims.models.upload_request.upload_path)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('github_issue_number', models.IntegerField(blank=True, null=True)),
                ('github_issue_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('ticketed', 'Ticket Created'), ('error', 'Error')], default='submitted', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='CSVDocument',
        ),
    ]
