# Generated by Django 4.2.24 on 2025-10-21 13:11

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0473_uploadrequest_delete_csvdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='github_app_id',
            field=models.CharField(blank=True, default='', help_text='GitHub App ID (integration ID) as shown on the GitHub App settings page.', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='github_private_key',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, default='', help_text='Private key (PEM) for your GitHub App. Paste the FULL key including the "-----BEGIN PRIVATE KEY-----" / "-----END PRIVATE KEY-----" lines. If stored on one line, you may use \\n for newlines.')),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='github_upload_assignees',
            field=models.CharField(blank=True, default='', help_text='Comma-separated GitHub usernames to assign to newly created issues. Assignees must have access to the repository.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='occurrence_upload_guidelines',
            field=models.FileField(blank=True, help_text='Guidelines document for uploading occurrence data (e.g. PDF/DOCX).', null=True, upload_to=''),
        ),
    ]
