# Generated by Django 4.2.24 on 2025-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0473_merge_20251016_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
