# Generated by Django 4.2.24 on 2025-10-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0474_sitesetting_github_app_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
