# Generated by Django 4.2.24 on 2025-10-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0473_occurrenceuploadtemplate'),
        ('bims', '0475_uploadrequest_title'),
    ]

    operations = [
    ]
