# Generated by Django 4.2.24 on 2025-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0476_merge_20251024_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_key',
            field=models.CharField(blank=True, default='', help_text='Google Analytics Measurement ID or API key.', max_length=255),
        ),
    ]
