# Generated by Django 4.2.25 on 2025-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0477_sitesetting_google_analytics_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='fada_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='FADA ID'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='fada_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FADA ID'),
        ),
    ]
