# Generated by Django 4.2.25 on 2025-11-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0478_alter_taxonomy_fada_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertaintyHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certainty hierarchy',
                'verbose_name_plural': 'Certainty hierarchy',
                'ordering': ['order'],
            },
        ),
    ]
