# Generated by Django 4.2.25 on 2025-11-03 16:28

from django.db import migrations, models

HIERARCHY_OF_CERTAINTY = [
    "High",
    "Herbarium verified",
    "Expert verified",
    "Photo ID",
    "Medium",
    "Unverified",
    "Low",
    "Misidentification",
    "Unknown",
]


def create_certainty_hierarchy(apps, schema_editor):
    CertaintyHierarchy = apps.get_model('bims', 'CertaintyHierarchy')
    if CertaintyHierarchy.objects.exists():
        return
    for idx, name in enumerate(HIERARCHY_OF_CERTAINTY):
        CertaintyHierarchy.objects.create(name=name, order=idx)


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0479_certaintyhierarchy'),
    ]

    operations = [
        migrations.RunPython(create_certainty_hierarchy, migrations.RunPython.noop),
    ]
