# Generated by Django 4.2.25 on 2025-11-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0480_auto_20251103_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomy',
            name='scientific_name',
            field=models.CharField(max_length=512, verbose_name='Scientific Name'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='scientific_name',
            field=models.CharField(max_length=512, verbose_name='Scientific Name'),
        ),
    ]
