# Generated by Django 4.2.25 on 2025-11-13 14:04

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bims', '0481_alter_taxonomy_scientific_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxontag',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional description for this taxonomy tag.'),
        ),
        migrations.CreateModel(
            name='TaxonTaggedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='bims.taxontag')),
            ],
            options={
                'verbose_name': 'Taxon Tagged Item',
                'verbose_name_plural': 'Taxon Tagged Items',
            },
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='bims.TaxonTaggedItem', to='bims.TaxonTag', verbose_name='Tags'),
        ),
    ]
