# Generated by Django 4.2.25 on 2025-11-13 14:07

from django.db import migrations


def forwards(apps, schema_editor):
    Tag = apps.get_model('taggit', 'Tag')
    TaggedItem = apps.get_model('taggit', 'TaggedItem')
    TaxonTag = apps.get_model('bims', 'TaxonTag')
    TaxonTaggedItem = apps.get_model('bims', 'TaxonTaggedItem')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # ContentType for Taxonomy model
    try:
        taxonomy_ct = ContentType.objects.get(
            app_label='bims',
            model='taxonomy',
        )
    except ContentType.DoesNotExist:
        return

    # 1) Copy Tag -> TaxonTag (if not exists yet)
    tag_to_taxontag = {}
    for tag in Tag.objects.all():
        taxon_tag, _ = TaxonTag.objects.get_or_create(
            name=tag.name,
            defaults={
                'slug': tag.slug,
            },
        )
        tag_to_taxontag[tag.id] = taxon_tag.id

    # 2) Copy TaggedItem (only for Taxonomy) -> TaxonTaggedItem
    for item in TaggedItem.objects.filter(content_type=taxonomy_ct):
        taxon_tag_id = tag_to_taxontag.get(item.tag_id)
        if not taxon_tag_id:
            continue

        TaxonTaggedItem.objects.get_or_create(
            content_type=item.content_type,
            object_id=item.object_id,
            tag_id=taxon_tag_id,
        )


def backwards(apps, schema_editor):
	pass


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0482_taxontag_description_taxontaggeditem_and_more'),
    ]

    operations = [
		migrations.RunPython(forwards, backwards),
    ]
