# Generated by Django 4.2.25 on 2025-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0482_harvestsession_additional_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsite',
            name='coordinate_precision',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A decimal representation of the precision of the coordinates. Examples: 0.00001 (GPS limit), 0.000278 (nearest second), 0.01667 (nearest minute), 1.0 (nearest degree)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='coordinate_uncertainty_in_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The horizontal distance (in meters) from the given coordinates describing the smallest circle containing the whole of the Location. Examples: 30 (GPS after 2000-05-01), 100 (GPS before 2000-05-01)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='locationsite',
            name='harvested_from_gbif',
            field=models.BooleanField(default=False, help_text='Indicates whether this location site was created from GBIF harvesting'),
        ),
    ]
