# Generated by Django 4.2.25 on 2025-11-28 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0483_add_gbif_coordinate_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestschedule',
            name='module_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_schedules', to='bims.taxongroup'),
        ),
    ]
