# Generated by Django 4.2.25 on 2025-11-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0483_auto_20251113_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggroup',
            name='taxon_tags',
            field=models.ManyToManyField(
                to='bims.TaxonTag',
                related_name='tag_groups_temp',
                blank=True,
            ),
        ),
    ]

