# Generated by Django 4.2.25 on 2025-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0484_allow_multiple_harvest_schedules_per_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_climate_data',
            field=models.BooleanField(default=False, help_text='Enable or disable Climate data'),
        ),
    ]
