# Generated by Django 4.2.25 on 2025-11-13 14:21

from django.db import migrations


def forwards(apps, schema_editor):
    TagGroup = apps.get_model('bims', 'TagGroup')
    Tag = apps.get_model('taggit', 'Tag')
    TaxonTag = apps.get_model('bims', 'TaxonTag')

    for tg in TagGroup.objects.all().prefetch_related('tags'):
        for old_tag in tg.tags.all():  # old Taggit Tag
            # Reuse existing TaxonTag or create a new one
            taxon_tag, _ = TaxonTag.objects.get_or_create(
                name=old_tag.name,
                defaults={
                    'slug': old_tag.slug,
                },
            )
            tg.taxon_tags.add(taxon_tag)


def backwards(apps, schema_editor):
    # usually no-op; you can leave it empty if you don't need rollback
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0484_auto_20251113_1418'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
