# Generated by Django 4.2.25 on 2025-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0485_auto_20251113_1421'),
    ]

    operations = [
       	migrations.RemoveField(
            model_name='taggroup',
            name='tags',
        ),
        migrations.RenameField(
            model_name='taggroup',
            old_name='taxon_tags',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='taggroup',
            name='tags',
            field=models.ManyToManyField(
                to='bims.TaxonTag',
                related_name='tag_groups',
                blank=True,
            ),
        ),
    ]
