# Generated by Claude Code on 2025-12-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0485_sitesetting_enable_climate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcereference',
            name='metadata_file',
            field=models.FileField(
                blank=True,
                help_text='Upload metadata documentation (PDF or Word document) describing this source reference',
                null=True,
                upload_to='source_reference_metadata/'
            ),
        ),
    ]
