# Generated by Django 4.2.25 on 2025-11-13 14:51

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0486_auto_20251113_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggroup',
            name='tags',
            field=models.ManyToManyField(related_name='tag_groups', to='bims.taxontag'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='bims.TaxonTaggedItem', to='bims.TaxonTag', verbose_name='Tags'),
        ),
    ]
