# Generated by Django migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0491_uploadtype_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestschedule',
            name='parent_species',
            field=models.ForeignKey(
                blank=True,
                help_text="Override GBIF parent species for this schedule. If not set, uses the module group default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='harvest_schedules',
                to='bims.taxonomy',
            ),
        ),
        migrations.AddField(
            model_name='harvestsession',
            name='parent_species',
            field=models.ForeignKey(
                blank=True,
                help_text='GBIF parent species used for this harvest session',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='harvest_sessions',
                to='bims.taxonomy',
            ),
        ),
    ]
