# Generated by Django 4.2.26 on 2026-01-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0492_harvestschedule_harvestsession_parent_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='GbifPublishConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for this configuration (e.g., 'Production', 'Test')", max_length=255)),
                ('gbif_api_url', models.URLField(default='https://api.gbif-uat.org/v1', help_text='GBIF API URL (e.g., https://api.gbif.org/v1 for production, https://api.gbif-uat.org/v1 for UAT)')),
                ('license_url', models.URLField(default='https://creativecommons.org/publicdomain/zero/1.0/legalcode', help_text='License URL for the dataset')),
                ('export_base_url', models.URLField(blank=True, help_text='Base URL where DwC-A exports will be accessible (e.g., https://yoursite.com)')),
                ('username', models.CharField(help_text='GBIF username for authentication', max_length=255)),
                ('password', models.CharField(help_text='GBIF password for authentication', max_length=255)),
                ('publishing_org_key', models.CharField(help_text='GBIF Publishing Organization Key (UUID)', max_length=64)),
                ('installation_key', models.CharField(help_text='GBIF Installation Key (UUID)', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GBIF Publish Config',
                'verbose_name_plural': 'GBIF Publish Configs',
            },
        ),
        migrations.CreateModel(
            name='GbifPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom (cron)')], default='DAILY', max_length=10)),
                ('run_at', models.TimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=9)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cron_expression', models.CharField(blank=True, default='', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('last_publish', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gbif_config', models.ForeignKey(help_text='GBIF configuration to use for publishing', on_delete=django.db.models.deletion.PROTECT, related_name='publish_schedules', to='bims.gbifpublishconfig')),
                ('module_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gbif_publish_schedules', to='bims.taxongroup')),
            ],
            options={
                'verbose_name': 'GBIF Publish Schedule',
                'verbose_name_plural': 'GBIF Publish Schedules',
            },
        ),
    ]
