# Generated by Django 4.2.26 on 2026-01-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0493_gbifpublishconfig_gbifpublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gbifpublishconfig',
            name='gbif_api_url',
            field=models.URLField(default='https://api.gbif-uat.org/v1', help_text='GBIF API URL: https://api.gbif.org/v1 (production), https://api.gbif-uat.org/v1 (UAT), https://api.gbif-test.org/v1 (test). Ensure credentials match the environment.'),
        ),
        migrations.CreateModel(
            name='GbifPublishSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('no_records', 'No Records')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('dataset_key', models.CharField(blank=True, help_text='GBIF dataset UUID returned after successful registration', max_length=64)),
                ('records_published', models.PositiveIntegerField(default=0, help_text='Number of records published in this session')),
                ('archive_url', models.URLField(blank=True, help_text='URL to the DwC-A archive file')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the publish failed')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='gbif-publish-session-log/')),
                ('gbif_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='bims.gbifpublishconfig')),
                ('module_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gbif_publish_sessions', to='bims.taxongroup')),
                ('schedule', models.ForeignKey(help_text='The publish schedule that triggered this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bims.gbifpublish')),
            ],
            options={
                'verbose_name': 'GBIF Publish Session',
                'verbose_name_plural': 'GBIF Publish Sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
