# Generated by Django 4.2.26 on 2026-02-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('bims', '0494_alter_gbifpublishconfig_gbif_api_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GbifPublishConfigProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GBIF Config',
                'verbose_name_plural': 'GBIF Configs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bims.gbifpublishconfig',),
        ),
        migrations.CreateModel(
            name='GbifPublishProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GBIF Publish Schedule',
                'verbose_name_plural': 'GBIF Publish Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bims.gbifpublish',),
        ),
        migrations.CreateModel(
            name='GbifPublishSessionProxy',
            fields=[
            ],
            options={
                'verbose_name': 'GBIF Publish Session',
                'verbose_name_plural': 'GBIF Publish Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bims.gbifpublishsession',),
        ),
        migrations.CreateModel(
            name='TaxonTagDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description_detail', to='taggit.tag')),
            ],
            options={
                'verbose_name': 'Tag Description',
                'verbose_name_plural': 'Tag Descriptions',
            },
        ),
    ]
