# Generated by Django 4.2.26 on 2026-02-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0495_gbifpublishconfigproxy_gbifpublishproxy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='invasion_label',
            field=models.CharField(blank=True, default='Invasion', help_text="Label for the invasion column in taxa checklist downloads. Default is 'Invasion'. SANParks uses 'National NEMBA Status'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='searchprocess',
            name='category',
            field=models.CharField(choices=[('cluster_generation', 'Cluster Generation'), ('search_results', 'Search Results'), ('sites_summary', 'Site Summary'), ('taxon_summary', 'Taxon Summary'), ('spatial_dashboard_module_totals', 'Spatial Dashboard Module Totals'), ('spatial_dashboard_cons_status', 'Spatial Dashboard Conservation Status'), ('spatial_dashboard_rli', 'Spatial Dashboard Red List Index'), ('spatial_dashboard_map', 'Spatial Dashboard Map'), ('spatial_dashboard_summary', 'Spatial Dashboard Summary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='category',
            field=models.CharField(blank=True, choices=[('taxa', 'Taxa'), ('taxa_validation', 'Taxa Validation'), ('collections', 'Collections'), ('water_temperature', 'Water Temperature'), ('physico_chemical', 'Physico Chemical')], default='', max_length=50),
        ),
    ]
