# Generated by Django 6.0.2 on 2026-02-25 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0496_taxonorigin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gbifpublishconfig',
            name='installation_key',
            field=models.CharField(blank=True, default='', help_text='GBIF Installation Key (UUID)', max_length=64),
        ),
        migrations.AlterField(
            model_name='searchprocess',
            name='category',
            field=models.CharField(choices=[('cluster_generation', 'Cluster Generation'), ('search_results', 'Search Results'), ('sites_summary', 'Site Summary'), ('taxon_summary', 'Taxon Summary'), ('spatial_dashboard_module_totals', 'Spatial Dashboard Module Totals'), ('spatial_dashboard_cons_status', 'Spatial Dashboard Conservation Status'), ('spatial_dashboard_rli', 'Spatial Dashboard Red List Index'), ('spatial_dashboard_map', 'Spatial Dashboard Map'), ('spatial_dashboard_summary', 'Spatial Dashboard Summary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='category',
            field=models.CharField(blank=True, choices=[('taxa', 'Taxa'), ('taxa_validation', 'Taxa Validation'), ('collections', 'Collections'), ('water_temperature', 'Water Temperature'), ('physico_chemical', 'Physico Chemical')], default='', max_length=50),
        ),
    ]
