# Generated by Django 6.0.2 on 2026-03-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0500_sitesetting_allow_public_taxa_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadrequest',
            name='data_licence',
        ),
        migrations.AlterField(
            model_name='searchprocess',
            name='category',
            field=models.CharField(choices=[('cluster_generation', 'Cluster Generation'), ('search_results', 'Search Results'), ('sites_summary', 'Site Summary'), ('taxon_summary', 'Taxon Summary'), ('spatial_dashboard_module_totals', 'Spatial Dashboard Module Totals'), ('spatial_dashboard_cons_status', 'Spatial Dashboard Conservation Status'), ('spatial_dashboard_rli', 'Spatial Dashboard Red List Index'), ('spatial_dashboard_map', 'Spatial Dashboard Map'), ('spatial_dashboard_summary', 'Spatial Dashboard Summary'), ('spatial_dashboard_species_download', 'Spatial Dashboard Species Download')], max_length=50),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.licence'),
        ),
        migrations.AddField(
            model_name='uploadrequest',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.licence'),
        ),
    ]
