# Generated by Django 6.0.2 on 2026-03-20 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bims", "0500_sitesetting_allow_public_taxa_view"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taxongroup",
            name="approved_at",
            field=models.DateTimeField(blank=True, help_text="When this taxon group was approved", null=True),
        ),
        migrations.AddField(
            model_name="taxongroup",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this taxon group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_taxon_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taxongroup",
            name="is_approved",
            field=models.BooleanField(default=True, help_text="Whether this taxon group has been approved for use"),
        ),
        migrations.AddField(
            model_name="taxongroup",
            name="proposed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who proposed this taxon group",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_taxon_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="taxongroup",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Reason for rejection if not approved", null=True),
        ),
        migrations.AlterField(
            model_name="searchprocess",
            name="category",
            field=models.CharField(
                choices=[
                    ("cluster_generation", "Cluster Generation"),
                    ("search_results", "Search Results"),
                    ("sites_summary", "Site Summary"),
                    ("taxon_summary", "Taxon Summary"),
                    ("spatial_dashboard_module_totals", "Spatial Dashboard Module Totals"),
                    ("spatial_dashboard_cons_status", "Spatial Dashboard Conservation Status"),
                    ("spatial_dashboard_rli", "Spatial Dashboard Red List Index"),
                    ("spatial_dashboard_map", "Spatial Dashboard Map"),
                    ("spatial_dashboard_summary", "Spatial Dashboard Summary"),
                    ("spatial_dashboard_species_download", "Spatial Dashboard Species Download"),
                ],
                max_length=50,
            ),
        ),
    ]
