# Generated by Django 6.0.2 on 2026-03-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0501_licence_remove_uploadrequest_data_licence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='download_params',
            field=models.JSONField(blank=True, help_text='Serialised request parameters used to start the download', null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='download_path',
            field=models.CharField(blank=True, help_text='Filesystem path of the in-progress download file', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last progress update', null=True),
        ),
    ]
