# Generated by Django 6.0.2 on 2026-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0502_downloadrequest_download_params_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='max_download_records',
            field=models.IntegerField(default=50000, help_text='Maximum number of occurrence records that can be downloaded without staff approval. Set to 0 for no limit. Requests exceeding this number always require explicit staff approval even if automatic approval is enabled.'),
        ),
    ]
