# Generated by Django 6.0.2 on 2026-03-27 11:15

import bims.models.download_request
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0503_sitesetting_max_download_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gbifpublish',
            name='module_group',
        ),
        migrations.RemoveField(
            model_name='gbifpublishsession',
            name='module_group',
        ),
        migrations.AddField(
            model_name='gbifpublish',
            name='source_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gbif_publish_schedules', to='bims.sourcereference'),
        ),
        migrations.AddField(
            model_name='gbifpublishsession',
            name='source_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gbif_publish_sessions', to='bims.sourcereference'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_category',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_file',
            field=models.FileField(blank=True, help_text='Only csv file', max_length=300, null=True, upload_to='request-files/', validators=[bims.models.download_request.validate_file_extension]),
        ),
    ]
