# Generated by Django 6.0.2 on 2026-03-24 09:59

import bims.models.download_request
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0503_sitesetting_max_download_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='subgenus',
            field=models.ForeignKey(blank=True, limit_choices_to={'rank': 'Sub Genus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subgenus', to='bims.taxonomy'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='subgenus',
            field=models.ForeignKey(blank=True, limit_choices_to={'rank': 'Sub Genus'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subgenus', to='bims.taxonomyupdateproposal'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_category',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_file',
            field=models.FileField(blank=True, help_text='Only csv file', max_length=300, null=True, upload_to='request-files/', validators=[bims.models.download_request.validate_file_extension]),
        ),
    ]
