# Generated by Django 6.0.2 on 2026-03-30 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0504_remove_gbifpublish_module_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GbifPublishContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_name_given', models.CharField(blank=True, default='', help_text="First name. Leave blank to use the linked user's first_name.", max_length=255, verbose_name='Given name')),
                ('individual_name_sur', models.CharField(blank=True, default='', help_text="Last name / surname. Leave blank to use the linked user's last_name.", max_length=255, verbose_name='Surname')),
                ('organization_name', models.CharField(blank=True, default='', help_text="Full name of the organisation. Leave blank to use the linked user's organisation.", max_length=512, verbose_name='Organisation name')),
                ('position_name', models.CharField(blank=True, default='', help_text="Title or position associated with this contact. Leave blank to use the linked user's role (bims_profile.role).", max_length=255, verbose_name='Position / title')),
                ('delivery_point', models.CharField(blank=True, default='', help_text='Street address or PO Box.', max_length=512, verbose_name='Delivery point (street address)')),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('country', models.CharField(blank=True, default='', help_text='Country name or ISO 3166-1 alpha-2 code.', max_length=255)),
                ('phone', models.CharField(blank=True, default='', help_text='Telephone number including country code, e.g. +27 21 123 4567.', max_length=64)),
                ('electronic_mail_address', models.EmailField(blank=True, default='', help_text="Contact email address. Leave blank to use the linked user's email.", max_length=254, verbose_name='Email address')),
                ('online_url', models.URLField(blank=True, default='', help_text='Link to associated online information, usually a web site.', verbose_name='Online URL')),
                ('gbif_config', models.ForeignKey(help_text='The GBIF config these contacts belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='bims.gbifpublishconfig')),
                ('user', models.ForeignKey(blank=True, help_text='Optional: link a user to auto-populate blank fields (name, email, organisation, position).', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GBIF Publish Contact',
                'verbose_name_plural': 'GBIF Publish Contacts',
                'ordering': ['id'],
            },
        ),
    ]
