# Generated by Django 6.0.2 on 2026-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0508_sitesetting_download_request_expiry_months'),
        ('td_biblio', '0008_alter_entry_crossref'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcereference',
            name='source_authors',
            field=models.ManyToManyField(blank=True, help_text='Author(s) of this source reference', related_name='source_references', to='td_biblio.author'),
        ),
        migrations.AddField(
            model_name='sourcereference',
            name='source_date',
            field=models.DateField(blank=True, help_text='Date of this source reference', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_code_generator',
            field=models.CharField(blank=True, choices=[('bims', 'BIMS (2 Site Name + 2 Site Description + Site count)'), ('fbis', 'FBIS (2 Secondary catchment + 4 River + Site count)'), ('fbis_africa', 'FBIS Africa (3 × ISO Country Code + base-36 Site count)'), ('rbis', 'RBIS (Catchment + Province ID + District ID + Site count)'), ('sanparks', 'SANPARKS (1st three park name + site count)'), ('kafue', 'KAFUE (1st five district name + site count)'), ('fips', 'FIPS (GBIF continent code + basin name + site count)')], default='bims', help_text='How site code generated', max_length=50),
        ),
    ]
