# Generated by Django 6.0.2 on 2026-04-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0509_sourcereference_source_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vernacularname',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vernacularname',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
