# Generated by Django 6.0.2 on 2026-04-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0510_alter_vernacularname_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='invasion_label',
            field=models.CharField(blank=True, default='Invasion', help_text="Label for the invasion column in taxa checklist downloads. Default is 'Invasion'. SANParks uses 'National NEMBA Status'.", max_length=100),
        ),
    ]
