# Generated by Django 6.0.2 on 2026-04-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0504_taxonomy_subgenus_taxonomyupdateproposal_subgenus_and_more'),
        ('bims', '0511_sitesetting_invasion_label'),
    ]

    operations = [
    ]
