# Generated by Django 6.0.2 on 2026-04-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0513_taxonomyupdateproposal_subgenus'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='coordinate_precision',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='A decimal representation of the precision of the coordinates. Examples: 0.00001 (GPS limit), 0.000278 (nearest second), 0.01667 (nearest minute), 1.0 (nearest degree)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='biologicalcollectionrecord',
            name='coordinate_uncertainty_in_meters',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The horizontal distance (in meters) from the given coordinates describing the smallest circle containing the whole of the Location. Examples: 30 (GPS after 2000-05-01), 100 (GPS before 2000-05-01)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='subgenus',
            field=models.ForeignKey(blank=True, limit_choices_to={'rank': 'SUBGENUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_subgenus', to='bims.taxonomy'),
        ),
    ]
