# Generated by Django 6.0.2 on 2026-05-20 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0524_taxonomy_sanbi_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this metagroup.')),
                ('gbif_key', models.CharField(blank=True, help_text='Corresponding GBIF broader organism group key', max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Representative icon or logo for this metagroup.', null=True, upload_to='metagroup_logo')),
                ('display_order', models.IntegerField(blank=True, help_text='Controls the display order on the landing page widget.', null=True)),
            ],
            options={
                'verbose_name': 'Meta Group',
                'verbose_name_plural': 'Meta Groups',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='show_metagroup_on_landing',
            field=models.BooleanField(default=False, help_text='Display the metagroup (broader organism group) widget on the landing page.'),
        ),
        migrations.AlterField(
            model_name='harvestsession',
            name='category',
            field=models.CharField(blank=True, choices=[('gbif', 'GBIF'), ('worms', 'WoRMS'), ('taxonworks', 'TaxonWorks')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='searchprocess',
            name='category',
            field=models.CharField(choices=[('cluster_generation', 'Cluster Generation'), ('search_results', 'Search Results'), ('sites_summary', 'Site Summary'), ('taxon_summary', 'Taxon Summary'), ('spatial_dashboard_module_totals', 'Spatial Dashboard Module Totals'), ('spatial_dashboard_cons_status', 'Spatial Dashboard Conservation Status'), ('spatial_dashboard_rli', 'Spatial Dashboard Red List Index'), ('spatial_dashboard_map', 'Spatial Dashboard Map'), ('spatial_dashboard_summary', 'Spatial Dashboard Summary'), ('spatial_dashboard_species_download', 'Spatial Dashboard Species Download'), ('spatial_dashboard_national_rli', 'Spatial Dashboard National RLI')], max_length=50),
        ),
        migrations.AddField(
            model_name='taxongroup',
            name='meta_group',
            field=models.ForeignKey(blank=True, help_text='Broader organism group (metagroup) this module belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxon_groups', to='bims.metagroup'),
        ),
    ]
