# Generated by Django 6.0.2 on 2026-05-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0524_taxonomy_sanbi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='is_readonly',
            field=models.BooleanField(default=False, help_text='When enabled, species in this taxon group cannot be edited locally. The group is managed by harvesting from an upstream BIMS instance.'),
        ),
        migrations.AddField(
            model_name='taxongroup',
            name='upstream_id',
            field=models.CharField(blank=True, default='', help_text='ID of the taxon group on the upstream BIMS instance.', max_length=100),
        ),
        migrations.AddField(
            model_name='taxongroup',
            name='upstream_url',
            field=models.URLField(blank=True, default='', help_text='Base URL of the upstream BIMS instance this group is harvested from.', max_length=500),
        ),
        migrations.AddField(
            model_name='taxongrouptaxonomy',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful harvest that touched this membership. Null means the record was never harvested (created manually or via upload).', null=True),
        ),
        migrations.AddField(
            model_name='taxongrouptaxonomy',
            name='upstream_checksum',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hex digest of the canonical upstream taxon payload at the time of last harvest. If the checksum matches on re-harvest the record is skipped, avoiding unnecessary DB writes. An empty string means no checksum has been recorded yet.', max_length=64),
        ),
        migrations.AddField(
            model_name='taxongrouptaxonomy',
            name='upstream_taxon_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID of the corresponding taxon on the upstream BIMS instance. Set during harvest; used to match taxa on re-harvest without relying solely on gbif_key or canonical name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='harvestsession',
            name='category',
            field=models.CharField(blank=True, choices=[('gbif', 'GBIF'), ('worms', 'WoRMS'), ('taxonworks', 'TaxonWorks'), ('bims', 'BIMS')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='searchprocess',
            name='category',
            field=models.CharField(choices=[('cluster_generation', 'Cluster Generation'), ('search_results', 'Search Results'), ('sites_summary', 'Site Summary'), ('taxon_summary', 'Taxon Summary'), ('spatial_dashboard_module_totals', 'Spatial Dashboard Module Totals'), ('spatial_dashboard_cons_status', 'Spatial Dashboard Conservation Status'), ('spatial_dashboard_rli', 'Spatial Dashboard Red List Index'), ('spatial_dashboard_map', 'Spatial Dashboard Map'), ('spatial_dashboard_summary', 'Spatial Dashboard Summary'), ('spatial_dashboard_species_download', 'Spatial Dashboard Species Download'), ('spatial_dashboard_national_rli', 'Spatial Dashboard National RLI')], max_length=50),
        ),
    ]
