# Generated by Django 6.0.2 on 2026-05-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0526_sitesetting_github_upload_repo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestsession',
            name='source_site',
        ),
    ]
