# Generated by Django 6.0.2 on 2026-06-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0528_gbifpublishconfig_license'),
        ('bims', '0528_metagroup_sitesetting_show_metagroup_on_landing_and_more'),
    ]

    operations = [
    ]
