# Generated by Django 6.0.2 on 2026-06-18 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0532_taxonomy_taxonworks_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistsnapshot',
            name='accepted_taxon',
            field=models.CharField(blank=True, default='', help_text='Canonical name of accepted taxon (for synonyms).', max_length=512),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of extra taxon attributes {attr_name: value}.'),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='canonical_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='cites_listing',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='common_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='conservation_status_global',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='conservation_status_national',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='endemism',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='fada_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='gbif_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='invasion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='species',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='species_group',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='subfamily',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='subgenus',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='subspecies',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='subtribe',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='tags',
            field=models.JSONField(default=dict, help_text='Snapshot of {tag_name: "Y"/"?"} for tags and biographic distributions.'),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='tribe',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='checklistsnapshot',
            name='variety',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Collector/owner'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_file',
            field=models.FileField(blank=True, help_text='Only csv file', max_length=300, null=True, upload_to='request-files/'),
        ),
        migrations.AlterField(
            model_name='geocontextsetting',
            name='tolerance',
            field=models.FloatField(default=0.0, help_text='The radius tolerance for the spatial query (in metres).'),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Collector/owner'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Collector/owner'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
