# Generated by Django 6.0.2 on 2026-06-17 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0532_taxonomy_taxonworks_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='source_references',
            field=models.ManyToManyField(blank=True, help_text='Additional source references for this taxon.', related_name='taxonomy_source_references', to='bims.sourcereference', verbose_name='External Source References'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='source_references',
            field=models.ManyToManyField(blank=True, related_name='taxonomy_proposal_source_references', to='bims.sourcereference', verbose_name='External Source References'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Collector/owner'),
        ),
        migrations.AlterField(
            model_name='downloadrequest',
            name='request_file',
            field=models.FileField(blank=True, help_text='Only csv file', max_length=300, null=True, upload_to='request-files/'),
        ),
        migrations.AlterField(
            model_name='geocontextsetting',
            name='tolerance',
            field=models.FloatField(default=0.0, help_text='The radius tolerance for the spatial query (in metres).'),
        ),
        migrations.AlterField(
            model_name='locationsite',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Collector/owner'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Collector/owner'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='collector_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_collector_user', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
    ]
