# Generated by Django 6.0.2 on 2026-07-06 12:53

import bims.models.site_setting
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0538_checklistversioncontributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='gbif_harvest_exclusion_rules',
            field=models.JSONField(blank=True, default=bims.models.site_setting.gbif_default_exclusion_rules, help_text='JSON list of rules applied during GBIF harvesting. Each rule is an object with \'field\' (DwC field name), \'condition\' (not_empty | equals | contains | greater_than | less_than), optional \'value\', and optional \'description\'. A record matching ANY rule is skipped. Example: [{"field": "informationWithheld", "condition": "not_empty", "description": "Skip obscured/withheld coordinates"}]', null=True),
        ),
        migrations.AlterField(
            model_name='biologicalcollectionrecord',
            name='institution_id',
            field=models.CharField(blank=True, default='', help_text='An identifier for the institution having custody of the object(s) or information referred to in the record.', max_length=200, verbose_name='Custodian'),
        ),
        migrations.AlterUniqueTogether(
            name='customtaggedtaxonomy',
            unique_together={('content_object', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='customtaggedupdatetaxonomy',
            unique_together={('content_object', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='taxontag',
            unique_together={('name', 'doubtful')},
        ),
    ]
