# Generated by Django 6.0.2 on 2026-07-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0538_checklistversioncontributor'),
        ('bims', '0539_opensearchreindexrun_opensearchreindextenantstatus'),
    ]

    operations = [
    ]
