# Generated by Codex on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0539_sitesetting_gbif_harvest_exclusion_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicalrecord',
            name='custodian',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    'An identifier for the institution having custody of the '
                    'information referred to in the record.'
                ),
                max_length=200,
                verbose_name='Custodian',
            ),
        ),
    ]
