# Generated by Django 6.0.2 on 2026-07-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0542_sitesetting_water_temperature_upload_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='col_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Catalogue of Life ID'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='col_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Catalogue of Life ID'),
        ),
        migrations.AlterField(
            model_name='gbifpublishcontact',
            name='electronic_mail_address',
            field=models.EmailField(blank=True, default='', help_text='Contact email address. Auto-populated from the linked user when the contact is first created. Clear this field to remove the email from GBIF.', max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='harvestsession',
            name='category',
            field=models.CharField(blank=True, choices=[('gbif', 'GBIF'), ('worms', 'WoRMS'), ('taxonworks', 'TaxonWorks'), ('bims', 'BIMS'), ('iucn', 'IUCN')], default='', max_length=50),
        ),
    ]
