# Generated by Django 6.0.2 on 2026-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0543_taxonomy_col_id_taxonomyupdateproposal_col_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxongroup',
            name='taxonworks_base_url',
            field=models.URLField(blank=True, default='', help_text='Base URL of the TaxonWorks instance (e.g. https://plecoptera.speciesfile.org). Used to construct OTU links for taxa in this group.', max_length=500),
        ),
        migrations.AddField(
            model_name='taxonomy',
            name='taxonworks_otu_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='TaxonWorks OTU ID'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='taxonworks_otu_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='TaxonWorks OTU ID'),
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='rank',
            field=models.CharField(blank=True, choices=[('DOMAIN', 'Domain'), ('KINGDOM', 'Kingdom'), ('SUBKINGDOM', 'Sub Kingdom'), ('PHYLUM', 'Phylum'), ('SUBPHYLUM', 'SubPhylum'), ('INFRAPHYLUM', 'Infra Phylum'), ('MEGACLASS', 'Mega Class'), ('GIGACLASS', 'Giga Class'), ('SUPERCLASS', 'Super Class'), ('CLASS', 'Class'), ('SUBCLASS', 'Sub Class'), ('INFRACLASS', 'Infra Class'), ('SUPERORDER', 'Super Order'), ('ORDER', 'Order'), ('SUBORDER', 'Sub Order'), ('INFRAORDER', 'Infra Order'), ('PARVORDER', 'Parv Order'), ('SUPERFAMILY', 'Super Family'), ('FAMILY', 'Family'), ('SUBFAMILY', 'Sub Family'), ('TRIBE', 'Tribe'), ('SUBTRIBE', 'Sub Tribe'), ('GENUS', 'Genus'), ('SUBGENUS', 'Sub Genus'), ('SPECIES', 'Species'), ('SUBSPECIES', 'Sub Species'), ('VARIETY', 'Variety'), ('FORMA', 'Forma')], max_length=50, verbose_name='Taxonomic Rank'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='rank',
            field=models.CharField(blank=True, choices=[('DOMAIN', 'Domain'), ('KINGDOM', 'Kingdom'), ('SUBKINGDOM', 'Sub Kingdom'), ('PHYLUM', 'Phylum'), ('SUBPHYLUM', 'SubPhylum'), ('INFRAPHYLUM', 'Infra Phylum'), ('MEGACLASS', 'Mega Class'), ('GIGACLASS', 'Giga Class'), ('SUPERCLASS', 'Super Class'), ('CLASS', 'Class'), ('SUBCLASS', 'Sub Class'), ('INFRACLASS', 'Infra Class'), ('SUPERORDER', 'Super Order'), ('ORDER', 'Order'), ('SUBORDER', 'Sub Order'), ('INFRAORDER', 'Infra Order'), ('PARVORDER', 'Parv Order'), ('SUPERFAMILY', 'Super Family'), ('FAMILY', 'Family'), ('SUBFAMILY', 'Sub Family'), ('TRIBE', 'Tribe'), ('SUBTRIBE', 'Sub Tribe'), ('GENUS', 'Genus'), ('SUBGENUS', 'Sub Genus'), ('SPECIES', 'Species'), ('SUBSPECIES', 'Sub Species'), ('VARIETY', 'Variety'), ('FORMA', 'Forma')], max_length=50, verbose_name='Taxonomic Rank'),
        ),
    ]
