# Generated by Django 6.0.2 on 2026-08-20 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0546_sitesetting_physico_chemical_upload_template'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpstreamDeletionCheckResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255, verbose_name='Object ID')),
                ('name', models.CharField(blank=True, default='', max_length=512)),
                ('upstream_id', models.CharField(blank=True, default='', max_length=100)),
                ('detail', models.TextField(blank=True, default='')),
                ('removed', models.BooleanField(default=False)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DataUpstreamDeletionCheckSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('taxa', 'Taxa'), ('occurrences', 'Occurrence Records')], default='taxa', max_length=20)),
                ('auto_remove', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('found_count', models.IntegerField(default=0)),
                ('removed_count', models.IntegerField(default=0)),
                ('canceled', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_update', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstream_deletion_check_sessions', to=settings.AUTH_USER_MODEL)),
                ('taxon_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims.taxongroup')),
            ],
        ),
        migrations.DeleteModel(
            name='GbifPublishConfigProxy',
        ),
        migrations.DeleteModel(
            name='GbifPublishProxy',
        ),
        migrations.DeleteModel(
            name='GbifPublishSessionProxy',
        ),
        migrations.AlterField(
            model_name='taxonomy',
            name='taxonomic_status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('PROVISIONALLY_ACCEPTED', 'Provisionally Accepted'), ('DOUBTFUL', 'Doubtful'), ('SYNONYM', 'Synonym'), ('HETEROTYPIC_SYNONYM', 'Heterotypic Synonym'), ('HOMOTYPIC_SYNONYM', 'Homotypic Synonym'), ('PROPARTE_SYNONYM', 'Proparte Synonym'), ('MISAPPLIED', 'Misapplied')], max_length=50, verbose_name='Taxonomic Status'),
        ),
        migrations.AlterField(
            model_name='taxonomyupdateproposal',
            name='taxonomic_status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('PROVISIONALLY_ACCEPTED', 'Provisionally Accepted'), ('DOUBTFUL', 'Doubtful'), ('SYNONYM', 'Synonym'), ('HETEROTYPIC_SYNONYM', 'Heterotypic Synonym'), ('HOMOTYPIC_SYNONYM', 'Homotypic Synonym'), ('PROPARTE_SYNONYM', 'Proparte Synonym'), ('MISAPPLIED', 'Misapplied')], max_length=50, verbose_name='Taxonomic Status'),
        ),
        migrations.AddField(
            model_name='dataupstreamdeletioncheckresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='bims.dataupstreamdeletionchecksession'),
        ),
        migrations.AlterUniqueTogether(
            name='dataupstreamdeletioncheckresult',
            unique_together={('session', 'object_id')},
        ),
    ]
