# Generated by Django 6.0.4 on 2026-08-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0547_dataupstreamdeletioncheckresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='addendum',
            field=models.CharField(blank=True, choices=[('SENSU_LATO', 'sensu lato')], help_text='Nomenclatural qualifier appended to the scientific name, e.g. "sensu lato" when a species has been split into subspecies but both the species and its subspecies remain accepted taxa.', max_length=50, verbose_name='Addendum'),
        ),
        migrations.AddField(
            model_name='taxonomyupdateproposal',
            name='addendum',
            field=models.CharField(blank=True, choices=[('SENSU_LATO', 'sensu lato')], help_text='Nomenclatural qualifier appended to the scientific name, e.g. "sensu lato" when a species has been split into subspecies but both the species and its subspecies remain accepted taxa.', max_length=50, verbose_name='Addendum'),
        ),
    ]
