# Generated by Django 6.0.4 on 2026-09-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0548_add_addendum_to_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='enable_checklist_versioning',
            field=models.BooleanField(default=True, help_text='Enable or disable the Taxonomic Checklist Versioning feature'),
        ),
    ]
