# Generated by Django 6.0.4 on 2026-09-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims', '0549_add_enable_checklist_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='conservation_status_chart_use_taxon_count',
            field=models.BooleanField(default=False, help_text='Base the conservation status chart on the front page on the number of taxa instead of the number of occurrence records.'),
        ),
    ]
