# Generated by Django 2.2.16 on 2022-03-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20201107_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='abstract_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='constraints_other_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='data_quality_statement_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='purpose_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='supplemental_information_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title_en',
        ),
    ]
