# Generated by Django 2.2.12 on 2020-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.URLField(help_text='This will appear as a tooltip', max_length=128)),
                ('logo', models.ImageField(upload_to='partner_logo')),
                ('link', models.URLField(blank=True, help_text='The url link for this partner, will make the logo clickable', null=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='carouselheader',
            options={'verbose_name_plural': 'Carousel Headers'},
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners',
            field=models.ManyToManyField(blank=True, help_text='List of partners that will appear on the landing page', null=True, to='bims_theme.Partner'),
        ),
    ]
