# Generated by Django 2.2.12 on 2020-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0002_auto_20200903_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(help_text='This will appear as a tooltip', max_length=128),
        ),
    ]
