# Generated by Django 2.2.12 on 2020-09-03 07:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0003_auto_20200903_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselheader',
            name='background_overlay_opacity',
            field=models.PositiveIntegerField(default=0, help_text='Opacity of the background overlay, in percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
