# Generated by Django 2.2.12 on 2020-09-09 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0004_auto_20200903_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselheader',
            options={'ordering': ['order'], 'verbose_name_plural': 'Carousel Headers'},
        ),
    ]
