# Generated by Django 2.2.12 on 2020-09-10 05:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0005_auto_20200909_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageSectionContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(help_text='Name of the section, will not appear in the landing page', max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(help_text='Name of the section, for identifier only, will not appear in landing page', max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text='Title of the section, may be left blank', max_length=255)),
                ('contents', models.ManyToManyField(blank=True, to='bims_theme.LandingPageSectionContent')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customtheme',
            name='landing_page_sections',
            field=models.ManyToManyField(blank=True, help_text='Landing page sections', null=True, to='bims_theme.LandingPageSection'),
        ),
    ]
