# Generated by Django 2.2.12 on 2020-09-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0006_auto_20200910_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(help_text='Menu item title', max_length=255)),
                ('url', models.URLField()),
                ('blank_target', models.BooleanField(default=False, help_text='Will open in a new tab')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customtheme',
            name='menu_items',
            field=models.ManyToManyField(blank=True, help_text='Extra menu items', null=True, to='bims_theme.MenuItem'),
        ),
    ]
