# Generated by Django 3.2.20 on 2023-07-12 07:45

import ckeditor_uploader.fields
import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0008_auto_20200924_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselheader',
            name='description_font_size',
            field=models.IntegerField(default=30, help_text='Specify the font size for the description. Value must be between 10 and 50.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', help_text='Select the alignment for both title and description text.', max_length=7),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic')], default='normal', help_text='Choose the text style for the title and description.', max_length=6),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_font_size',
            field=models.IntegerField(default=45, help_text='Specify the font size for the title. Value must be between 10 and 80.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='funders',
            field=models.ManyToManyField(blank=True, help_text='Specify funders to be featured on the landing page', null=True, related_name='theme_funders', to='bims_theme.Partner'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='funders_section_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the funders section', max_length=18),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='funders_section_order',
            field=models.PositiveIntegerField(default=0, help_text='The order of the funders section from the bottom'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='funders_section_title',
            field=models.CharField(default='FUNDERS', help_text='Title for the funders display section', max_length=100),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners_section_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the partners section', max_length=18),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners_section_order',
            field=models.PositiveIntegerField(default=1, help_text='The order of the partners section from the bottom'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners_section_title',
            field=models.CharField(default='PARTNERS', help_text='Title for the partners display section', max_length=100),
        ),
        migrations.AddField(
            model_name='landingpagesection',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the section', max_length=18),
        ),
        migrations.AlterField(
            model_name='landingpagesectioncontent',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
