# Generated by Django 4.1.10 on 2023-12-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('bims_theme', '0010_customtheme_navbar_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site this taxon group is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Associated Site'),
        ),
    ]
