# Generated by Django 4.2.8 on 2024-04-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0011_customtheme_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='auth_background',
            field=models.ImageField(blank=True, help_text='Background image for login/logout page.', null=True, upload_to=''),
        ),
    ]
