# Generated by Django 4.2.8 on 2024-04-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0012_customtheme_auth_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='hide_site_visit',
            field=models.BooleanField(default=False, help_text='Hide site visit in the landing page'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='location_site_name',
            field=models.CharField(default='Site', help_text='The name of the location site as it will appear in the dashboard, on landing pages, and in other user interfaces.'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='location_site_name_plural',
            field=models.CharField(default='Sites', help_text='The plural form of the location site name for use when referring to multiple sites.'),
        ),
    ]
