# Generated by Django 4.2.8 on 2024-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0013_customtheme_hide_site_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='login_modal_logo',
            field=models.ImageField(blank=True, help_text='Optional logo displayed in the login modal.', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='login_modal_title',
            field=models.CharField(blank=True, default='Login', help_text='Optional title text displayed in the login modal.', max_length=100),
        ),
    ]
