# Generated by Django 4.2.15 on 2024-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0014_customtheme_login_modal_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='footer_background',
            field=models.ImageField(blank=True, help_text='Background image for footer in landing page.', null=True, upload_to=''),
        ),
    ]
