# Generated by Django 4.2.16 on 2024-12-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0015_customtheme_footer_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselheader',
            name='full_screen_background',
            field=models.BooleanField(default=False),
        ),
    ]
