# Generated by Django 4.2.16 on 2025-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0016_carouselheader_full_screen_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesection',
            name='full_width',
            field=models.BooleanField(default=False, help_text='Enable this if you want the section to be full-width'),
        ),
    ]
