# Generated by Django 4.2.16 on 2025-08-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0017_landingpagesection_full_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='navbar_brand_divider_enabled',
            field=models.BooleanField(default=True, help_text='Show a vertical divider to the right of the navbar logo/brand.'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_custom_typography_enabled',
            field=models.BooleanField(default=False, help_text='Enable custom font for the navbar. If disabled, theme/site defaults are used.'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_font_family',
            field=models.CharField(blank=True, default='', help_text="CSS font-family for navbar text, e.g. 'Inter, system-ui, sans-serif'.", max_length=200),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_font_size_px',
            field=models.PositiveIntegerField(default=16, help_text='Navbar font size in pixels.'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_font_url',
            field=models.CharField(blank=True, default='', help_text='e.g. https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&family=Roboto+Condensed:wght@100;300;400;500;700&display=swap'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_font_weight',
            field=models.CharField(choices=[('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'Semibold (600)'), ('700', 'Bold (700)')], default='500', help_text='Navbar font weight.', max_length=3),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_letter_spacing_em',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Letter spacing in em (e.g. 0.00, 0.05, 0.10).', max_digits=4),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_text_case',
            field=models.CharField(choices=[('none', 'None'), ('uppercase', 'UPPERCASE'), ('lowercase', 'lowercase'), ('capitalize', 'Capitalize')], default='none', help_text='Transform case for navbar text.', max_length=12),
        ),
    ]
