# Generated by Django 4.2.16 on 2025-08-25 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0018_customtheme_navbar_brand_divider_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselheader',
            name='banner_fit',
            field=models.CharField(choices=[('cover', 'Cover (fill area, crop if needed)'), ('contain', 'Contain (no crop)'), ('natural', 'Natural size'), ('stretch', 'Stretch to fill')], default='cover', help_text='How the image scales in the banner.', max_length=10),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='banner_height_mode',
            field=models.CharField(choices=[('auto', 'Auto (image height)'), ('fixed_px', 'Fixed (px)'), ('viewport_vh', 'Viewport (vh)')], default='viewport_vh', help_text='How the banner height is determined.', max_length=12),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='banner_height_value',
            field=models.PositiveIntegerField(default=60, help_text='Height value in px (when fixed_px) or vh (when viewport_vh). Ignored for auto.'),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='banner_position_x',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Horizontal focal point.', max_length=6),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='banner_position_y',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='Vertical focal point.', max_length=6),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='', help_text='Override alignment for description only (empty = use default).', max_length=7),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_font_family',
            field=models.CharField(blank=True, default='', help_text='CSS font-family for description.', max_length=200),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_font_url',
            field=models.CharField(blank=True, default='', help_text='e.g. https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&family=Roboto+Condensed:wght@100;300;400;500;700&display=swap'),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_font_weight',
            field=models.CharField(choices=[('300', 'Light 300'), ('400', 'Regular 400'), ('500', 'Medium 500'), ('600', 'Semibold 600'), ('700', 'Bold 700')], default='400', help_text='Description font weight.', max_length=3),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_letter_spacing_em',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Description letter spacing in em.', max_digits=4),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_line_height_pct',
            field=models.PositiveIntegerField(default=130, help_text='Description line-height as percent.', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_offset_y_percent',
            field=models.PositiveIntegerField(default=58, help_text='Vertical position of description (0–100%, from top).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_alignment',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='', help_text='Override alignment for title only (empty = use default).', max_length=7),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_font_family',
            field=models.CharField(blank=True, default='', help_text="CSS font-family for title, e.g. 'Alegreya, serif'.", max_length=200),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_font_url',
            field=models.CharField(blank=True, default='', help_text='e.g. https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700&family=Roboto+Condensed:wght@100;300;400;500;700&display=swap'),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_font_weight',
            field=models.CharField(choices=[('300', 'Light 300'), ('400', 'Regular 400'), ('500', 'Medium 500'), ('600', 'Semibold 600'), ('700', 'Bold 700')], default='700', help_text='Title font weight.', max_length=3),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_letter_spacing_em',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Title letter spacing in em (e.g., 0.00, 0.05).', max_digits=4),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_line_height_pct',
            field=models.PositiveIntegerField(default=110, help_text='Title line-height as percent.', validators=[django.core.validators.MinValueValidator(80), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_offset_y_percent',
            field=models.PositiveIntegerField(default=42, help_text='Vertical position of title (0–100%, from top).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='description_font_size',
            field=models.IntegerField(default=30, help_text='Default description size (10–50).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='full_screen_background',
            field=models.BooleanField(default=False, help_text='Legacy. Prefer banner_fit.'),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], default='left', help_text='Default alignment for both title and description.', max_length=7),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='text_style',
            field=models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold'), ('italic', 'Italic')], default='normal', help_text='Default text style for title/description (fallback).', max_length=6),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='title_font_size',
            field=models.IntegerField(default=45, help_text='Default title size (10–80).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
