# Generated by Django 4.2.16 on 2025-08-25 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0019_carouselheader_banner_fit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselheader',
            name='description_offset_y_percent',
            field=models.PositiveIntegerField(default=30, help_text='Offset below the title in percent of slide height.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='title_font_size',
            field=models.IntegerField(default=60, help_text='Default title size (10–80).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='title_offset_y_percent',
            field=models.PositiveIntegerField(default=20, help_text='Vertical position of title (0–100%, from top).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
