# Generated by Django 4.2.16 on 2025-08-26 12:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0020_alter_carouselheader_description_offset_y_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Font family name as used in CSS (e.g., Inter, 'Noto Serif Display').", max_length=100)),
                ('css_url', models.URLField(help_text='Stylesheet URL (e.g., https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap)', max_length=512)),
                ('stack', models.CharField(blank=True, help_text="CSS font-family stack. Leave blank to use the 'name' only.", max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Custom fonts',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='carouselheader',
            name='description_font_family',
        ),
        migrations.RemoveField(
            model_name='carouselheader',
            name='description_font_url',
        ),
        migrations.RemoveField(
            model_name='carouselheader',
            name='title_font_family',
        ),
        migrations.RemoveField(
            model_name='carouselheader',
            name='title_font_url',
        ),
        migrations.RemoveField(
            model_name='customtheme',
            name='navbar_font_family',
        ),
        migrations.RemoveField(
            model_name='customtheme',
            name='navbar_font_url',
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='description_offset_y_percent',
            field=models.PositiveIntegerField(default=12, help_text='Offset below the title in percent of slide height.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='title_font_size',
            field=models.IntegerField(default=45, help_text='Default title size (10–80).', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='carouselheader',
            name='title_offset_y_percent',
            field=models.PositiveIntegerField(default=30, help_text='Vertical position of title (0–100%, from top).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='description_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_description_font', to='bims_theme.customfont'),
        ),
        migrations.AddField(
            model_name='carouselheader',
            name='title_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carousel_title_font', to='bims_theme.customfont'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='navbar_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_navbar_font', to='bims_theme.customfont'),
        ),
    ]
