# Generated by Django 4.2.16 on 2025-08-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0021_customfont_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesection',
            name='background',
            field=models.ImageField(blank=True, help_text='Optional image shown behind the section content. Use a large image for best results.', null=True, upload_to='landing_page_section_background'),
        ),
        migrations.AddField(
            model_name='landingpagesection',
            name='background_fit',
            field=models.CharField(choices=[('cover', 'Cover (fill area, crop if needed)'), ('contain', 'Contain (no crop)'), ('natural', 'Natural size'), ('stretch', 'Stretch to fill')], default='cover', help_text='How the background image is sized: • Cover = fill area, crop if needed; • Contain = fit inside, no crop (may leave gaps); • Natural = use image’s intrinsic size; • Stretch = force to fill width & height (may distort).', max_length=10),
        ),
        migrations.AddField(
            model_name='landingpagesection',
            name='background_position_x',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Horizontal focal point used when the image is cropped (Left/Center/Right).', max_length=6),
        ),
        migrations.AddField(
            model_name='landingpagesection',
            name='background_position_y',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='Vertical focal point used when the image is cropped (Top/Center/Bottom).', max_length=6),
        ),
        migrations.AddField(
            model_name='landingpagesection',
            name='section_height_mode',
            field=models.CharField(choices=[('auto', 'Auto (image height)'), ('fixed_px', 'Fixed (px)'), ('viewport_vh', 'Viewport (vh)')], default='viewport_vh', help_text='Height behavior: Auto = height grows with content; Fixed (px) = use min-height in pixels; Viewport (vh) = use min-height as % of viewport height.', max_length=12),
        ),
        migrations.AddField(
            model_name='landingpagesection',
            name='section_height_value',
            field=models.PositiveIntegerField(default=60, help_text='Numeric height value used when mode is Fixed (px) or Viewport (vh). Applied as min-height (e.g., 60 -> 60px or 60vh). Ignored when mode is Auto.'),
        ),
    ]
