# Generated by Django 4.2.16 on 2025-08-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0022_landingpagesection_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagesection',
            name='section_height_mode',
            field=models.CharField(choices=[('auto', 'Auto (image height)'), ('fixed_px', 'Fixed (px)'), ('viewport_vh', 'Viewport (vh)')], default='auto', help_text='Height behavior: Auto = height grows with content; Fixed (px) = use min-height in pixels; Viewport (vh) = use min-height as % of viewport height.', max_length=12),
        ),
        migrations.AlterField(
            model_name='landingpagesection',
            name='section_height_value',
            field=models.PositiveIntegerField(default=40, help_text='Numeric height value used when mode is Fixed (px) or Viewport (vh). Applied as min-height (e.g., 60 -> 60px or 60vh). Ignored when mode is Auto.', verbose_name='Min section height'),
        ),
    ]
