# Generated by Django 4.2.16 on 2025-08-26 14:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0023_alter_landingpagesection_section_height_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagesection',
            name='border_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Separator color. Leave blank to use the theme’s accent color.', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='landingpagesection',
            name='enable_border',
            field=models.BooleanField(default=True, help_text='Draw a separator line below this section.'),
        ),
    ]
