# Generated by Django 4.2.16 on 2025-08-26 15:07

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0024_landingpagesection_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='landing_page_occurrence_records_title',
            field=models.CharField(default='BIODIVERSITY OCCURRENCE RECORDS', help_text='Header title for the Biodiversity Occurrence Records section.', max_length=150),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='show_explore_map',
            field=models.BooleanField(default=True, help_text='Show the “Explore Map” button under the summary.'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='summary_background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Background color for the summary section.', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='summary_font',
            field=models.ForeignKey(blank=True, help_text='CSS font for the summary. Leave blank to use the site default.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bims_theme.customfont'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='summary_font_size_px',
            field=models.PositiveIntegerField(default=16, help_text='Base font size (px) for the summary content.'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='summary_text_case',
            field=models.CharField(choices=[('none', 'None'), ('uppercase', 'UPPERCASE'), ('lowercase', 'lowercase'), ('capitalize', 'Capitalize')], default='none', help_text='Text transform for summary content (e.g. UPPERCASE).', max_length=12),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='summary_text_color',
            field=colorfield.fields.ColorField(default='#111111', help_text='Text color used across the summary section.', image_field=None, max_length=18, samples=None),
        ),
    ]
