# Generated by Django 4.2.16 on 2025-08-26 15:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0025_customtheme_landing_page_occurrence_records_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtheme',
            name='summary_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Text color used across the summary section.', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
