# Generated by Django 4.2.16 on 2025-08-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0026_alter_customtheme_summary_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtheme',
            name='summary_font_size_px',
            field=models.PositiveIntegerField(default=23, help_text='Base font size (px) for the summary content.'),
        ),
    ]
