# Generated by Django 4.2.16 on 2025-09-03 11:56

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0027_alter_customtheme_summary_font_size_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='landing_page_occurrence_records_title_font',
            field=models.ForeignKey(blank=True, help_text='Font for the Biodiversity Occurrence Records title.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_occ_title_font', to='bims_theme.customfont'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='landing_page_occurrence_records_title_font_size_px',
            field=models.PositiveIntegerField(default=28, help_text='Occurrence Records title font size (px).'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='landing_page_occurrence_records_title_font_weight',
            field=models.CharField(choices=[('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'Semibold (600)'), ('700', 'Bold (700)')], default='500', help_text='Occurrence Records title font weight.', max_length=3),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='landing_page_occurrence_records_title_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Occurrence Records title text color.', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners_section_title_font',
            field=models.ForeignKey(blank=True, help_text='Font for the Partners section title.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_partners_title_font', to='bims_theme.customfont'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners_section_title_font_size_px',
            field=models.PositiveIntegerField(default=28, help_text='Partners title font size (px).'),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners_section_title_font_weight',
            field=models.CharField(choices=[('300', 'Light (300)'), ('400', 'Regular (400)'), ('500', 'Medium (500)'), ('600', 'Semibold (600)'), ('700', 'Bold (700)')], default='500', help_text='Partners title font weight.', max_length=3),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='partners_section_title_text_color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Partners title text color.', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='customtheme',
            name='show_explore_map',
            field=models.BooleanField(default=True, help_text='Show the "Explore" button under the summary. If disabled, it will show in the carousel'),
        ),
    ]
