# Generated by Django 4.2.26 on 2026-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0028_customtheme_landing_page_occurrence_records_title_font_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='Hex color code (e.g., #FF5733)', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Order of the color in the palette')),
            ],
            options={
                'verbose_name': 'Chart Color',
                'verbose_name_plural': 'Chart Colors',
                'ordering': ['order'],
            },
        ),
    ]
