# Generated by Django 4.2.26 on 2026-01-09 14:29

from django.db import migrations


def populate_chart_colors(apps, schema_editor):
    """Populate initial chart colors from renderPieChart function"""
    ChartColor = apps.get_model('bims_theme', 'ChartColor')

    colors = [
        '#8D2641', '#641f30',
        '#E6E188', '#D7CD47',
        '#9D9739', '#525351',
        '#618295', '#2C495A',
        '#39B2A3', '#17766B',
        '#859FAC', '#1E2F38'
    ]

    for index, color in enumerate(colors, start=1):
        ChartColor.objects.get_or_create(
            color=color,
            defaults={'order': index}
        )


def reverse_populate(apps, schema_editor):
    """Remove all chart colors"""
    ChartColor = apps.get_model('bims_theme', 'ChartColor')
    ChartColor.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0029_chartcolor'),
    ]

    operations = [
        migrations.RunPython(populate_chart_colors, reverse_populate),
    ]
