# Generated by Django 4.2.26 on 2026-01-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0030_populate_chart_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartcolor',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
