# Generated by Django 6.0.2 on 2026-08-17 15:21

import bims_theme.models.carousel_header
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bims_theme', '0031_alter_chartcolor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselheader',
            name='custom_css',
            field=models.TextField(blank=True, default='', help_text="Advanced: raw CSS injected for this slide only. Scope your rules to #carousel-item-&lt;id&gt; (this slide's id, shown after saving) so they don't affect other slides or the rest of the page. Style/script tags, @import, and javascript: URLs are rejected.", validators=[bims_theme.models.carousel_header.validate_carousel_custom_css]),
        ),
    ]
